	/*1149*/ {IDS_INSTRUMENT_NAME                      ,"Nome strumento"},
	/*1150*/ {IDS_CZECH                                ,"Cestina"},
	/*1151*/ {IDS_ENGLISH                              ,"English"},
	/*1152*/ {IDS_FRENCH                               ,"Français"},
	/*1153*/ {IDS_GERMAN                               ,"Deutsch"},
	/*1154*/ {IDS_HUNGARIAN                            ,"Magyar"},
	/*1155*/ {IDS_ITALIAN                              ,"Italiano"},
	/*1156*/ {IDS_NORWEGIAN                            ,"Norsk"},
	/*1157*/ {IDS_POLISH                               ,"Polski"},
	/*1158*/ {IDS_PORTUGUESE_BR                        ,"Português(BR)"},
	/*1159*/ {IDS_PORTUGUESE_PT                        ,"Português(PT)"},
	/*1160*/ {IDS_ROMANIAN                             ,"Limba Româna"},
	/*1161*/ {IDS_RUSSIAN                              ,"‰¸¶¶ª§¨"},
	/*1162*/ {IDS_SPANISH                              ,"Español"},
	/*1163*/ {IDS_SWEDISH                              ,"Svenska"},
	/*1164*/ {IDS_TURKISH                              ,"Türkçe"},
	/*1165*/ {IDS_LASEQ                                ,"L$#eq"},
	/*1166*/ {IDS_LAS                                  ,"L$#"},
	/*1167*/ {IDS_LAPEAK                               ,"L^picco"},
	/*1168*/ {IDS_LAPEAKMAX                            ,"L^picco(max)"},
	/*1169*/ {IDS_LASMAX                               ,"L$#max"},
	/*1170*/ {IDS_LASMIN                               ,"L$#min"},
	/*1171*/ {IDS_LASE                                 ,"L$#E"},
	/*1172*/ {IDS_EAS                                  ,"E$#"},
	/*1173*/ {IDS_EAS8                                 ,"E$#8"},
	/*1174*/ {IDS_EAS40                                ,"E$#40"},
	/*1175*/ {IDS_LASG                                 ,"L$# >"},
	/*1176*/ {IDS_LAPEAKG                              ,"L^picco >"},
	/*1177*/ {IDS_LEQ1S                                ,"L$#eq(1s)"},
	/*1178*/ {IDS_LCEQ                                 ,"LC#eq"},
	/*1179*/ {IDS_LAEQ                                 ,"LA#eq"},
	/*1180*/ {IDS_LWMAX                                ,"L$max"},
	/*1181*/ {IDS_LWMIN                                ,"L$min"},
	/*1182*/ {IDS_LWAVG                                ,"L$avg"},
	/*1183*/ {IDS_LWPEAK_MAX                           ,"L$max(max)"},
	/*1184*/ {IDS_LWPEAK_AVG                           ,"L$max(avg)"},
	/*1185*/ {IDS_LW                                   ,"L$"},
	/*1186*/ {IDS_LWDBK                                ,"L$#bk"},
	/*1187*/ {IDS_CMINUSA                              ,"LC#eq-LA#eq"},
	/*1188*/ {IDS_FREQWT                               ,"Ponderazione frequenza"},
	/*1189*/ {IDS_DETECTOR                             ,"Rivelatore"},
	/*1190*/ {IDS_PEAKWT                               ,"Ponderazione del picco"},
	/*1191*/ {IDS_INTEGRATIONMETHOD                    ,"Metodo di integrazione"},
	/*1192*/ {IDS_A                                    ,"A"},
	/*1193*/ {IDS_C                                    ,"C"},
	/*1194*/ {IDS_Z                                    ,"Z"},
	/*1195*/ {IDS_SLOW                                 ,"Slow"},
	/*1196*/ {IDS_FAST                                 ,"Fast"},
	/*1197*/ {IDS_IMPL                                 ,"Impl"},
	/*1198*/ {IDS_SLOWS                                ,"S"},
	/*1199*/ {IDS_FASTF                                ,"F"},
	/*1200*/ {IDS_IMPLI                                ,"I"},
	/*1201*/ {IDS_LINEAR                               ,"Lineare"},
	/*1202*/ {IDS_EXPONENTIAL                          ,"Esponenz."},
	/*1203*/ {IDS_RUNTIME                              ,"Tempo di misura:"},
	/*1204*/ {IDS_STARTED                              ,"Iniziato:"},
	/*1205*/ {IDS_TWA24                                ,"TWA"},
	/*1206*/ {IDS_PROJTWA                              ,"TWA Proiettato"},
	/*1207*/ {IDS_LEPD                                 ,"Lep,d"},
	/*1208*/ {IDS_DOSE                                 ,"DOSE"},
	/*1209*/ {IDS_PROJDOSE                             ,"Stima dose"},
	/*1210*/ {IDS_WEIGHTING                            ,"Ponderazione"},
	/*1211*/ {IDS_EXCHANGERATE                         ,"Fattore scambio"},
	/*1212*/ {IDS_SOUNDEXPOSURELEVEL                   ,"Livello esposizione rumore"},
	/*1213*/ {IDS_SOUNDEXPOSURE                        ,"Esposizione al rumore"},
	/*1214*/ {IDS_EXCEEDANCES                          ,"Superamenti"},
	/*1215*/ {IDS_COUNT                                ,"Conteggio"},
	/*1216*/ {IDS_DURATION                             ,"Durata"},
	/*1217*/ {IDS_SEA1                                 ,"SEA"},
	/*1218*/ {IDS_FREQWEIGHTINGZ                       ,"Ponderazione frequenza: Z"},
	/*1219*/ {IDS_STARTTIME                            ,"Inizio"},
	/*1220*/ {IDS_ENDTIME                              ,"Fine"},
	/*1221*/ {IDS_LEQ                                  ,"Leq"},
	/*1222*/ {IDS_LMAX                                 ,"Lmax"},
	/*1223*/ {IDS_LMIN                                 ,"Lmin"},
	/*1224*/ {IDS_VIEWOBA                              ,"Visualizza l'analizzatore"},
	/*1225*/ {IDS_VIEWSLM                              ,"Visualizza il fonometro"},
	/*1226*/ {IDS_NORMALIZE                            ,"Normalizza"},
	/*1227*/ {IDS_LOCATE                               ,"Trova >"},
	/*1228*/ {IDS_PLAY                                 ,"Riproduci"},
	/*1229*/ {IDS_ENTER                                ,"Invio"},
	/*1230*/ {IDS_CLOSE                                ,"Chiudi"},
	/*1231*/ {IDS_CLOSE_CENTERED                       ," ,Chiudi, "},
	/*1232*/ {IDS_LNPERCENTILES                        ,"Percentili Ln"},
	/*1233*/ {IDS_DATE                                 ,"Data"},
	/*1234*/ {IDS_TIME                                 ,"Tempo"},
	/*1235*/ {IDS_RUNTIMER                             ,"Durata"},
	/*1236*/ {IDS_BATTERY                              ,"Batterie"},
	/*1237*/ {IDS_USBPOWERED                           ,"Alimentato USB"},
	/*1238*/ {IDS_MEMORY                               ,"Memoria"},
	/*1239*/ {IDS_DATAFILES                            ,"Files dati"},
	/*1240*/ {IDS_FREE                                 ,"Libera"},
	/*1241*/ {IDS_OF                                   ,"di"},
	/*1242*/ {IDS_HR                                   ,"h"},
	/*1243*/ {IDS_MEASUREMENT_DESC                     ,"Descrizione della misura"},
	/*1244*/ {IDS_DEFAULTFILENAME                      ,"Nome della Misura"},
	/*1245*/ {IDS_SPLTRIGGER1                          ,"Livello di soglia SPL 1"},
	/*1246*/ {IDS_SPLTRIGGER2                          ,"Livello di soglia SPL 2"},
	/*1247*/ {IDS_PEAKTRIGGER1                         ,"Picco 1"},
	/*1248*/ {IDS_DB                                   ,"dB"},
	/*1249*/ {IDS_PERCENT                              ,"%"},
	/*1250*/ {IDS_1                                    ,"1"},
	/*1251*/ {IDS_2                                    ,"2"},
	/*1252*/ {IDS_3                                    ,"3"},
	/*1253*/ {IDS_4                                    ,"4"},
	/*1254*/ {IDS_5                                    ,"5"},
	/*1255*/ {IDS_6                                    ,"6"},
	/*1256*/ {IDS_OBARANGE                             ,"Gamma Filtri OBA"},
	/*1257*/ {IDS_NORMAL                               ,"Normale"},
	/*1258*/ {IDS_LOW                                  ,"Basso"},
	/*1259*/ {IDS_MANUAL_STOP                          ,"Stop manuale"},
	/*1260*/ {IDS_RUNTILLSTABLE                        ,"Stop quando stabile"},
	/*1261*/ {IDS_DELTA                                ,"Delta"},
	/*1262*/ {IDS_HMS                                  ,"hh:mm:ss"},
	/*1263*/ {IDS_TIMED_STOP                           ,"Stop temporizzato"},
	/*1264*/ {IDS_NAME                                 ,"Nome"},
	/*1265*/ {IDS_ENABLED                              ,"Abilitato"},
	/*1266*/ {IDS_THRESHOLD                            ,"Soglia"},
	/*1267*/ {IDS_CRITERION                            ,"Criterio"},
	/*1268*/ {IDS_AUTOCALCULATE                        ,"Auto-calcolo"},
	/*1269*/ {IDS_TRIGGERING                           ,"Soprasoglia"},
	/*1270*/ {IDS_OSHA1                                ,"OSHA-1"},
	/*1271*/ {IDS_OSHA2                                ,"OSHA-2"},
	/*1272*/ {IDS_ACGIH                                ,"ACGIH"},
	/*1273*/ {IDS_NIOSH                                ,"NIOSH"},
	/*1274*/ {IDS_IEC                                  ,"IEC"},
	/*1275*/ {IDS_3DB                                  ,"3 dB"},
	/*1276*/ {IDS_4DB                                  ,"4 dB"},
	/*1277*/ {IDS_5DB                                  ,"5 dB"},
	/*1278*/ {IDS_6DB                                  ,"6 dB"},
	/*1279*/ {IDS_TABLIVE                              ,"Istantaneo"},
	/*1280*/ {IDS_OVERALL                              ,"Globale"},
	/*1281*/ {IDS_TABSESSIONLOG                        ,"Registro"},
	/*1282*/ {IDS_TABGENERAL                           ,"Generale"},
	/*1283*/ {IDS_TABSLM                               ,"SLM"},
	/*1284*/ {IDS_TABDOSE1                             ,"Dosimetro1"},
	/*1285*/ {IDS_TABDOSE2                             ,"Dosimetro2"},
	/*1286*/ {IDS_TABTRIGGER                           ,"Soglie"},
	/*1287*/ {IDS_TABLN                                ,"Ln"},
	/*1288*/ {IDS_OBA                                  ,"Filtri OBA"},
	/*1289*/ {IDS_CONTROL                              ,"Controllo"},
	/*1290*/ {IDS_CP_DATAEXPLORER                      ," Esplora \n dati "},
	/*1291*/ {IDS_CP_CALIBRATE                         ,"Calibra"},
	/*1292*/ {IDS_CALIBRATE                            ,"Calibra"},
	/*1293*/ {IDS_CP_LOCK                              ,"Blocca"},
	/*1294*/ {IDS_CP_ABOUT                             ,"A proposito di"},
	/*1295*/ {IDS_CP_SYSTEMPROPERTIES                  ," Proprietà \n del sistema "},
	/*1296*/ {IDS_CP_VOICERECORDER                     ," Registratore \n vocale "},
	/*1297*/ {IDS_TABSABOUT1                           ,"A proposito di"},
	/*1298*/ {IDS_TABSABOUT2                           ,"Norme"},
	/*1299*/ {IDS_TABSABOUT3                           ,"Opzioni"},
	/*1300*/ {IDS_TABSABOUT4                           ,"Utente"},
	/*1301*/ {IDS_TABSCAL1                             ,"Calibra"},
	/*1302*/ {IDS_TABSCAL2                             ,"Storia"},
	/*1303*/ {IDS_TABSCAL3                             ,"Certificazione"},
	/*1304*/ {IDS_MENU                                 ,"Menu"},
	/*1305*/ {IDS_TITLE_CONTROL_PANEL                  ,"Pannello di controllo"},
	/*1306*/ {IDS_TITLE_ABOUT                          ,"A proposito di"},
	/*1307*/ {IDS_TITLE_CALIBRATE                      ,"Utilità di calibrazione"},
	/*1308*/ {IDS_TITLE_SYSTEMPROPERTIES               ,"Proprietà del sistema"},
	/*1309*/ {IDS_TITLE_VOICE_RECORDER                 ,"Registratore vocale"},
	/*1310*/ {IDS_TITLE_DATA_EXPLORER                  ,"Esplora dati"},
	/*1311*/ {IDS_SERIALNUMBER                         ,"Numero di serie:"},
	/*1312*/ {IDS_MANUFACTURED                         ,"Prodotto da:"},
	/*1313*/ {IDS_STANDARDS                            ,"Norme"},
	/*1314*/ {IDS_LARSONDAVIS                          ,"Larson Davis"},
	/*1315*/ {IDS_PREC_INT_SLM_1                       ,"Integratore di precisione"},
	/*1316*/ {IDS_PREC_INT_SLM_2                       ,"Misuratore di livello sonoro"},
	/*1317*/ {IDS_FULLOCTAVE                           ,"1/1 ottava"},
	/*1318*/ {IDS_VOICEANNOTATION                      ,"Appunti vocali"},
	/*1319*/ {IDS_OWNER                                ,"Questo strumento è di:"},
	/*1320*/ {IDS_OPTION                               ,"Opzioni"},
	/*1321*/ {IDS_TABSSYSPROP1                         ,"Dispositivo"},
	/*1322*/ {IDS_TABSSYSPROP2                         ,"Tempo"},
	/*1323*/ {IDS_TABSSYSPROP3                         ,"Energia"},
	/*1324*/ {IDS_TABSSYSPROP4                         ,"Preferenze"},
	/*1325*/ {IDS_INSTRUMENTIDENTIFICATION             ,"Identificazione strumento"},
	/*1326*/ {IDS_AUTOOFFTIME                          ,"T. auto-Off"},
	/*1327*/ {IDS_POWERSAVETIME                        ,"T. salva energia"},
	/*1328*/ {IDS_BACKLIGHTTIME                        ,"T. retroillumin."},
	/*1329*/ {IDS_BACKLIGHTMODE                        ,"Retroilluminazione"},
	/*1330*/ {IDS_DISPLAYCONTRAST                      ,"Contrasto visore"},
	/*1331*/ {IDS_5MIN                                 ,"5 min"},
	/*1332*/ {IDS_10MIN                                ,"10 min"},
	/*1333*/ {IDS_30MIN                                ,"30 min"},
	/*1334*/ {IDS_60MIN                                ,"60 min"},
	/*1335*/ {IDS_NEVER                                ,"Mai"},
	/*1336*/ {IDS_5SEC                                 ,"5 s"},
	/*1337*/ {IDS_10SEC                                ,"10 s"},
	/*1338*/ {IDS_30SEC                                ,"30 s"},
	/*1339*/ {IDS_60SEC                                ,"60 s"},
	/*1340*/ {IDS_ALWAYSON                             ,"Sempre luminoso"},
	/*1341*/ {IDS_OFF                                  ,"Spento"},
	/*1342*/ {IDS_DIM                                  ,"Media"},
	/*1343*/ {IDS_BRIGHT                               ,"Luminoso"},
	/*1344*/ {IDS_LANGUAGE                             ,"Lingua"},
	/*1345*/ {IDS_RESETPROMPTING                       ,"Avvertimento per Reset"},
	/*1346*/ {IDS_RESETPROMPT                          ,"Azzera?"},
	/*1347*/ {IDS_DECIMALSYMBOL                        ,"Simbolo decimale"},
	/*1348*/ {IDS_DATEFORMAT                           ,"Formato data"},
	/*1349*/ {IDS_SYNCPC                               ,"Sincronizza Data/Ora con PC"},
	/*1350*/ {IDS_TAKTENABLED                          ,"Dati Takt Maximal"},
	/*1351*/ {IDS_COMMA                                ,"Virgola (,)"},
	/*1352*/ {IDS_PERIOD                               ,"Punto (.)"},
	/*1353*/ {IDS_DDMMMYYYY                            ,"g-m-a"},
	/*1354*/ {IDS_YYYYMMMDD                            ,"a-m-g"},
	/*1355*/ {IDS_V                                    ,"V"},
	/*1356*/ {IDS_ESTRUNTIME                           ,"Durata stimata"},
	/*1357*/ {IDS_BATTVOLTAGE                          ,"Voltaggio batteria"},
	/*1358*/ {IDS_TITLE_POWERCONTROL                   ,"Controllo alimentazione"},
	/*1359*/ {IDS_TEMPERATUREINT                       ,"T(interna)"},
	/*1360*/ {IDS_DEGREEF                              ,"°F"},
	/*1361*/ {IDS_DEGREEC                              ,"°C"},
	/*1362*/ {IDS_LOCKMODE                             ,"Blocca"},
	/*1363*/ {IDS_ALLOWCALWHENLOCKED                   ,"Consenti Cal. Quando bloccato"},
	/*1364*/ {IDS_LOCKCODE                             ,"Codice di sblocco"},
	/*1365*/ {IDS_UNLOCKED                             ,"Sbloccato"},
	/*1366*/ {IDS_LOCKAUTOSTORE                        ,"Blocca /AutoMemor."},
	/*1367*/ {IDS_LOCKMANUAL                           ,"Blocca /ManualMem."},
	/*1368*/ {IDS_FULLYLOCKED                          ,"Blocco totale"},
	/*1369*/ {IDS_POWERCONTROLNAV                      ,"Spento,Chiudi,Setup"},
	/*1370*/ {IDS_SYSDATE                              ,"Data del sistema"},
	/*1371*/ {IDS_SYSTIME                              ,"Ora del sistema"},
	/*1372*/ {IDS_JAN                                  ,"Gen."},
	/*1373*/ {IDS_FEB                                  ,"Feb."},
	/*1374*/ {IDS_MAR                                  ,"Mar."},
	/*1375*/ {IDS_APR                                  ,"Apr."},
	/*1376*/ {IDS_MAY                                  ,"Mag."},
	/*1377*/ {IDS_JUN                                  ,"Giu."},
	/*1378*/ {IDS_JUL                                  ,"Lug."},
	/*1379*/ {IDS_AUG                                  ,"Ago"},
	/*1380*/ {IDS_SEP                                  ,"Set."},
	/*1381*/ {IDS_OCT                                  ,"Ott."},
	/*1382*/ {IDS_NOV                                  ,"Nov."},
	/*1383*/ {IDS_DEC                                  ,"Dic."},
	/*1384*/ {IDS_AUTOSTOREMODE                        ,"Auto-memorizza"},
	/*1385*/ {IDS_AS_NONE                              ,"Nessuno"},
	/*1386*/ {IDS_AS_PROMPT                            ,"con Comando"},
	/*1387*/ {IDS_AS_STORE                             ,"Direttamente"},
	/*1388*/ {IDS_YES                                  ,"Sì"},
	/*1389*/ {IDS_NO                                   ,"No"},
	/*1390*/ {IDS_OK                                   ,"OK"},
	/*1391*/ {IDS_CANCEL                               ,"Cancella"},
	/*1392*/ {IDS_SAVE                                 ,"Salva"},
	/*1393*/ {IDS_SAVEAS                               ,"Salva come"},
	/*1394*/ {IDS_SETTINGS                             ,"Impostazioni"},
	/*1395*/ {IDS_APPLYCHANGES                         ,"Applica le modifiche?"},
	/*1396*/ {IDS_HISTORY                              ,"Storia"},
	/*1397*/ {IDS_PERFORMED                            ,"Eseguito:"},
	/*1398*/ {IDS_DUE                                  ,"Scadenza:"},
	/*1399*/ {IDS_CERTIFICATION                        ,"Certificazione"},
	/*1400*/ {IDS_INTERVAL                             ,"Intervallo"},
	/*1401*/ {IDS_REMINDER                             ,"Promemoria"},
	/*1402*/ {IDS_15DAYS                               ,"15 Giorni"},
	/*1403*/ {IDS_30DAYS                               ,"30 Giorni"},
	/*1404*/ {IDS_45DAYS                               ,"45 Giorni"},
	/*1405*/ {IDS_60DAYS                               ,"60 Giorni"},
	/*1406*/ {IDS_1YEAR                                ,"1 Anno"},
	/*1407*/ {IDS_2YEAR                                ,"2 Anni"},
	/*1408*/ {IDS_3YEAR                                ,"3 Anni"},
	/*1409*/ {IDS_4YEAR                                ,"4 Anni"},
	/*1410*/ {IDS_DESCRIPTION                          ,"Descrizione"},
	/*1411*/ {IDS_HZ                                   ,"Hz"},
	/*1412*/ {IDS_CALIBRATOR                           ,"Calibratore"},
	/*1413*/ {IDS_CALIBRATING                          ,"In calibrazione"},
	/*1414*/ {IDS_TITLE_DATAVIEWER                     ,"Visualizzatore dei dati"},
	/*1415*/ {IDS_TABSDATAVIEWER1                      ,"Data"},
	/*1416*/ {IDS_TABSDATAVIEWER2                      ,"Sessione Registro"},
	/*1417*/ {IDS_LEVEL1                               ,"SPL 1"},
	/*1418*/ {IDS_LEVEL2                               ,"SPL 2"},
	/*1419*/ {IDS_SPLTRIGGER                           ,"Livelli conteggio superamenti"},
	/*1420*/ {IDS_LEVEL                                ,"Livello"},
	/*1421*/ {IDS_UNLOCKPROMPT                         ,"Immettere codice a 4 cifre"},
	/*1422*/ {IDS_UNLOCK                               ,"Sblocca"},
	/*1423*/ {IDS_LOCKED1                              ,"Questo strumento è stato"},
	/*1424*/ {IDS_LOCKED2                              ,"BLOCCATO"},
	/*1425*/ {IDS_LOCKED3                              ,"Premi il pulsante Utensili per"},
	/*1426*/ {IDS_LOCKED4                              ,"SBLOCCATO"},
	/*1427*/ {IDS_INVALIDCODE                          ,"Codice non valido"},
	/*1428*/ {IDS_CAL                                  ,"Cal."},
	/*1429*/ {IDS_RUN                                  ,"Avvio"},
	/*1430*/ {IDS_CONFIRM                              ,"Siete sicuri?"},
	/*1431*/ {IDS_WARNING                              ,"Attenzione!"},
	/*1432*/ {IDS_CERTEXPIRING1                        ,"La certificazione scadrà in\n"},
	/*1433*/ {IDS_CERTEXPIRING2                        ,"giorni"},
	/*1434*/ {IDS_CERTEXPIRED                          ,"La certificazione è scaduta"},
	/*1435*/ {IDS_RESETREQ                             ,"Occorre azzerare"},
	/*1436*/ {IDS_STOPREQ                              ,"Occorre fermare"},
	/*1437*/ {IDS_SAVEFILE                             ,"Salva il file?"},
	/*1438*/ {IDS_BROWSE                               ,"Indaga"},
	/*1439*/ {IDS_FILELIST                             ,"Files"},
	/*1440*/ {IDS_CONTEXTMENU                          ,"Menù"},
	/*1441*/ {IDS_MEASUREMENTOK                        ,"La misura è OK?"},
	/*1442*/ {IDS_CALFAILED                            ,"Calibrazione fallita"},
	/*1443*/ {IDS_SAVECAL                              ,"Salva il risultato?"},
	/*1444*/ {IDS_RECORD                               ,"Registra"},
	/*1445*/ {IDS_PLAYBACK                             ,"Riproduci"},
	/*1446*/ {IDS_SAVERECORDING                        ,"Salva la registrazione?"},
	/*1447*/ {IDS_STOP                                 ,"Stop"},
	/*1448*/ {IDS_DENAVBUTTONS                         ," ,Chiudi, Menù"},
	/*1449*/ {IDS_VIEW                                 ,"Vedi"},
	/*1450*/ {IDS_DELETE                               ,"Cancella"},
	/*1451*/ {IDS_RENAME                               ,"Rinomina"},
	/*1452*/ {IDS_REFRESH                              ,"Rinnova la lista"},
	/*1453*/ {IDS_LOADSETTINGS                         ,"Carica le impostazioni"},
	/*1454*/ {IDS_RENAMEFILE                           ,"Rinomina il file?"},
	/*1455*/ {IDS_DELETEFILE                           ,"Cancella il file?"},
	/*1456*/ {IDS_OVERWRITEFILE                        ,"Sovrascrivi il file?"},
	/*1457*/ {IDS_FILENAME_EXISTS                      ,"Nome file esistente \n Sovrascrivo?"},
	/*1458*/ {IDS_BATTERYTYPE                          ,"Tipo di batteria"},
	/*1459*/ {IDS_ALKALINE                             ,"Alcalina"},
	/*1460*/ {IDS_NIMH                                 ,"NiMH"},
	/*1461*/ {IDS_MEASUREMENT                          ,"Misura"},
	/*1462*/ {IDS_PAUSE                                ,"Pausa"},
	/*1463*/ {IDS_RESUME                               ,"Continua"},
	/*1464*/ {IDS_VOICE                                ,"Voce"},
	/*1465*/ {IDS_SOUND                                ,"Audio"},
	/*1466*/ {IDS_KEY                                  ,"Da tastiera"},
	/*1467*/ {IDS_IO                                   ,"Commando USB"},
	/*1468*/ {IDS_TIMER                                ,"Temporizzatore"},
	/*1469*/ {IDS_POWER                                ,"alimentazione"},
	/*1470*/ {IDS_OUTOFMEMORY                          ,"Memoria esaurita"},
	/*1471*/ {IDS_COULDNTSAVE                          ,"Impossibile salvare"},
	/*1472*/ {IDS_ERROR                                ,"Errore!"},
	/*1473*/ {IDS_FIRMWAREREV                          ,"Rev. del firmware"},
	/*1474*/ {IDS_THIRDOCTAVE                          ,"1/3 Ottava"},
	/*1475*/ {IDS_PREAMP_CONNECT                       ,"Preamp Collegato"},
	/*1476*/ {IDS_PREAMP_DISCONNECT                    ,"Preamp scollegato"},
	/*1477*/ {IDS_JACKFUNC                             ,"Funzioni del Jack"},
	/*1478*/ {IDS_JACKFUNC_ACDC                        ,"AC/DC"},
	/*1479*/ {IDS_JACKFUNC_HEADSET                     ,"Cuffia"},
	/*1480*/ {IDS_SETTIME                              ,"Imposta ora"},
	/*1481*/ {IDS_UNLOCK1                              ,"Immetti codice a 4 cifre"},
	/*1482*/ {IDS_UNLOCK2                              ,"quando si sblocca."},
	/*1483*/ {IDS_UNAVAILABLE                          ,"Questa funzione non è ora disponibile"},
	/*1484*/ {IDS_TIMESET                              ,"L'ora è impostata"},
	/*1485*/ {IDS_SHUTDOWN_IMMINENT                    ,"Batterie scariche!\nImminente blocco alimentazione!\nSalvate il vostro lavoro!"},
	/*1486*/ {IDS_INSTINFO                             ,"Informazioni sullo strumento"},
	/*1487*/ {IDS_PREAMPTYPE                           ,"Preamp:"},
	/*1488*/ {IDS_STANDARDSINFO1                       ,"Questo strumento è conforme ai"},
	/*1489*/ {IDS_STANDARDSINFO2                       ,"seguenti standards"},
	/*1490*/ {IDS_OPTIONNAME                           ,"Nome della opzione"},
	/*1491*/ {IDS_SETTINGSLOCKED                       ,"Impostazioni utilizzate da PC.\nContinua?"},
	/*1492*/ {IDS_CP_SYSUTILS                          ,"Servizi\ndel sistema"},
	/*1493*/ {IDS_FSERRCORRECTED                       ,"Errore nel sistema dei files\nidentificato e riparato"},
	/*1494*/ {IDS_FSERRNOTCORRECTED                    ,"Corruzione nel sistema dei files\nVolete riformattare?"},
	/*1495*/ {IDS_TITLE_SYSUTIL                        ,"Servizi del sistema"},
	/*1496*/ {IDS_TABSYSUTIL1                          ,"Sistema dei files"},
	/*1497*/ {IDS_CHECK                                ,"Controlla i files"},
	/*1498*/ {IDS_FORMAT                               ,"Formatta"},
	/*1499*/ {IDS_FORMATALL                            ,"Formatta / Ritorna preimpostato"},
	/*1500*/ {IDS_DSPREV                               ,"Rev DSP:"},
	/*1501*/ {IDS_DELETEALLINTERNAL                    ,"Canc. tutta mem.interna"},
	/*1502*/ {IDS_CONFIRMDELETEALL                     ,"Cancella tutti i files?"},
	/*1503*/ {IDS_NOERRORS                             ,"Nessun errore\ntrovato"},
	/*1504*/ {IDS_OBABANDWIDTH                         ,"Banda analisi"},
	/*1505*/ {IDS_FULLTHIRDOCTAVE                      ,"1/1,1/3 di ottava"},
	/*1506*/ {IDS_INCOMPATIBLEBOOTLOADER               ,"Caricamento incompatibile.\nContattare la Spectra"},
	/*1507*/ {IDS_TABCURRENT                           ,"Attuale"},
	/*1508*/ {IDS_TABMEASUREMENT                       ,"Misura"},
	/*1509*/ {IDS_TABTIMEHISTORY                       ,"Profilo storico"},
	/*1510*/ {IDS_TABEVENTS                            ,"Eventi"},
	/*1511*/ {IDS_MARKSOUNDTYPE                        ,"Marca il tipo di rumore"},
	/*1512*/ {IDS_VIEWNORMALIZED                       ,"Vista Normalizzata"},
	/*1513*/ {IDS_OVERLOADS                            ,"Overloads"},
	/*1514*/ {IDS_LDN                                  ,"LDN"},
	/*1515*/ {IDS_LDEN                                 ,"LDEN"},
	/*1516*/ {IDS_TAKT                                 ,"LAFTM5"},
	/*1517*/ {IDS_COMMUNITYNOISE                       ,"Comunity Noise"},
	/*1518*/ {IDS_LINKTIMEHISTORY                      ,"Vedi il Profilo Storico"},
	/*1519*/ {IDS_RECORDNUM                            ,"Campione n.:"},
	/*1520*/ {IDS_LINKMEASUREMENTHISTORY1              ,"Collegamento ? Misura"},
	/*1521*/ {IDS_LINKMEASUREMENTHISTORY               ,"Vedi sequenza misure"},
	/*1522*/ {IDS_SAMPLENUM                            ,"Campione"},
	/*1523*/ {IDS_NUMMEASUREMENTS                      ,"Misure"},
	/*1524*/ {IDS_NUMEXCEEDANCES                       ,"Eventi"},
	/*1525*/ {IDS_NUMTIMEHISTORIES                     ,"Dati nel tempo"},
	/*1526*/ {IDS_ENTERBYFREQ                          ,"Attiva -> Vs. Frequenza"},
	/*1527*/ {IDS_ENTERBYTIME                          ,"Attiva -> Vs. Tempo"},
	/*1528*/ {IDS_PEAKTRIGGER2                         ,"Picco 2"},
	/*1529*/ {IDS_PEAKTRIGGER3                         ,"Picco 3"},
	/*1530*/ {IDS_DYNTRIGGEROFFSET                     ,"Offset Soglia Dinamica"},
	/*1531*/ {IDS_DYNAMICRESPONSE                      ,"Risposta Dinamica"},
	/*1532*/ {IDS_ATMAX                                ,"At Lmax"},
	/*1533*/ {IDS_BINMAX                               ,"Bin Max"},
	/*1534*/ {IDS_OBAMAXMODE                           ,"Spettro Max"},
	/*1535*/ {IDS_ENABLEMSMTHISTORY                    ,"Abilita misura profilo storico"},
	/*1536*/ {IDS_MEASUREMENTCOUNTER                   ,"Conteggio delle misure"},
	/*1537*/ {IDS_CONTINUOUS                           ,"Continua"},
	/*1538*/ {IDS_SINGLEBLOCK                          ,"Timer singolo periodo"},
	/*1539*/ {IDS_DAILYTIMER                           ,"Timer giornaliero"},
	/*1540*/ {IDS_RUNMODE                              ,"Modo"},
	/*1541*/ {IDS_MEASUREMENTTIME                      ,"Inizio misura"},
	/*1542*/ {IDS_CLOCKSYNC                            ,"Sincroniz. Durata Intervalli"},
	/*1543*/ {IDS_DAILYAUTOSTORE                       ,"Auto Memoriz."},
	/*1544*/ {IDS_AUTOSTORETIME                        ,"Inizio Auto Mem."},
	/*1545*/ {IDS_AUTOCALCHECK                         ,"Verifica Calibrazione"},
	/*1546*/ {IDS_AUTOCALCHECKTIME                     ,"Data della Verifica Calibrazione"},
	/*1547*/ {IDS_DAILY                                ,"Giornaliero"},
	/*1548*/ {IDS_TABEXCEEDANCEHISTORY                 ,"Storia degli Eventi"},
	/*1549*/ {IDS_TABMARKER                            ,"Marcatori"},
	/*1550*/ {IDS_ENABLETIMEHISTORY                    ,"Abilita Profilo Storico"},
	/*1551*/ {IDS_PERIOD1                              ,"Periodo"},
	/*1552*/ {IDS_100PS                                ,"10 ms"},
	/*1553*/ {IDS_50PS                                 ,"20 ms"},
	/*1554*/ {IDS_20PS                                 ,"50 ms"},
	/*1555*/ {IDS_10PS                                 ,"100 ms"},
	/*1556*/ {IDS_5PS                                  ,"200 ms"},
	/*1557*/ {IDS_2PS                                  ,"500 ms"},
	/*1558*/ {IDS_1S                                   ,"1 s"},
	/*1559*/ {IDS_2S                                   ,"2 s"},
	/*1560*/ {IDS_5S                                   ,"5 s"},
	/*1561*/ {IDS_10S                                  ,"10 s"},
	/*1562*/ {IDS_15S                                  ,"15 s"},
	/*1563*/ {IDS_20S                                  ,"20 s"},
	/*1564*/ {IDS_30S                                  ,"30 s"},
	/*1565*/ {IDS_1MIN                                 ,"1 min"},
	/*1566*/ {IDS_2MIN                                 ,"2 min"},
	/*1567*/ {IDS_15MIN                                ,"15 min"},
	/*1568*/ {IDS_20MIN                                ,"20 min"},
	/*1569*/ {IDS_1HR                                  ,"1 ora"},
	/*1570*/ {IDS_24HR                                 ,"24 ore"},
	/*1571*/ {IDS_LTWA1                                ,"Ltwa1"},
	/*1572*/ {IDS_LTWA2                                ,"Ltwa2"},
	/*1573*/ {IDS_LTWA3                                ,"Ltwa3"},
	/*1574*/ {IDS_LTWA4                                ,"Ltwa4"},
	/*1575*/ {IDS_LPEAK                                ,"Lpicco"},
	/*1576*/ {IDS_LTM5                                 ,"Ltm5"},
	/*1577*/ {IDS_OBALEQ                               ,"OBA Spettro Leq"},
	/*1578*/ {IDS_OBALMAX                              ,"OBA Spettro Lmax"},
	/*1579*/ {IDS_OBALMIN                              ,"OBA Spettro Lmin"},
	/*1580*/ {IDS_2102HUMIDITY                         ,"Preamp Umidità"},
	/*1581*/ {IDS_2102TEMPERATURE                      ,"Preamp Temp."},
	/*1582*/ {IDS_THOPTIONS                            ,"Opzione Profilo Storico"},
	/*1583*/ {IDS_TRIGGER_LEVEL                        ,"Livello"},
	/*1584*/ {IDS_TRIGGER_RISE_FALL                    ,"10dB Salita/Discesa"},
	/*1585*/ {IDS_TRIGGER_DYNAMIC                      ,"Dinamica"},
	/*1586*/ {IDS_ENABLEEXCDHISTORY                    ,"Storia degli Eventi"},
	/*1587*/ {IDS_MINIMUMDURATION                      ,"Durata Minima"},
	/*1588*/ {IDS_CONTPERIOD                           ,"Coda Evento"},
	/*1589*/ {IDS_TRIGGERMETHOD                        ,"Modo Trigger"},
	/*1590*/ {IDS_ENABLEEXCDTH                         ,"Profilo Eventi"},
	/*1591*/ {IDS_EXCDTHPERIOD                         ,"Campionamento"},
	/*1592*/ {IDS_ENABLEEXCDSPECTH                     ,"Modo analisi OBA"},
	/*1593*/ {IDS_SEC                                  ,"s"},
	/*1594*/ {IDS_VIEW15                               ,"1-5"},
	/*1595*/ {IDS_VIEW610                              ,"6-10"},
	/*1596*/ {IDS_PREREC                               ,"Durata Pre-trigger"},
	/*1597*/ {IDS_RECPERIOD                            ,"Durata Registrazione"},
	/*1598*/ {IDS_RECORDENABLE                         ,"Registrazione"},
	/*1599*/ {IDS_TABDAYNIGHT                          ,"Giorno/Notte"},
	/*1600*/ {IDS_TABAUDIO                             ,"Suono"},
	/*1601*/ {IDS_DAY                                  ,"Giorno"},
	/*1602*/ {IDS_EVENING                              ,"Sera"},
	/*1603*/ {IDS_NIGHT                                ,"Notte"},
	/*1604*/ {IDS_PENALTY                              ,"Penalità"},
	/*1605*/ {IDS_EXCDAUDIO                            ,"Eccedenza Audio"},
	/*1606*/ {IDS_SAVESNAPSHOT                         ,"Salva misura singola"},
	/*1607*/ {IDS_SNAPSHOTPERIOD                       ,"Durata Misura Singola"},
	/*1608*/ {IDS_PRETRIGGERPERIOD                     ,"Durata Pre-Triger"},
	/*1609*/ {IDS_MSMTAUDIO                            ,"Misura con Audio"},
	/*1610*/ {IDS_LEQA                                 ,"LAeq"},
	/*1611*/ {IDS_LPEAKA                               ,"LApicco"},
	/*1612*/ {IDS_LPEAKAMAX                            ,"LApicco(max)"},
	/*1613*/ {IDS_SLOWLMAXA                            ,"LASmax"},
	/*1614*/ {IDS_FASTLMAXA                            ,"LAFmax"},
	/*1615*/ {IDS_IMPLMAXA                             ,"LAImax"},
	/*1616*/ {IDS_SLOWLMINA                            ,"LASmin"},
	/*1617*/ {IDS_FASTLMINA                            ,"LAFmin"},
	/*1618*/ {IDS_IMPLMINA                             ,"LAImin"},
	/*1619*/ {IDS_LEQC                                 ,"LCeq"},
	/*1620*/ {IDS_LPEAKC                               ,"LCpicco"},
	/*1621*/ {IDS_LPEAKCMAX                            ,"LCpicco(max)"},
	/*1622*/ {IDS_SLOWLMAXC                            ,"LCSmax"},
	/*1623*/ {IDS_FASTLMAXC                            ,"LCFmax"},
	/*1624*/ {IDS_IMPLMAXC                             ,"LCImax"},
	/*1625*/ {IDS_SLOWLMINC                            ,"LCSmin"},
	/*1626*/ {IDS_FASTLMINC                            ,"LCFmin"},
	/*1627*/ {IDS_IMPLMINC                             ,"LCImin"},
	/*1628*/ {IDS_LEQZ                                 ,"LZeq"},
	/*1629*/ {IDS_LPEAKZ                               ,"LZpicco"},
	/*1630*/ {IDS_LPEAKZMAX                            ,"LZpicco(max)"},
	/*1631*/ {IDS_SLOWLMAXZ                            ,"LZSmax"},
	/*1632*/ {IDS_FASTLMAXZ                            ,"LZFmax"},
	/*1633*/ {IDS_IMPLMAXZ                             ,"LZImax"},
	/*1634*/ {IDS_SLOWLMINZ                            ,"LZSmin"},
	/*1635*/ {IDS_FASTLMINZ                            ,"LZFmin"},
	/*1636*/ {IDS_IMPLMINZ                             ,"LZImin"},
	/*1637*/ {IDS_EXTPOWER                             ,"Alimentaz. Ext."},
	/*1638*/ {IDS_INTTEMP                              ,"Temp. Interna"},
	/*1639*/ {IDS_WINDSPD                              ,"Velocità Vento"},
	/*1640*/ {IDS_ADC1AVG                              ,"ADC1 Avg."},
	/*1641*/ {IDS_ADC2AVG                              ,"ADC2 Avg."},
	/*1642*/ {IDS_OBALEQ11                             ,"OBA 1/1 Leq"},
	/*1643*/ {IDS_OBAMAX11                             ,"OBA 1/1 max"},
	/*1644*/ {IDS_OBAMIN11                             ,"OBA 1/1 min"},
	/*1645*/ {IDS_OBALEQ13                             ,"OBA 1/3 Leq"},
	/*1646*/ {IDS_OBAMAX13                             ,"OBA 1/3 max"},
	/*1647*/ {IDS_OBAMIN13                             ,"OBA 1/3 min"},
	/*1648*/ {IDS_ASLOWSPL                             ,"LAS"},
	/*1649*/ {IDS_AFASTSPL                             ,"LAF"},
	/*1650*/ {IDS_AIMPLSPL                             ,"LAI"},
	/*1651*/ {IDS_CSLOWSPL                             ,"LCS"},
	/*1652*/ {IDS_CFASTSPL                             ,"LCF"},
	/*1653*/ {IDS_CIMPLSPL                             ,"LCI"},
	/*1654*/ {IDS_ZSLOWSPL                             ,"LZS"},
	/*1655*/ {IDS_ZFASTSPL                             ,"LZF"},
	/*1656*/ {IDS_ZIMPLSPL                             ,"LZI"},
	/*1657*/ {IDS_OBASPL                               ,"OBA LPS"},
	/*1658*/ {IDS_OBASPL11                             ,"OBA 1/1 LPS"},
	/*1659*/ {IDS_OBASPL13                             ,"OBA 1/3 LPS"},
	/*1660*/ {IDS_USBSTORAGE                           ,"Memoria USB"},
	/*1661*/ {IDS_OVERWRITEFILES                       ,"Sovrascrivi sui files vecchi"},
	/*1662*/ {IDS_COMPRESSDATAFILE                     ,"Comprimi dati nei Files"},
	/*1663*/ {IDS_AUTO                                 ,"Auto rileva"},
	/*1664*/ {IDS_ENTERBY11FREQ                        ,"Enter -> Vs. 1/1 in Frequenza"},
	/*1665*/ {IDS_ENTERBY13FREQ                        ,"Enter -> Vs. 1/3 in Frequenza"},
	/*1666*/ {IDS_NORMALIZED_SPECTRUM                  ,"Spettro Normalizzato"},
	/*1667*/ {IDS_NORMALIZEDSPECTRUMNAV                ,"Imposta,Chiudi,Edit"},
	/*1668*/ {IDS_MARKSOUNDTYPE1NAV                    ,"Registra,Chiudi,Nessuno"},
	/*1669*/ {IDS_MARKSOUNDTYPE2NAV                    ,"Stop,Chiudi,Nessuno"},
	/*1670*/ {IDS_SPL                                  ,"LPS"},
	/*1671*/ {IDS_REF                                  ,"Rif:"},
	/*1672*/ {IDS_OBAFREQWT                            ,"Ponderaz.Freq."},
	/*1673*/ {IDS_FILE                                 ,"File"},
	/*1674*/ {IDS_NEGA                                 ,"-A"},
	/*1675*/ {IDS_NEGC                                 ,"-C"},
	/*1676*/ {IDS_EDIT_SPECTRA                         ,"Modifica Spettro Riferimento"},
	/*1677*/ {IDS_SAVECHANGES                          ,"Salva le Modifiche?"},
	/*1678*/ {IDS_EDITSPECTRUMNAV                      ," ,Chiudi,Re.1kHz"},
	/*1679*/ {IDS_CANTRECORDWHILESTOPPED               ,"Lo Strumento deve essere\navviato per registrare."},
	/*1680*/ {IDS_WINDDIR                              ,"Dir. Vento"},
	/*1681*/ {IDS_THOPTIONSTURNEDOFF                   ,"Alcune opzioni dei profili storici\nsono state disattivate."},
	/*1682*/ {IDS_SOUNDREC                             ,"Registrazione Audio"},
	/*1683*/ {IDS_DATALOGGING                          ,"Profilo storico"},
	/*1684*/ {IDS_ANYDATA                              ,"Tutti i Dati"},
	/*1685*/ {IDS_INTERVALS                            ,"Storia delle misure"},
	/*1686*/ {IDS_WEATHER                              ,"Meteo"},
	/*1687*/ {IDS_GAIN                                 ,"+20dB di Guadagno"},
	/*1688*/ {IDS_NODATA                               ,"Nessun Dato"},
	/*1689*/ {IDS_EXTPOWERED                           ,"Alimentazione Esterna"},
	/*1690*/ {IDS_LDAY                                 ,"Lgiorno"},
	/*1691*/ {IDS_LEVENING                             ,"Lsera"},
	/*1692*/ {IDS_LNIGHT                               ,"Lnotte"},
	/*1693*/ {IDS_INVALIDDATES                         ,"Avvio non valido/data arresto"},
	/*1694*/ {IDS_PLEASEWAIT                           ,"Attendere..."},
	/*1695*/ {IDS_PARTIAL                              ,"Parziale"},
	/*1696*/ {IDS_TIMERSLOST                           ,"Il timer giornaliero\nsarà perso\ncontinuare?"},
	/*1697*/ {IDS_LTWA                                 ,"LTWA"},
	/*1698*/ {IDS_LOWMEMSTOP                           ,"Fine memoria\narresto misura."},
	/*1699*/ {IDS_SETTINGSMAYCHANGE                    ,"Alcune opzioni possono variare\ncausa campionamento\ndel profilo storico."},
	/*1700*/ {IDS_PREAMP_DISPLAY                       ,"Preamp Interface"},
	/*1701*/ {IDS_TABSSYSPROP5                         ,"Visualizza"},
	/*1702*/ {IDS_TABS                                 ,"Tabs"},
	/*1703*/ {IDS_PAGES                                ,"Pagine"},
	/*1704*/ {IDS_STARTTAB                             ,"Avvia"},
	/*1705*/ {IDS_DISP_PROFILE                         ,"Profilo"},
	/*1706*/ {IDS_DISP_11                              ,"1/1 Ottave"},
	/*1707*/ {IDS_DISP_13                              ,"1/3 Ottave"},
	/*1708*/ {IDS_DISP_TRIGGER                         ,"Trigger"},
	/*1709*/ {IDS_DISP_POWER                           ,"Alimentazione"},
	/*1710*/ {IDS_DISP_LEQ                             ,"Leq"},
	/*1711*/ {IDS_DISP_DOSE1                           ,"Dose 1"},
	/*1712*/ {IDS_DISP_DOSE2                           ,"Dose 2"},
	/*1713*/ {IDS_DISP_SEL                             ,"SEL"},
	/*1714*/ {IDS_DISP_PERCENTILES                     ,"Percentili"},
	/*1715*/ {IDS_DISP_EXCEEDANCES                     ,"Superamenti"},
	/*1716*/ {IDS_DISP_SEA                             ,"S.E.A."},
	/*1717*/ {IDS_DISP_OVERLOAD                        ,"Overloads"},
	/*1718*/ {IDS_DISP_MEMORY                          ,"Memoria"},
	/*1719*/ {IDS_DISP_COMMUNITY                       ,"Community Noise"},
	/*1720*/ {IDS_DISP_MISC                            ,"Varie"},
	/*1721*/ {IDS_DISP_HISTORY                         ,"Storia"},
	/*1722*/ {IDS_DISP_METRICS                         ,"Unità"},
	/*1723*/ {IDS_DISP_TIMEHISTORY                     ,"Profilo storico"},
	/*1724*/ {IDS_DISP_SPECTRAL_TIMEHISTORY            ,"Profilo frequenze"},
	/*1725*/ {IDS_NODISPLAYENABLED                     ," Almeno una \n pagina va attivata. "},
	/*1726*/ {IDS_GRAPHSETTINGS                        ,"Regola il Grafico"},
	/*1727*/ {IDS_GRAPHHEIGHT                          ,"Sopra"},
	/*1728*/ {IDS_GRAPHBOTTOM                          ,"Sotto"},
	/*1729*/ {IDS_CLOSEWND                             ,"'Enter' per chiudere"},
	/*1730*/ {IDS_SETUPMANAGER                         ," Gestione \n Setup "},
	/*1731*/ {IDS_COULDNTLOAD                          ,"Incapace caricare file"},
	/*1732*/ {IDS_TABWEATHER                           ,"Dati meteo"},
	/*1733*/ {IDS_COMPASS                              ,"Bussola"},
	/*1734*/ {IDS_DEGREES                              ,"Gradi"},
	/*1735*/ {IDS_PERCENT_TEXT                         ,"Percento"},
	/*1736*/ {IDS_VOLTS                                ,"Volt"},
	/*1737*/ {IDS_SCALE                                ,"Scala"},
	/*1738*/ {IDS_UNITS                                ,"Unità"},
	/*1739*/ {IDS_OFFSET                               ,"Offset"},
	/*1740*/ {IDS_WINDTHRESHOLD                        ,"Soglia"},
	/*1741*/ {IDS_WINDEXCDLEVEL                        ,"Soglia superata"},
	/*1742*/ {IDS_WINDHYSTERESIS                       ,"Isteresi"},
	/*1743*/ {IDS_WINDPAUSE                            ,"Pausa"},
	/*1744*/ {IDS_WIND                                 ,"Vento"},
	/*1745*/ {IDS_HIGH                                 ,"Alto"},
	/*1746*/ {IDS_DESC                                 ,"a scendere"},
	/*1747*/ {IDS_COULDNTSAVEUSB                       ,"Non posso salvare file in\nuscita USB."},
	/*1748*/ {IDS_SAVETOUSB                            ,"Salva su USB"},
	/*1749*/ {IDS_WINDY                                ,"Ventoso"},
	/*1750*/ {IDS_AVG                                  ,"Media"},
	/*1751*/ {IDS_GUST                                 ,"Raffica"},
	/*1752*/ {IDS_GUSTSPEED                            ,"Velocità raffica"},
	/*1753*/ {IDS_ADC1MAX                              ,"ADC1 Max"},
	/*1754*/ {IDS_ADC1MIN                              ,"ADC1 Min"},
	/*1755*/ {IDS_ADC2MAX                              ,"ADC2 Max"},
	/*1756*/ {IDS_ADC2MIN                              ,"ADC2 Min"},
	/*1757*/ {IDS_LAE                                  ,"LAE"},
	/*1758*/ {IDS_LCE                                  ,"LCE"},
	/*1759*/ {IDS_LZE                                  ,"LZE"},
	/*1760*/ {IDS_OPT_DOSE                             ,"Igiene Industriale"},
	/*1761*/ {IDS_SPECLNMODE                           ,"Modo Spettri LN"},
	/*1762*/ {IDS_SPECTRAL_LN                          ,"Spettri LN"},
	/*1763*/ {IDS_PEAK                                 ,"Picco"},
	/*1764*/ {IDS_SPL_S                                ,"LPS S"},
	/*1765*/ {IDS_SPL_F                                ,"LPS f"},
	/*1766*/ {IDS_SPL_I                                ,"LPS I"},
	/*1767*/ {IDS_MAX_S                                ,"Max S"},
	/*1768*/ {IDS_MAX_F                                ,"Max F"},
	/*1769*/ {IDS_MAX_I                                ,"Max I"},
	/*1770*/ {IDS_MIN_S                                ,"Min S"},
	/*1771*/ {IDS_MIN_F                                ,"Min F"},
	/*1772*/ {IDS_MIN_I                                ,"Min I"},
	/*1773*/ {IDS_OCCURANCE                            ,"Accadimento"},
	/*1774*/ {IDS_GPS                                  ,"GPS"},
	/*1775*/ {IDS_COMMUNICATION                        ,"Communicazione"},
	/*1776*/ {IDS_WIRELESS                             ,"Wireless"},
	/*1777*/ {IDS_MODEM                                ,"Modem"},
	/*1778*/ {IDS_EXCD                                 ,"Superamento"},
	/*1779*/ {IDS_ALARM                                ,"Allarme"},
	/*1780*/ {IDS_BOTH                                 ,"Entrambi"},
	/*1781*/ {IDS_DIALOUT                              ,"Chiamata con:"},
	/*1782*/ {IDS_MONITORNUMBER                        ,"Monitor #"},
	/*1783*/ {IDS_PHONENUMBER                          ,"Telefono #"},
	/*1784*/ {IDS_MODEMPASSWORD                        ,"Password"},
	/*1785*/ {IDS_INITSTRING                           ,"Stringa Inizial."},
	/*1786*/ {IDS_ON                                   ,"Acceso"},
	/*1787*/ {IDS_NONE                                 ,"Nessuno"},
	/*1788*/ {IDS_PRETRIGGER                           ,"Pre-trigger"},
	/*1789*/ {IDS_MAX_SAMPLES                          ,"Campioni max"},
	/*1790*/ {IDS_LATITUDE                             ,"Latitudine"},
	/*1791*/ {IDS_LONGITUDE                            ,"Longitudine"},
	/*1792*/ {IDS_ELEVATION                            ,"Altezza"},
	/*1793*/ {IDS_GPSTIME                              ,"Acquisito a"},
	/*1794*/ {IDS_FEET                                 ,"Piedi"},
	/*1795*/ {IDS_METERS                               ,"Metri"},
	/*1796*/ {IDS_LOCALIZATION                         ,"Localizzazione"},
	/*1797*/ {IDS_GPSMODE                              ,"Modo GPS"},
	/*1798*/ {IDS_GPSSYNC                              ,"Sincronizzato GPS"},
	/*1799*/ {IDS_GPSNOSYNC                            ,"GPS non Sincronizzato"},
	/*1800*/ {IDS_WIRELESS_MODEM                       ,"Modem Wireless"},
	/*1801*/ {IDS_APN                                  ,"APN"},
	/*1802*/ {IDS_APNUSERNAME                          ,"Nome uso APN"},
	/*1803*/ {IDS_APNPASSWORD                          ,"Password APN"},
	/*1804*/ {IDS_UNITSSI                              ,"Sist. Internaz."},
	/*1805*/ {IDS_UNITSENGLISH                         ,"Inglese"},
	/*1806*/ {IDS_RICORRECTION                         ,"Correz.RI"},
	/*1807*/ {IDS_RI2FF                                ,"RI->FF"},
	/*1808*/ {IDS_FF2RI                                ,"FF->RI"},
	/*1809*/ {IDS_FF2RI_2106_8                         ,"FF:RI 2106/8"},
	/*1810*/ {IDS_FF2FF_2106_8                         ,"FF:FF 2106/8"},
	/*1811*/ {IDS_FF290_2106_8                         ,"FF:90 2106/8"},
	/*1812*/ {IDS_ENTERCHANGEREC                       ,"Enter->Cambia campione"},
	/*1813*/ {IDS_ENTERCHANGEMETRICS                   ,"Enter->Cambia Valore"},
	/*1814*/ {IDS_ENTERCHANGEEVENT                     ,"Enter->Cambia Eventi"},
	/*1815*/ {IDS_ENTERCHANGEFREQ                      ,"Enter->Cambia Frequenza"},
	/*1816*/ {IDS_EVENT                                ,"Eventi"},
	/*1817*/ {IDS_DELETEALLUSB                         ,"Cancella tutta la USB"},
	/*1818*/ {IDS_RANGE                                ,"Gamma"},
	/*1819*/ {IDS_IMPROPERSHUTDOWN                     ,"Spegnimento sbagliato"},
	/*1820*/ {IDS_RESETDATA                            ,"Il Dato sarà cancellato.\nSalvare il dato?"},
	/*1821*/ {IDS_EDIT                                 ,"Edit"},
	/*1822*/ {IDS_GPSGLOBALPOSITION                    ,"GPS Global Position"},
	/*1823*/ {IDS_COULDNTDELETE                        ,"Impossibile cancellare file"},
	/*1824*/ {IDS_USBHOSTPORT                          ,"Porta USB Host"},
	/*1825*/ {IDS_OPEN                                 ,"Apri"},
	/*1826*/ {IDS_USBHOSTPORTTURNEDOFF                 ,"Porta USB Host\nè stata spenta"},
	/*1827*/ {IDS_TIMEZONECORR                         ,"ora locale (h:m)"},
	/*1828*/ {IDS_CANNOTOVERWRITESYSFILE               ,"Non sovrascrivibili\nfiles di systema"},
	/*1829*/ {IDS_FILEINUSE_PC                         ,"Il file è già1nin uso dal PC"},
	/*1830*/ {IDS_OBALASEQ                             ,"L$#eq"},
	/*1831*/ {IDS_OBALASMAX                            ,"L$#max"},
	/*1832*/ {IDS_OBALASMIN                            ,"L$#min"},
	/*1833*/ {IDS_OBALAS                               ,"L$#"},
	/*1834*/ {IDS_HM                                   ,"hh:mm"},
	/*1835*/ {IDS_INVALIDMSMTTIME                      ,"Intervallo non  valido.\ndeve essere maggiore\n di 1 minuto."},
	/*1836*/ {IDS_CAL_CHECK                            ,"Verifica E.A."},
	/*1837*/ {IDS_LOGICIO                              ,"Logica I/O"},
	/*1838*/ {IDS_LOGICIN                              ,"Logica Ingresso"},
	/*1839*/ {IDS_LOGICOUT                             ,"Logica Uscita"},
	/*1840*/ {IDS_LOGICRUNSTATE                        ,"Condizione Run"},
	/*1841*/ {IDS_LOGICRUNSTOP                         ,"Run/Stop"},
	/*1842*/ {IDS_USBMOVECOMPLETE                      ,"Copia USB completata"},
	/*1843*/ {IDS_INVALIDTIMES                         ,"start/stop non valido"},
	/*1844*/ {IDS_MICROPHONE                           ,"Microfono"},
	/*1845*/ {IDS_TYPE                                 ,"Tipo"},
	/*1846*/ {IDS_SENSITIVITY                          ,"Sensibilità"},
	/*1847*/ {IDS_SELFNOISE                            ,"Rumore el."},
	/*1848*/ {IDS_OVERLOADLEVEL                        ,"Livello Overload"},
	/*1849*/ {IDS_UNDERRANGELEVEL                      ,"Livello sotto gamma"},
	/*1850*/ {IDS_NOISEFLOOR                           ,"Ruore di fondo"},
	/*1851*/ {IDS_MVPA                                 ,"mV/Pa"},
	/*1852*/ {IDS_CALOUTOFRANGE                        ,"Calibrazione fuori\ngamma normale. \nSalva comunque?"},
	/*1853*/ {IDS_PUBLISHED                            ,"Nominale"},
	/*1854*/ {IDS_INVALIDPERIOD                        ,"Il tempo di cattura deve essere \nmaggiore della durata\nminima dell'evento."},
	/*1855*/ {IDS_EVENTPTCHANGED                       ,"Tempo di pre-Trigger \nevento cambiato."},
	/*1856*/ {IDS_REMOVEUSBDRIVE                       ,"Ora potete rimuovere \nla penna USB."},
	/*1857*/ {IDS_T                                    ,"T:"},
	/*1858*/ {IDS_RH                                   ,"RH:"},
	/*1859*/ {IDS_DEWPOINT                             ,"Punto Rugiada"},
	/*1860*/ {IDS_OVERLOADIN                           ,"Overload In"},
	/*1861*/ {IDS_MAINSPOWER                           ,"Aliment. Ext."},
	/*1862*/ {IDS_CALIBRATOR_ON                        ,"Calib.Ext. ON"},
	/*1863*/ {IDS_SAMPLERATE                           ,"Velocità Campioni"},
	/*1864*/ {IDS_USBFILEEXISTS                        ,"Il file già esiste\nsulla chiave USB. \nFile non copiato."},
	/*1865*/ {IDS_SHORTED                              ,"Accorciato"},
	/*1866*/ {IDS_FAULT                                ,"Difetto:"},
	/*1867*/ {IDS_USBFILETOOLARGE                      ,"Spazio insufficiente\nsulla penna USB. \nOperazione annullata."},
	/*1868*/ {IDS_ENV                                  ,"LxT-ENV"},
	/*1869*/ {IDS_HDRCMINUSA                           ,"C meno A"},
	/*1870*/ {IDS_IMPULSIVITY                          ,"Impulsività"},
	/*1871*/ {IDS_LIEQ                                 ,"L$Ieq"},
	/*1872*/ {IDS_LACZEQ                               ,"L$eq"},
	/*1873*/ {IDS_LIEQMINUSLEQ                         ,"L$Ieq-L$eq"},
	/*1874*/ {IDS_HSLOG                                ,"LxT-HSLOG"},
	/*1875*/ {IDS_LITH                                 ,"Litio"},
	/*1876*/ {IDS_BACK5S                               ,"Indietro-5s"},
	/*1877*/ {IDS_BACK10S                              ,"Indietro-10s"},
	/*1878*/ {IDS_UNDOBACK                             ,"Annulla"},
	/*1879*/ {IDS_DUR_FRAC                             ,"Tms"},
	/*1880*/ {IDS_WSLOWSPL                             ,"L$S"},
	/*1881*/ {IDS_WFASTSPL                             ,"L$F"},
	/*1882*/ {IDS_WIMPLSPL                             ,"L$I"},
	/*1883*/ {IDS_DISP_PROFILE_LARGE                   ,"Espandi Profilo"},
	/*1884*/ {IDS_MS                                   ,"ms"},
	/*1885*/ {IDS_GRAPH_RELATIVE                       ,"Grafico Relativo"},
	/*1886*/ {IDS_REF1                                 ,"Ref"},
	/*1887*/ {IDS_NAME1                                ,"Nome:"},
	/*1888*/ {IDS_JUMP_TO_TOP                          ,"Salta all'inizio"},
	/*1889*/ {IDS_JUMP_TO_BOTTOM                       ,"Salta alla fine"},
	/*1890*/ {IDS_CALRANGEDIFF                         ,"Calibrazione variata \npiù di 0.5dB. \nSalva comunque?"},
	/*1891*/ {IDS_DENAVBUTTONS1                        ,"per file,Chiudi, Menù"},
	/*1892*/ {IDS_TABS_CAL_CHECK                       ,"E.A. attivo"},
	/*1893*/ {IDS_CAL_LEVEL                            ,"E.A. livello"},
	/*1894*/ {IDS_STD_CAL_LEVEL                        ,"Livello E.A. standard"},
	/*1895*/ {IDS_TABS_CAL_CHECK_HISTORY               ,"storia degli E.A. "},
	/*1896*/ {IDS_THLOCATE                             ,"Individua"},
	/*1897*/ {IDS_THFIRST                              ,"Primo"},
	/*1898*/ {IDS_THLAST                               ,"Ultimo"},
	/*1899*/ {IDS_THRECNUM                             ,"Numero Record"},
	/*1900*/ {IDS_SESSIONLOG                           ,"Archivio"},
	/*1901*/ {IDS_LAENEW                               ,"L$E"},
	/*1902*/ {IDS_RS232                                ,"RS-232"},
	/*1903*/ {IDS_BAUDRATE                             ,"Baud Rate"},
	/*1904*/ {IDS_B9600                                ,"9600"},
	/*1905*/ {IDS_B19200                               ,"19200"},
	/*1906*/ {IDS_B57600                               ,"57600"},
	/*1907*/ {IDS_B115200                              ,"115200"},
	/*1908*/ {IDS_DLYAUTOSTORENEVER                    ,"Mai"},
	/*1909*/ {IDS_DLYAUTOSTORE1                        ,"1/giorno"},
	/*1910*/ {IDS_DLYAUTOSTORE2                        ,"2/giorno"},
	/*1911*/ {IDS_DLYAUTOSTORE4                        ,"4/giorno"},
	/*1912*/ {IDS_DLYAUTOSTORE6                        ,"6/giorno"},
	/*1913*/ {IDS_DLYAUTOSTORE8                        ,"8/giorno"},
	/*1914*/ {IDS_DLYAUTOSTORE12                       ,"12/giorno"},
	/*1915*/ {IDS_DLYAUTOSTORE24                       ,"24/giorno"},
	/*1916*/ {IDS_DLYAUTOSTORE48                       ,"48/giorno"},
	/*1917*/ {IDS_DLYAUTOSTORE96                       ,"96/giorno"},
	/*1918*/ {IDS_DLYAUTOSTORE144                      ,"144/giorno"},
	/*1919*/ {IDS_FLOWCONTROL                          ,"Controllo Flusso"},
	/*1920*/ {IDS_FCNONE                               ,"Nessuno"},
	/*1921*/ {IDS_XONXOFF                              ,"Xon/Xoff"},
	/*1922*/ {IDS_HARDWARE                             ,"Hadware"},
	/*1923*/ {IDS_400PS                                ,"2.5 ms"},
	/*1924*/ {IDS_200PS                                ,"5 ms"},
	/*1925*/ {IDS_FST                                  ,"Time History Veloce"},
	/*1926*/ {IDS_PREPOSTTRIGGER                       ,"Pre/Post Trigger"},
	/*1927*/ {IDS_NOTIFYUSBMOVE                        ,"Sto copiando su\nMemoria USB \nSpegni comunque?"},
	/*1928*/ {IDS_SETTINGSCONFLICT                     ,"Conflitto Impost. \nCorreggo da solo?"},
	/*1929*/ {IDS_FSTCONFLICT                          ,"Non attiva\ncon Time Hist.Veloce \nabilitata."},
	/*1930*/ {IDS_DISP_TRIG_STATUS                     ,"Condizione Trig. Eventi"},
	/*1931*/ {IDS_CAL_CHECK_SPECTRUM                   ,"Verifica Spettro E.A."},
	/*1932*/ {IDS_CALIBRATE_SPECTRUM                   ,"Spettro Calibrazione"},
	/*1933*/ {IDS_POWERINGOFF                          ,"Spegnimento"},
	/*1934*/ {IDS_FSTOBANOTIFY                         ,"OBA 1/1 Ottave \nè disabilitato"},
	/*1935*/ {IDS_MARK                                 ,"Marca"},
	/*1936*/ {IDS_GPSTIMESYNC                          ,"Sincr.Tempo"},
	/*1937*/ {IDS_DELTAT                               ,"Correzione"},
	/*1938*/ {IDS_EXCDPAUSE                            ,"Pausa Eccedenze"},
	/*1939*/ {IDS_ENABLEWEATHER                        ,"Abilita Meteo"},
	/*1940*/ {IDS_THNOTIFY                             ,"Nessuna opzione scelta\nla Time History \nsarà disabilitata."},
	/*1941*/ {IDS_EXTSHUTOFFVOLT                       ,"Soglia Tensione ext."},
	/*1942*/ {IDS_REPAIRUSB                            ,"Ripara/Verifica USB"},
	/*1943*/ {IDS_USBCHECKSTATUS                       ,"Ripara/Verifica USB \neseguita"},
	/*1944*/ {IDS_USBFILENOMOUNT                       ,"Sistema File USB non trovato"},
	/*1945*/ {IDS_USBNOCHECK                           ,"Ripara/Verifica/Formatta non possibile \nquando sto copiando"},
	/*1946*/ {IDS_USBFORMATSTATUS                      ,"Drive USB formattato"},
	/*1947*/ {IDS_FORMATUSB                            ,"Formatto USB"},
	/*1948*/ {IDS_ADV_COMM                             ,"Comunicazioni Avanz."},
	/*1949*/ {IDS_ANALOG_MODEM                         ,"Modem Analogico"},
	/*1950*/ {IDS_PASSWORD                             ,"Password"},
	/*1951*/ {IDS_DISP_FREQ11                          ,"1/1 Ottave per Frequenza"},
	/*1952*/ {IDS_DISP_FREQ13                          ,"1/3 Ottave per Frequenza"},
	/*1953*/ {IDS_DISP_TIME11                          ,"1/1 Ottave nel Tempo"},
	/*1954*/ {IDS_DISP_TIME13                          ,"1/3 Ottave nel Tempo"},
	/*1955*/ {IDS_USBSAVENOTIFY                        ,"Precedente spost. in esecuzione \noperazione non possibile"},
	/*1956*/ {IDS_BATTPOWERED                          ,"Aliment. a Batt"},
	/*1957*/ {IDS_DISP_SPTH_BYTIME                     ,"Profilo storico spettri (t)"},
	/*1958*/ {IDS_DAILYTIMERNOTIFY                     ,"Uno o più periodi sovrapposti"},
	/*1959*/ {IDS_INVALIDTIME                          ,"Periodo non valido. \nLa durata deve essere > 1 sec."},
	/*1960*/ {IDS_SAVESETUP                            ,"Cambiare la stringa attiva?"},
	/*1961*/ {IDS_STATUS                               ,"Condizione"},
	/*1962*/ {IDS_CHANNEL                              ,"Canale"},
	/*1963*/ {IDS_CURSTATE                             ,"Stato"},
	/*1964*/ {IDS_PREVSTATE                            ,"Precedente:"},
	/*1965*/ {IDS_IN                                   ,"In:"},
	/*1966*/ {IDS_OUT                                  ,"Uscita:"},
	/*1967*/ {IDS_TIMEOUT                              ,"Timeout:"},
	/*1968*/ {IDS_USB                                  ,"USB"},
	/*1969*/ {IDS_TIMERSLOST1                          ,"I periodi giornalieri \nsaranno disabilitati. \nContinuare?"},
	/*1970*/ {IDS_USBRMNOTIFY                          ,"Attendere durante \noperazione pulizia USB."},
	/*1971*/ {IDS_USBCOMMNOTIFY                        ,"Altre sorgenti comunicazione"},
	/*1972*/ {IDS_CALCHECK                             ,"Verifica calibrazione"},
	/*1973*/ {IDS_CALCHANGE                            ,"Nuova calibrazione"},
	/*1974*/ {IDS_CALIBRATIONCHANGED                   ,"Differenze rilevate"},
	/*1975*/ {IDS_CALCHECKDB                           ,"Livello (dB)"},
	/*1976*/ {IDS_CALCHANGEDB                          ,"Variazione (dB)"},
	/*1977*/ {IDS_FSTCONFLICT1                         ,"Conflitto impostazioni. \nProfilo in Fast abilitato."},
	/*1978*/ {IDS_SAVETOUSBALL                         ,"Scarica tutto su USB"},
	/*1979*/ {IDS_USBMOVENOTIFY                        ,"File usato\nnon copiabile."},
	/*1980*/ {IDS_USBDUPLICATENOTIFY                   ,"nome del file duplicato \ncambiare."},
	/*1981*/ {IDS_USBNOMOVENOTIFY                      ," Alcuni files non \ncopiati."},
	/*1982*/ {IDS_LN1                                  ,"Ln1"},
	/*1983*/ {IDS_LN2                                  ,"Ln2"},
	/*1984*/ {IDS_LN3                                  ,"Ln3"},
	/*1985*/ {IDS_LN4                                  ,"Ln4"},
	/*1986*/ {IDS_LN5                                  ,"Ln5"},
	/*1987*/ {IDS_LN6                                  ,"Ln6"},
	/*1988*/ {IDS_PAUSETIME                            ,"Durata Pausa:"},
	/*1989*/ {IDS_INVALIDMSMTTIME1                     ,"Durata intervallo invalida.\ndeve essere maggiore\ndi 1 secondo."},
	/*1990*/ {IDS_INVALIDMSMTTIME2                     ,"Intervallo di tempo invalido\nDeve essere 1 minuto\no maggiore."},
	/*1991*/ {IDS_FORMATFAILED                         ,"Formattazione file di Sistema\nfallita."},
	/*1992*/ {IDS_NOPLAYBACK                           ,"Play impossibile quando\nil modo autostore\n è attivato."},
	/*1993*/ {IDS_FILEINUSE                            ,"Impossibile aprire. File in uso."},
	/*1994*/ {IDS_PCBREV                               ,"Rev. PCB:"},
	/*1995*/ {IDS_SOUNDRECORDINGS                      ,"Registrazione Sonora"},
	/*1996*/ {IDS_FSCHECKNOTIFY                        ,"Lo strumento deve\n essere in Stop."},
	/*1997*/ {IDS_CANNOTDELETEFILE                     ,"Impossibile cancellare.\nFile in uso."},
	/*1998*/ {IDS_NOPLAYBACK1                          ,"Salva il File\nprima di riprodurlo."},
	/*1999*/ {IDS_CANNOTRENAME                         ,"Un File con stesso\nnome è in uso.\nNon riscrivibile."},
	/*2000*/ {IDS_CANNOTRENAMECOPY                     ,"Non rinominabile\nFile in uso."},
	/*2001*/ {IDS_PREAMPNOTSUPPORTED                   ,"Preamp non supportato"},
	/*2002*/ {IDS_STABLE                               ,"Stabile"},
	/*2003*/ {IDS_DEMO                                 ,"Demo"},
	/*2004*/ {IDS_BACKERASE                            ,"Cancello indietro"},
	/*2005*/ {IDS_PRINT                                ,"Stampa Riassunto"},
	/*2006*/ {IDS_DOSESETTINGS                         ,"Imposta Dose"},
	/*2007*/ {IDS_RESULTS                              ,"Risultati"},
	/*2008*/ {IDS_PRINTSCREEN                          ,"Stampa Schermo"},
	/*2009*/ {IDS_MTLMEASDESC                          ,"Descrizione\nMisura"},
	/*2010*/ {IDS_MTLCOMMUNITYNOISE                    ,"Rumore\nUrbano"},
	/*2011*/ {IDS_MTLLNPERCENTILE                      ,"Percentili\nLn"},
	/*2012*/ {IDS_MTLOVERALLSETTINGS                   ,"Imposta\nGlobali"},
	/*2013*/ {IDS_MTLPRINTSUCCESS                      ,"Stampa Terminata."},
	/*2014*/ {IDS_MTLNOPRINTER                         ,"Stampante non trovata."},
	/*2015*/ {IDS_MTLDISCONNECT                        ,"Stampante scollegata.\nStampa fallita."},
	/*2016*/ {IDS_DISP_PROFILE_LARGE1                  ,"Digitale"},
	/*2017*/ {IDS_DISPLAYWARNING                       ,"Schermi\nnon disattivabili."},
	/*2018*/ {IDS_TABSYSOPTIONS                        ,"Opzioni"},
	/*2019*/ {IDS_TABSMSOUT                            ,"Invio SMS"},
	/*2020*/ {IDS_SENDSMSON                            ,"Invio SMS Attivo"},
	/*2021*/ {IDS_MEMLOW                               ,"Poca Memoria"},
	/*2022*/ {IDS_SMSIN                                ,"SMS Ricevuto"},
	/*2023*/ {IDS_ALL                                  ,"Tutti"},
	/*2024*/ {IDS_WEATHERINT                           ,"Meteo-INT"},
	/*2025*/ {IDS_WEATHERVAISALA                       ,"Vaisala"},
	/*2026*/ {IDS_MAXRATE                              ,"Quantità massima"},
	/*2027*/ {IDS_ACCUMULATION                         ,"Accumulo"},
	/*2028*/ {IDS_RAINRATE                             ,"Quantità pioggia"},
	/*2029*/ {IDS_HAILRATE                             ,"Quantità Hale"},
	/*2030*/ {IDS_OPTIONSWARNING                       ,"Impossibile disattivare opzioni\nRiattivo le opzioni base."},
	/*2031*/ {IDS_OPTIONS                              ,"Opzioni"},
	/*2032*/ {IDS_OPTIONSCHANGED                       ,"Cambio di Opzioni\nPrego riavvia fonometro."},
	/*2033*/ {IDS_MM_PER_HOUR                          ,"mm/hr"},
	/*2034*/ {IDS_IN_PER_HOUR                          ,"in/hr"},
	/*2035*/ {IDS_HITS_PER_CM_SQ_HOUR                  ,"hits/cm²h"},
	/*2036*/ {IDS_HITS_PER_IN_SQ_HOUR                  ,"hits/in²h"},
	/*2037*/ {IDS_HITS_PER_CM_SQ                       ,"hits/cm²"},
	/*2038*/ {IDS_HITS_PER_IN_SQ                       ,"hits/in²"},
	/*2039*/ {IDS_METERS_PER_SEC                       ,"m/s"},
	/*2040*/ {IDS_MI_PER_HOUR                          ,"mi/h"},
	/*2041*/ {IDS_INCHES                               ,"in"},
	/*2042*/ {IDS_MILIMETERS                           ,"mm"},
	/*2043*/ {IDS_CENTIMETERS                          ,"cm"},
	/*2044*/ {IDS_PERCENT_RH                           ,"% RH"},
	/*2045*/ {IDS_EMPTY                                ," "},
	/*2046*/ {IDS_OPT_QC_TONALITY                      ,"Tonalità QC"},
	/*2047*/ {IDS_CORRECTED_DBA                        ,"dBA corretto"},
	/*2048*/ {IDS_CORR_OBALASEQ                        ,"Corr. L$#eq"},
	/*2049*/ {IDS_WARN_REVISION                        ,"Revisione Incompatibile\nper queste funzioni."},
	/*2050*/ {IDS_RS232_WILL_DISABLE                   ,"RS232 sarà Disattivata..."},
	/*2051*/ {IDS_VAISALA_WILL_DISABLE                 ,"Vaisala sarà Disattivata..."},
	/*2052*/ {IDS_Q_DISABLE_USB                        ,"Disattivare porta USB?"},
	/*2053*/ {IDS_TALARM                               ,"TA-Larm"},
	/*2054*/ {IDS_LN95                                 ,"Ln95"},
	/*2055*/ {IDS_LN                                   ,"Statistica Ln"},
	/*2056*/ {IDS_SLM                                  ,"SLM"},
	/*2057*/ {IDS_Q_CHANGE_MODES                       ,"Cambio Modalita?"},
	/*2058*/ {IDS_PRINTENFORCEMENT                     ,"Eseguo la Stampa"},
	/*2059*/ {IDS_PRINTCALIBRATION                     ,"Stampo la Calibrazione"},
	/*2060*/ {IDS_MTLLOCATION                          ,"Località:"},
	/*2061*/ {IDS_MTLBY                                ,"Di:"},
	/*2062*/ {IDS_MTLDEPT                              ,"Ente:"},
	/*2063*/ {IDS_CALIBRATION                          ,"Calibrazione"},
	/*2064*/ {IDS_SERIALNO                             ,"N. di Serie:"},
	/*2065*/ {IDS_REFSPL                               ,"SPL rif.:"},
	/*2066*/ {IDS_SELECT                               ,"Seleziona"},
	/*2067*/ {IDS_NEW                                  ,"Nuovo"},
	/*2068*/ {IDS_OLD                                  ,"Vecchio"},
	/*2069*/ {IDS_SAVE_CAL_STD_LVL                     ,"Salva %dB come\nLivello E.A. Standard?"},
	/*2070*/ {IDS_USB_LOW_POWER                        ,"Penna USB disattivata\nper alimentazione bassa."},
	/*2071*/ {IDS_SIL                                  ,"SIL"},
	/*2072*/ {IDS_DEVELOPER                            ,"Sviluppatore"},
	/*2073*/ {IDS_ROOM_ACOUSTICS_NL                    ,"Acustica degli\nAmbienti"},
	/*2074*/ {IDS_ROOM_ACOUSTICS                       ,"Acustica degli Ambienti"},
	/*2075*/ {IDS_RT60                                 ,"RT-60"},
	/*2076*/ {IDS_RT60_SR                              ,"RT-60 Audio Rec."},
	/*2077*/ {IDS_SOURCE                               ,"Sorgente"},
	/*2078*/ {IDS_RTA                                  ,"RTA"},
	/*2079*/ {IDS_RTA_SR                               ,"RT Audio Rec."},
	/*2080*/ {IDS_SPECTRA                              ,"Spettri"},
	/*2081*/ {IDS_PROJECT_NAME                         ,"Nome Progetto"},
	/*2082*/ {IDS_NOISE_RT60                           ,"Rumore RT-60"},
	/*2083*/ {IDS_NOISE_RTA                            ,"Rumore RTA"},
	/*2084*/ {IDS_NOISE                                ,"Rumore"},
	/*2085*/ {IDS_NOISE_WHITE                          ,"Bianco"},
	/*2086*/ {IDS_NOISE_PINK                           ,"Rosa"},
	/*2087*/ {IDS_AMPLITUDE                            ,"Ampiezza"},
	/*2088*/ {IDS_MUTE                                 ,"Silenzio"},
	/*2089*/ {IDS_1_1                                  ,"1/1"},
	/*2090*/ {IDS_1_3                                  ,"1/3"},
	/*2091*/ {IDS_IMPULSE                              ,"Impulso"},
	/*2092*/ {IDS_INT_NOISE                            ,"Rumore Inter."},
	/*2093*/ {IDS_TRIG_FREQ                            ,"Freq. di Trigger"},
	/*2094*/ {IDS_TRIG_SOURCE                          ,"Banda di Trigger"},
	/*2095*/ {IDS_BUILD_TIME                           ,"Sonorizzazione"},
	/*2096*/ {IDS_MAX_RUN_TIME                         ,"Durata misura"},
	/*2097*/ {IDS_SAVE_AVG_TS                          ,"Salva serie temporale mediata"},
	/*2098*/ {IDS_SAVE_ALL_TS                          ,"Salva ogni serie temporale"},
	/*2099*/ {IDS_EXIT_TIME                            ,"Tempo di uscita"},
	/*2100*/ {IDS_LOWEST_BAND                          ,"Filtro più basso"},
	/*2101*/ {IDS_HIGHEST_BAND                         ,"Filtro più alto"},
	/*2102*/ {IDS_ATTENUATION                          ,"Attenuazione"},
	/*2103*/ {IDS_ADVANCED                             ,"Avanzamento"},
	/*2104*/ {IDS_BACK                                 ,"Indietro"},
	/*2105*/ {IDS_T20                                  ,"T20"},
	/*2106*/ {IDS_T30                                  ,"T30"},
	/*2107*/ {IDS_EDT                                  ,"EDT"},
	/*2108*/ {IDS_SAMPLE                               ,"Campione"},
	/*2109*/ {IDS_ENSEMBLE                             ,"Media"},
	/*2110*/ {IDS_ENTER_CHANGE_DATA                    ,"Enter->Cambia Dato"},
	/*2111*/ {IDS_ENTER_CHANGE                         ,"Enter->Modifica"},
	/*2112*/ {IDS_METHOD                               ,"Metodo"},
	/*2113*/ {IDS_MID_BAND                             ,"Banda Centrale"},
	/*2114*/ {IDS_F_6_3                                ,"6.30 Hz"},
	/*2115*/ {IDS_F_8                                  ,"8.00 Hz"},
	/*2116*/ {IDS_F_10                                 ,"10.0 Hz"},
	/*2117*/ {IDS_F_12_5                               ,"12.5 Hz"},
	/*2118*/ {IDS_F_16                                 ,"16.0 Hz"},
	/*2119*/ {IDS_F_20                                 ,"20.0 Hz"},
	/*2120*/ {IDS_F_25                                 ,"25.0 Hz"},
	/*2121*/ {IDS_F_31_5                               ,"31.5 Hz"},
	/*2122*/ {IDS_F_40                                 ,"40.0 Hz"},
	/*2123*/ {IDS_F_50                                 ,"50.0 Hz"},
	/*2124*/ {IDS_F_63                                 ,"63.0 Hz"},
	/*2125*/ {IDS_F_80                                 ,"80.0 Hz"},
	/*2126*/ {IDS_F_100                                ,"100 Hz"},
	/*2127*/ {IDS_F_125                                ,"125 Hz"},
	/*2128*/ {IDS_F_160                                ,"160 Hz"},
	/*2129*/ {IDS_F_200                                ,"200 Hz"},
	/*2130*/ {IDS_F_250                                ,"250 Hz"},
	/*2131*/ {IDS_F_315                                ,"315 Hz"},
	/*2132*/ {IDS_F_400                                ,"400 Hz"},
	/*2133*/ {IDS_F_500                                ,"500 Hz"},
	/*2134*/ {IDS_F_630                                ,"630 Hz"},
	/*2135*/ {IDS_F_800                                ,"800 Hz"},
	/*2136*/ {IDS_F_1000                               ,"1.00 kHz"},
	/*2137*/ {IDS_F_1250                               ,"1.25 kHz"},
	/*2138*/ {IDS_F_1600                               ,"1.60 kHz"},
	/*2139*/ {IDS_F_2000                               ,"2.00 kHz"},
	/*2140*/ {IDS_F_2500                               ,"2.50 kHz"},
	/*2141*/ {IDS_F_3150                               ,"3.15 kHz"},
	/*2142*/ {IDS_F_4000                               ,"4.00 kHz"},
	/*2143*/ {IDS_F_5000                               ,"5.00 kHz"},
	/*2144*/ {IDS_F_6300                               ,"6.30 kHz"},
	/*2145*/ {IDS_F_8000                               ,"8.00 kHz"},
	/*2146*/ {IDS_F_10000                              ,"10.0 kHz"},
	/*2147*/ {IDS_F_12500                              ,"12.5 kHz"},
	/*2148*/ {IDS_F_16000                              ,"16.0 kHz"},
	/*2149*/ {IDS_F_20000                              ,"20.0 kHz"},
	/*2150*/ {IDS_LINK_TO_DISPLAY                      ,"Collega al display"},
	/*2151*/ {IDS_BT                                   ,"BT"},
	/*2152*/ {IDS_BK                                   ,"Bk"},
	/*2153*/ {IDS_CO                                   ,"Co"},
	/*2154*/ {IDS_CU                                   ,"Cu"},
	/*2155*/ {IDS_SD                                   ,"SD"},
	/*2156*/ {IDS_INCLUDE                              ,"Includi"},
	/*2157*/ {IDS_EXCLUDE                              ,"Escludi"},
	/*2158*/ {IDS_RUN_RA_L1                            ,"Avvia-L1"},
	/*2159*/ {IDS_RUN_RA_L2                            ,"Avvia-L2"},
	/*2160*/ {IDS_RUN_RA_B2                            ,"Avvia-B2"},
	/*2161*/ {IDS_RUN_RA_T2                            ,"Avvia-T2"},
	/*2162*/ {IDS_RUN_RA_TH                            ,"Durata T-History"},
	/*2163*/ {IDS_MASK_OPTION_MATCH                    ,"Cambio di opzione.\nFile non visibile."},
	/*2164*/ {IDS_NOPLAYBACK_RUNNING                   ,"Non possibile\nquando sta misurando."},
	/*2165*/ {IDS_NL                                   ,"NL"},
	/*2166*/ {IDS_RT60_STATUS                          ,"RT-60 Condizione"},
	/*2167*/ {IDS_RT60_TIMES                           ,"RT-60 Grafico nel Tempo"},
	/*2168*/ {IDS_RT60_DECAYS                          ,"RT-60 Grafico Decadimenti"},
	/*2169*/ {IDS_RT60_LEVELS                          ,"RT-60 Decadimenti"},
	/*2170*/ {IDS_QI_SUMMARY1                          ,"Sommario Qualità 1"},
	/*2171*/ {IDS_QI_SUMMARY2                          ,"Sommario Qualità 2"},
	/*2172*/ {IDS_QI_DETAIL                            ,"Dettaglio indici Qualità"},
	/*2173*/ {IDS_SURVEY                               ,"Controllo"},
	/*2174*/ {IDS_ENGINEERING                          ,"Ingegneristico"},
	/*2175*/ {IDS_PRECISION                            ,"Precisione"},
	/*2176*/ {IDS_POSITION                             ,"Posizione"},
	/*2177*/ {IDS_POSITIONS                            ,"Posizioni"},
	/*2178*/ {IDS_DECAY_PER_POS                        ,"Decadimento/Posizione"},
	/*2179*/ {IDS_DECAY                                ,"Decadimento"},
	/*2180*/ {IDS_DECAYS                               ,"Decadimenti"},
	/*2181*/ {IDS_EST_GRADE                            ,"Grado di Precisione"},
	/*2182*/ {IDS_FREG_RANGE                           ,"Gamma in Frequenza"},
	/*2183*/ {IDS_DASHES                               ,"- - -"},
	/*2184*/ {IDS_ACTUAL                               ,"Misurato:"},
	/*2185*/ {IDS_REQUIRED                             ,"Richiesto:"},
	/*2186*/ {IDS_CONFIRM_DELETEALL_SLM                ,"Cancella tutti i Files LPS?"},
	/*2187*/ {IDS_CONFIRM_DELETEALL_RA                 ,"Cancella tutti i Files RA?"},
	/*2188*/ {IDS_CONFIRM_DELETEALL_FFT                ,"Cancella tutti i Files FFT?"},
	/*2189*/ {IDS_INSTALLED                            ,"Installato"},
	/*2190*/ {IDS_TEMPERATURE                          ,"Temperatura"},
	/*2191*/ {IDS_HUMIDITY                             ,"Umidità"},
	/*2192*/ {IDS_L1_RANGE                             ,"Misure L1"},
	/*2193*/ {IDS_L2_RANGE                             ,"Misure L2"},
	/*2194*/ {IDS_B2_RANGE                             ,"Misure B2"},
	/*2195*/ {IDS_B2                                   ,"B2"},
	/*2196*/ {IDS_L1L2                                 ,"L1 L2"},
	/*2197*/ {IDS_SAMPLEPERIOD                         ,"Campionamento"},
	/*2198*/ {IDS_MAX_POSITION                         ,"Ultima Posizione\n Raggiunta"},
	/*2199*/ {IDS_SETTING_CONFLICT                     ,"Conflitto Impostazioni"},
	/*2200*/ {IDS_NOT_APPLICABLE                       ,"Non Applicabile"},
	/*2201*/ {IDS_FFT                                  ,"FFT"},
	/*2202*/ {IDS_FFT_LIVE                             ,"FFT Istant."},
	/*2203*/ {IDS_CREATE_AVG                           ,"Esegui Media"},
	/*2204*/ {IDS_ADD_TO_AVG                           ,"Aggiungi a Media"},
	/*2205*/ {IDS_ERROR_CANNOT_AVERAGE                 ,"Conflitto Impost.|nImpossibile Mediare."},
	/*2206*/ {IDS_CREATED_AVERAGE                      ,"File Mediato"},
	/*2207*/ {IDS_FILE_AVERAGING                       ,"Mediando"},
	/*2208*/ {IDS_WINDOW                               ,"Finestra"},
	/*2209*/ {IDS_HANNING                              ,"Hanning"},
	/*2210*/ {IDS_FLATTOP                              ,"Flat Top"},
	/*2211*/ {IDS_RECTANGULAR                          ,"Rettangolare"},
	/*2212*/ {IDS_FREQUENCY_SPAN                       ,"Banda in Freq."},
	/*2213*/ {IDS_LINES                                ,"Linee"},
	/*2214*/ {IDS_6400                                 ,"6400"},
	/*2215*/ {IDS_3200                                 ,"3200"},
	/*2216*/ {IDS_1600                                 ,"1600"},
	/*2217*/ {IDS_800                                  ,"800"},
	/*2218*/ {IDS_400                                  ,"400"},
	/*2219*/ {IDS_MANUAL                               ,"Manuale"},
	/*2220*/ {IDS_COUNT_STOP                           ,"Fine Conteggio"},
	/*2221*/ {IDS_CURSOR                               ,"Cursore"},
	/*2222*/ {IDS_CURSOR_TYPE                          ,"Tipo cursore"},
	/*2223*/ {IDS_MAX_TRACKING                         ,"Traccia-Massimi"},
	/*2224*/ {IDS_HARMONICS                            ,"Armoniche"},
	/*2225*/ {IDS_TO                                   ,"Fino a"},
	/*2226*/ {IDS_BAD_TIMES                            ,"Durata serale invalida. \n aggiusto da solo?"},
	/*2227*/ {IDS_FLASH_ERROR                          ,"Rilevati errori su Flash. \n Fare copia dati e \n riformattare il systema"},
	/*2228*/ {IDS_COMMS_WATCHDOG                       ,"Watchdog sulla communicaz."},
	/*2229*/ {IDS_COMMS_WATCHDOG_COUNT                 ,"Cont WD comm."},
	/*2230*/ {IDS_TEMPERATURE_AVG                      ,"Temp. media"},
	/*2231*/ {IDS_TEMPERATURE_MAX                      ,"Temp. Max"},
	/*2232*/ {IDS_TEMPERATURE_MIN                      ,"Temp. Min"},
	/*2233*/ {IDS_HUMIDITY_AVG                         ,"Umidità media"},
	/*2234*/ {IDS_HUMIDITY_MAX                         ,"Umidità Max"},
	/*2235*/ {IDS_HUMIDITY_MIN                         ,"Umidità Min"},
	/*2236*/ {IDS_OFF_CLOSE                            ,"Off, Spento,"},
	/*2237*/ {IDS_ERROR_LOG                            ,"Errore Log"},
	/*2238*/ {IDS_TIMER_EXPIRED                        ,"Tempo scaduto"},
	/*2239*/ {IDS_TONALITYX                            ,"Tonalità"},
	/*2240*/ {IDS_1996_TONALITY                        ,"ISO 1996-2 Tonalità"},
	/*2241*/ {IDS_TONE                                 ,"Tono"},
	/*2242*/ {IDS_TONES                                ,"Toni"},
	/*2243*/ {IDS_NO_TONES                             ,"Nessun Tono"},
	/*2244*/ {IDS_LPT                                  ,"Lpt"},
	/*2245*/ {IDS_LPN                                  ,"Lpn"},
	/*2246*/ {IDS_LTA                                  ,"Lta"},
	/*2247*/ {IDS_KT                                   ,"Kt"},
	/*2248*/ {IDS_BCRIT                                ,"Bcrit"},
	/*2249*/ {IDS_SETTINGS_DIFFER                      ,"Impostaz. diverse dallo \n standard tonalità. \n impost. automatic.? "},
	/*2250*/ {IDS_RUNNING                              ,"in misura"},
	/*2251*/ {IDS_TONE_SEEK_DELTA                      ," prominenza tono"},
	/*2252*/ {IDS_TONE_SEEK_DELTA_1                    ,"1 dB"},
	/*2253*/ {IDS_TONE_SEEK_DELTA_2                    ,"2 dB"},
	/*2254*/ {IDS_TONE_SEEK_DELTA_3                    ,"3 dB"},
	/*2255*/ {IDS_TONE_SEEK_DELTA_4                    ,"4 dB"},
	/*2256*/ {IDS_LR_SPAN_PERCENT                      ,"Gamma regressione"},
	/*2257*/ {IDS_LR_SPAN_PERCENT_50                   ," 50 %"},
	/*2258*/ {IDS_LR_SPAN_PERCENT_75                   ," 75 %"},
	/*2259*/ {IDS_LR_SPAN_PERCENT_100                  ,"100 %"},
	/*2260*/ {IDS_LR_SPAN_PERCENT_150                  ,"150 %"},
	/*2261*/ {IDS_LR_SPAN_PERCENT_200                  ,"200 %"},
	/*2262*/ {IDS_HEATER                               ,"Riscaldatore"},
	/*2263*/ {IDS_AC_OUT_DISABLED                      ,"Jack funz. AC/DC \n è stato scollegato"},
	/*2264*/ {IDS_WATCHDOG                             ,"Watchdog"},
	/*2265*/ {IDS_831_INT_ET                           ,"831 INT-ET"},
	/*2266*/ {IDS_COUNTER_WRAP                         ,"Limite di Tempo"},
	/*2267*/ {IDS_NF30_LN                              ,"NF30 Ln"},
	/*2268*/ {IDS_FAST_WEATHER                         ,"Meteo veloce"},
	/*2269*/ {IDS_REMAINING_LEQ                        ,"Leq rimanente"},
	/*2270*/ {IDS_ELAPSED                              ,"Trascorso"},
	/*2271*/ {IDS_CURRENT                              ,"Attuale"},
	/*2272*/ {IDS_REMAINING                            ,"Rimanente"},
	/*2273*/ {IDS_TARGET                               ,"Da raggiungere"},
	/*2274*/ {IDS_VAISALA_WEATHER                      ,"Meteo Vaisala"},
	/*2275*/ {IDS_OTHER                                ,"Altro"},
	/*2276*/ {IDS_IP_ADDR                              ,"IP"},
	/*2277*/ {IDS_MAC_ADDR                             ,"MAC"},
	/*2278*/ {IDS_TIME_WEIGHTED_AVE                    ,"Time-Weighted Averages"},
	/*2279*/ {IDS_MTIME_RES                            ,"Millisecond Time Resolution"},
	/*2280*/ {IDS_SETTINGS_MODIFIED                    ,"Settings have been modified."},
	/*2281*/ {IDS_SETTOACTIVE                          ,"Impostare su Attivo"},
	/*2282*/ {IDS_HLD_YOU_MUST_ENABLE                  ,"È necessario attivare"},
	/*2283*/ {IDS_HLD_SETTINGSCONFLICT_INTEGRATION     ,"IT Settings conflict: Integration Method must be Linear also Measurement, Save Snapshot and Event History must be disabled to enable this setting. Fix automatically?"},
	/*2284*/ {IDS_HLD_SETTINGSCONFLICT_SAVE_SNAP       ,"IT Settings conflict: Save Snapshot Event must be disabled to enable this setting. Fix automatically?"},
	/*2285*/ {IDS_HLD_FST_ONENTHIRD_OPTIONS            ,"È necessario attivare the Fast Time History, 1/1 Octave and 1/3 Octave Options."},
	/*2286*/ {IDS_HLD_SAMPLERATE_TOOHIGH               ,"IT Settings conflict: Sound Recording sample rate set too high; max is 8 ksps with Time History. Fix automatically?"},
	/*2287*/ {IDS_HLD_SOUNDRECORDING_OPTION            ,"È necessario attivare the Sound Recording Option."},
	/*2288*/ {IDS_HLD_USBHOSTPORT_GPS                  ,"È necessario attivare the USB Host Port and the GPS Mode must be On."},
	/*2289*/ {IDS_HLD_ENABLE_USBHOSTPORT               ,"È necessario attivare the USB Host Port."},
	/*2290*/ {IDS_HLD_ENABLE_MEASHISTORY               ,"È necessario attivare Measurement History."},
	/*2291*/ {IDS_HLD_RUNTIME_59SECS                   ,"IT Run Time must be greater than 59 seconds."},
	/*2292*/ {IDS_HLD_EN_MEASHIST_NOTMANUAL            ,"È necessario attivare Measurement History and the Run Mode must not be 'Manual Stop'"},
	/*2293*/ {IDS_HLD_EN_MEASHIST_OPTION               ,"È necessario attivare the Measurement History Option."},
	/*2294*/ {IDS_HLD_EN_EVENTHIST                     ,"È necessario attivare Event History."},
	/*2295*/ {IDS_HLD_EN_MEASHIST_N_OPTION             ,"È necessario abilitare Storia misurazione e l'opzione Cronologia di misura."},
	/*2296*/ {IDS_HLD_DIFFER_TONALITYSTD_FIX           ,"Impostazioni differiscono dallo standard tonalità. Fissare automaticamente?"},
	/*2297*/ {IDS_HLD_RS232DISABLED                    ,"RS232 sarà disabilitata. Continuare?"},
	/*2298*/ {IDS_HLD_EN_TIMEDSTOP                     ,"Deve consentire temporizzato arresto"},
	/*2299*/ {IDS_HLD_REQUIREDPREAMP                   ,"È necessario che il preamplificatore richiesta."},
	/*2300*/ {IDS_HLD_RT60METHOD_INTERRUPTED           ,"RT-60 metodo deve essere impostato interrotto."},
	/*2301*/ {IDS_HLD_STOREONCEDAILY                   ,"Dovete scegliere di memorizzare almeno una volta al giorno."},
	/*2302*/ {IDS_HLD_MUSTBE_INTET                     ,"Il contatore deve essere seduto in un INT/INT-ET."},
	/*2303*/ {GID_MAY_WAIT_FOR_OTHER_SPREADSHEETS      ,"Può aspettare se altri fogli di calcolo sono 'costruzione'."},
	/*2304*/ {IDS_LNF                                  ,"L<sub>NF</sub>"},
	/*2305*/ {IDS_LCEQN                                ,"L<sub>Ceq</sub>"},
	/*2306*/ {IDS_LAEQN                                ,"L<sub>Aeq</sub>"},
	/*2307*/ {IDS_LZEQN                                ,"L<sub>Zeq</sub>"},
	/*2308*/ {IDS_RESET                                ,"Chiaro"},
	/*2309*/ {IDS_RAM_SIZE                             ,"Dimensioni RAM"},
	/*2310*/ {IDS_NETWORK                              ,"Rete"},
	/*2311*/ {IDS_FF2RI_2116                           ,"FF:RI 2116"},
	/*2312*/ {IDS_FF2FF_2116                           ,"FF:FF 2116"},
	/*2313*/ {IDS_FF290_2116                           ,"FF:90 2116"},
	/*2314*/ {IDS_HLD_DYNAMIC_RANGE                    ,"Compressione dinamica"},
	/*2315*/ {IDS_HLD_SAVEFILE                         ,"IDS_HLD_SAVEFILE, "Save to File"},
	/*2316*/ {IDS_HLD_BUFFERLEN                        ,"IDS_HLD_BUFFERLEN, "lunghezza del buffer"},
	/*2317*/ {IDS_HLD_ARMS                             ,"un <sub> RMS </ sub>"},
	/*2318*/ {IDS_HLD_APEAK                            ,"un <sub> PEAK </ sub>"},
	/*2319*/ {IDS_HLD_AMIN                             ,"un <sub> MIN </ sub>"},
	/*2320*/ {IDS_HLD_AMAX                             ,"MTV"},
	/*2321*/ {IDS_HLD_RETURNOVERALL                    ,"Torna a scheda generale"},
	/*2322*/ {IDS_HLD_UPLOADFIRM                       ,"Upload Firmware"},
	/*2323*/ {IDS_HLD_MODEL                            ,"Modello"},
	/*2324*/ {IDS_HLD_CONN_TYPE                        ,"Tipo di connessione"},
	/*2325*/ {IDS_HLD_SENSORSTAT                       ,"Stato sensore"},
	/*2326*/ {IDS_HLD_TEDS                             ,"TEDS"},
	/*2327*/ {IDS_HLD_SYSSTAT                          ,"Stato del sistema"},
	/*2328*/ {IDS_HLD_WIFI                             ,"Wifi"},
	/*2329*/ {IDS_HLD_CHARGING                         ,"carica"},
	/*2330*/ {IDS_HLD_MISSING                          ,"Mancante"},
	/*2331*/ {IDS_HLD_USING                            ,"utilizzando"},
	/*2332*/ {IDS_HLD_CHARGED                          ,"Charged"},
	/*2333*/ {IDS_HLD_BATLOW                           ,"Basso"},
	/*2334*/ {IDS_HLD_SAVE_MEASPROPS                   ,"Salvare le proprietà di misura"},
	/*2335*/ {IDS_HLD_SAVE_SYSPROPS                    ,"Salvare Proprietà del sistema"},
	/*2336*/ {IDS_HLD_FIRMWARE                         ,"firmware"},
	/*2337*/ {IDS_HLD_FILETYPE                         ,"Tipo di file"},
	/*2338*/ {IDS_HLD_INTERNAL_MEM                     ,"Uso della memoria interna"},
	/*2339*/ {IDS_HLD_TIME_REM                         ,"Tempo rimanente (H: M)"},
	/*2340*/ {IDS_HLD_SENS_ERROR                       ,"Non collegato o errore"},
	/*2341*/ {IDS_HLD_SETWIFI                          ,"Impostazione WiFi"},
	/*2342*/ {IDS_HLD_SENSOR                           ,"sensor"},
	/*2343*/ {IDS_HLD_ADD                              ,"Aggiungere"},
	/*2344*/ {IDS_HLD_SETAP                            ,"Set Access Point"},
	/*2345*/ {IDS_HLD_UP                               ,"Su"},
	/*2346*/ {IDS_HLD_DOWN                             ,"Fuori uso"},
	/*2347*/ {IDS_HLD_SETNET                           ,"Connettersi al WiFi"},
	/*2348*/ {IDS_HLD_SETNET_ERROR                     ,"È necessario disporre di almeno una rete Wi-Fi configurata."},
	/*2349*/ {IDS_HLD_WIFI_NET                         ,"rete di WiFi"},
	/*2350*/ {IDS_HLD_MY_IP                            ,"My IP"},
	/*2351*/ {IDS_HLD_SAVED                            ,"Risparmiato"},
	/*2352*/ {IDS_HLD_NETWORKS                         ,"Rete"},
	/*2353*/ {IDS_HLD_PRIORITY                         ,"Preferenza"},
	/*2354*/ {IDS_HLD_SIGNAL                           ,"Segnale"},
	/*2355*/ {IDS_HLD_SCANNING                         ,"Scansione"},
	/*2356*/ {IDS_HLD_NET_OPEN                         ,"Aprire"},
	/*2357*/ {IDS_HLD_NETSECURE                        ,"assicurato"},
	/*2358*/ {IDS_HLD_CONFIRM_REM_NET                  ,"Sei sicuro di voler dimenticare questa rete WiFi?"},
	/*2359*/ {IDS_HLD_CONFIRM_DELETE                   ,"Conferma dimenticata"},
	/*2360*/ {IDS_HLD_CONFIRM_UPGRADE                  ,"Conferma aggiornamento"},
	/*2361*/ {IDS_HLD_CONFIRM_DELFILE                  ,"Stai per cancellare questo file"},
	/*2362*/ {IDS_HLD_CONF_CON_NET                     ,"Connessione a rete di WiFi"},
	/*2363*/ {IDS_HLD_CONF_LOSECON                     ,"Se si procede, si rischia di perdere il collegamento con lo strumento se non è collegato via USB. Si prega di connettersi alla stessa rete del metro."},
	/*2364*/ {IDS_HLD_CONF_SET_AP                      ,"Imposta come Access Point"},
	/*2365*/ {IDS_HLD_FILEMAN                          ,"File Manager"},
	/*2366*/ {IDS_HLD_VIBRATION                        ,"Vibrazione"},
	/*2367*/ {IDS_HLD_HANDARM                          ,"Mano / braccio"},
	/*2368*/ {IDS_HLD_WHOLEBODY                        ,"Corpo intero"},
	/*2369*/ {IDS_HLD_DATAFILE                         ,"Documenti"},
	/*2370*/ {IDS_HLD_VIEWFILE                         ,"Visualizza file di dati"},
	/*2371*/ {IDS_HLD_DELSELFILE                       ,"Cancella il file selezionato"},
	/*2372*/ {IDS_HLD_REFLIST                          ,"Elenco dei file di aggiornamento"},
	/*2373*/ {IDS_HLD_UPNEWFIRM                        ,"Carica nuovo firmware"},
	/*2374*/ {IDS_HLD_CONFREQ                          ,"conferma richiesta"},
	/*2375*/ {IDS_HLD_ANNOMEAS                         ,"Annota misura"},
	/*2376*/ {IDS_HLD_ANNOTIME                         ,"annotazione tempo"},
	/*2377*/ {IDS_HLD_ANNOTATE                         ,"Annotare"},
	/*2378*/ {IDS_HLD_ANNONOTE                         ,"Nota"},
	/*2379*/ {IDS_HLD_SUMMATION                        ,"Σ Somma"},
	/*2380*/ {IDS_HLD_AXIS                             ,"Asse"},
	/*2381*/ {IDS_HLD_TOTAL                            ,"Totale"},
	/*2382*/ {IDS_HLD_MODE                             ,"modo"},
	/*2383*/ {IDS_HLD_OVLD                             ,"overload"},
	/*2384*/ {IDS_HLD_CONF                             ,"Confermare"},
	/*2385*/ {IDS_HLD_WILLREBOOT                       ,"Lo strumento verrà riavviato."},
	/*2386*/ {IDS_HLD_WILLSTOPREBOOT                   ,"Lo strumento sarà fermato e riavviato."},
	/*2387*/ {IDS_HLD_PROCFILE                         ,"File Processing"},
	/*2388*/ {IDS_HLD_REBOOTING                        ,"Riavvio"},
	/*2389*/ {IDS_HLD_CLOSING                          ,"Chiusura"},
	/*2390*/ {IDS_HLD_SETUP                            ,"Impostare"},
	/*2391*/ {IDS_HLD_SCHEDULE                         ,"tabella di marcia"},
	/*2392*/ {IDS_HLD_MISC                             ,"Varie"},
	/*2393*/ {IDS_HLD_TOOLS                            ,"Strumenti"},
	/*2394*/ {IDS_HLD_TOOLS2                           ,"Strumenti 2"},
	/*2395*/ {IDS_HLD_OPERATING_MODE                   ,"Modalità operativa"},
	/*2396*/ {IDS_HLD_OM_VIB                           ,"Vibrazione"},
	/*2397*/ {IDS_HLD_OM_HA                            ,"Mano / braccio"},
	/*2398*/ {IDS_HLD_OM_WB                            ,"Corpo intero"},
	/*2399*/ {IDS_HLD_STORE_INTER_TIME                 ,"Conservare Intervallo"},
	/*2400*/ {IDS_HLD_SEC                              ,"secondo"},
	/*2401*/ {IDS_HLD_MIN                              ,"min"},
	/*2402*/ {IDS_HLD_HR                               ,"hr"},
	/*2403*/ {IDS_HLD_W_WS                             ,"ws gravità"},
	/*2404*/ {IDS_HLD_W_FA                             ,"Fa 0,4-100 Hz"},
	/*2405*/ {IDS_HLD_W_FB                             ,"Fb 0,4-1.250 Hz"},
	/*2406*/ {IDS_HLD_W_FC                             ,"Fc 6,3-1.250 Hz"},
	/*2407*/ {IDS_HLD_W_WH                             ,"Wh"},
	/*2408*/ {IDS_HLD_W_WM                             ,"Wm Edifici"},
	/*2409*/ {IDS_HLD_W_WB                             ,"Wb Ferrovie-Z"},
	/*2410*/ {IDS_HLD_W_WC                             ,"Wc schienale-X"},
	/*2411*/ {IDS_HLD_W_WD                             ,"Wd orizzontale-XY"},
	/*2412*/ {IDS_HLD_W_WE                             ,"noi di rotazione"},
	/*2413*/ {IDS_HLD_W_WG                             ,"Wg BS 8461-Z"},
	/*2414*/ {IDS_HLD_W_WJ                             ,"Wj Head-X"},
	/*2415*/ {IDS_HLD_W_WK                             ,"Wk verticale-Z"},
	/*2416*/ {IDS_HLD_W_WF                             ,"Wf la bassa frequenza"},
	/*2417*/ {IDS_HLD_DELAY_START                      ,"Inizio ritardato"},
	/*2418*/ {IDS_HLD_RUN_DUR                          ,"eseguire Durata"},
	/*2419*/ {IDS_HLD_STOR_RAW                         ,"Conservare Raw Data"},
	/*2420*/ {IDS_HLD_STOR_PEAK                        ,"Conservare max dati"},
	/*2421*/ {IDS_HLD_AUTOSTOP                         ,"Auto Stop"},
	/*2422*/ {IDS_HLD_OBA_TH                           ,"OBA Time History"},
	/*2423*/ {IDS_HLD_DB_REF                           ,"dB di riferimento"},
	/*2424*/ {IDS_HLD_EXP_LIMIT                        ,"Limite di esposizione"},
	/*2425*/ {IDS_HLD_EXP_ACTION                       ,"Azione esposizione"},
	/*2426*/ {IDS_HLD_DIS_UNITS                        ,"Unità di visualizzazione"},
	/*2427*/ {IDS_HLD_INTEGRATION                      ,"Integrazione"},
	/*2428*/ {IDS_HLD_K_FACTOR                         ,"k-Factor"},
	/*2429*/ {IDS_HLD_BASE_NAME                        ,"Nome file di dati"},
	/*2430*/ {IDS_HLD_SF_NAME                          ,"Impostare Nome file"},
	/*2431*/ {IDS_HLD_AUTO_STORE                       ,"Auto Store"},
	/*2432*/ {IDS_HLD_STORE_TIME                       ,"Conservare Tempo"},
	/*2433*/ {IDS_HLD_SINGLE                           ,"Single"},
	/*2434*/ {IDS_HLD_DOUBLE                           ,"Raddoppiare"},
	/*2435*/ {IDS_HLD_ACDC_OUTPUT                      ,"Uscita AC / DC"},
	/*2436*/ {IDS_HLD_AC_W                             ,"AC: Weighted"},
	/*2437*/ {IDS_HLD_AC_B                             ,"AC: BandLimit"},
	/*2438*/ {IDS_HLD_DC_RMS                           ,"DC: RMS"},
	/*2439*/ {IDS_HLD_DC_MIN                           ,"DC: Min"},
	/*2440*/ {IDS_HLD_DC_MAX                           ,"DC: Max"},
	/*2441*/ {IDS_HLD_DC_PEAK                          ,"DC: Picco"},
	/*2442*/ {IDS_HLD_DC_RMS_SUM                       ,"DC: RMS Sum"},
	/*2443*/ {IDS_HLD_DC_MIN_SUM                       ,"DC: Min Sum"},
	/*2444*/ {IDS_HLD_DC_MAX_SUM                       ,"DC: Max Sum"},
	/*2445*/ {IDS_HLD_DC_PEAK_SUM                      ,"DC: Picco Sum"},
	/*2446*/ {IDS_HLD_RPT_HEADERS                      ,"Rapporto intestazioni"},
	/*2447*/ {IDS_HLD_PRNT_HSTRY                       ,"Stampa Storia"},
	/*2448*/ {IDS_HLD_SENSOR_LIST                      ,"Lista sensore"},
	/*2449*/ {IDS_HLD_ACCEL_TYPE                       ,"accelerometro"},
	/*2450*/ {IDS_HLD_DIRECT                           ,"Diretto"},
	/*2451*/ {IDS_HLD_CHARGE                           ,"caricare"},
	/*2452*/ {IDS_HLD_SENSORS                          ,"sensori"},
	/*2453*/ {IDS_HLD_SERIAL_NUM                       ,"Seriale #"},
	/*2454*/ {IDS_HLD_X_SENS                           ,"x Sens."},
	/*2455*/ {IDS_HLD_Y_SENS                           ,"y Sens."},
	/*2456*/ {IDS_HLD_Z_SENS                           ,"z Sens."},
	/*2457*/ {IDS_HLD_STDATE                           ,"Data d'inizio"},
	/*2458*/ {IDS_HLD_ENDATE                           ,"Data di fine"},
	/*2459*/ {IDS_HLD_SENSOR_NA                        ,"Errore o il sensore non supporta TEDS."},
	/*2460*/ {IDS_HLD_CONNECTED                        ,"Collegato"},
	/*2461*/ {IDS_HLD_NOTCONN                          ,"Non collegata"},
	/*2462*/ {IDS_HLD_ALERT                            ,"Allarme"},
	/*2463*/ {IDS_HLD_CN_FAIL                          ,"Impossibile connettersi alla rete. Meter è ancora un punto di accesso."},
	/*2464*/ {IDS_HLD_CN_SUCC                          ,"Meter è ora collegata con IP"},
	/*2465*/ {IDS_HLD_CN_RESET                         ,"Meter sta resettando WiFi"},
	/*2466*/ {IDS_HLD_AP_SUCC                          ,"Meter è ora impostato per essere un punto di accesso."},
	/*2467*/ {IDS_HLD_AP_ERR                           ,"Errore di impostazione del punto di accesso."},
	/*2468*/ {IDS_HLD_STATUS                           ,"Stato"},
	/*2469*/ {IDS_HLD_WF_ENTNETPASS                    ,"Password di rete"},
	/*2470*/ {IDS_HLD_WF_ADDNET                        ,"Aggiungi rete"},
	/*2471*/ {IDS_FIRMUPG_CHOS                         ,"Scegli firmware"},
	/*2472*/ {IDS_FIRMUPG_SAME                         ,"Lo strumento è stato aggiornato con successo per la stessa configurazione."},
	/*2473*/ {IDS_FIRMUPG_SUCCESS                      ,"Con successo aggiornato il contatore."},
	/*2474*/ {IDS_FIRMUPG_FAIL                         ,"Lo strumento non è riuscito ad aggiornare. Il file di aggiornamento può essere stato valido o la connessione potrebbe essere stato perso durante la trasmissione. Verificare di disporre di un file di aggiornamento valido e riprovare."},
	/*2475*/ {IDS_HLD_FAIL                             ,"Impossibile"},
	/*2476*/ {IDS_HLD_FINISHED                         ,"Finito"},
	/*2477*/ {IDS_HLD_REFERENCE                        ,"Riferimento"},
	/*2478*/ {IDS_HLD_SET                              ,"Impostato"},
	/*2479*/ {IDS_HLD_UPG_AP                           ,"È necessario riconnettersi al WiFi del metro (punto di accesso). La chiusura di questa finestra."},
	/*2480*/ {IDS_HLD_APOINT                           ,"Punto d'accesso"},
	/*2481*/ {IDS_HLD_AP_LOSECON                       ,"Se si procede, si verrà disconnessi temporaneamente dal metro e potrebbe essere necessario riconnettersi alla rete."},
	/*2482*/ {IDS_HLD_CNCTING                          ,"Collegamento"},
	/*2483*/ {IDS_HLD_LOSTDLG                          ,"Sembra che la connessione si è interrotta. Seleziona 'Home' per tornare alla lista metro."},
	/*2484*/ {IDS_HLD_LOSTCON                          ,"Collegamento perso"},
	/*2485*/ {IDS_HLD_MINPASS                          ,"O nessuna password o almeno è necessario inserire una password di 8 caratteri per abbinare tua rete WiFi."},
	/*2486*/ {IDS_HLD_MISNAME                          ,"È necessario immettere un nome di rete WiFi valido (SSID)."},
	/*2487*/ {IDS_STOP_METER                           ,"Fermare il Meter?"},
	/*2488*/ {IDS_HLD_STOP_METER                       ,"Fermare il Meter?"},
	/*2489*/ {IDS_HLD_DO_CAL                           ,"fare Calibrazione"},
	/*2490*/ {IDS_HLD_QUESTION                         ,"Domanda"},
	/*2491*/ {IDS_HLD_PREAMP                           ,"preamplificatore"},
	/*2492*/ {IDS_HLD_DBPK                             ,"dB<sub>pk</sub>"},
	/*2493*/ {IDS_HLD_MIC_SAVED                        ,"La sensibilità dei dati è stato scritto per la metro."},
};
/*****************************************************************************/
// end of module
