/*************************************************************************//*
   @file  Strings_English.h
   @brief Translated text strings.

   NOTE: This is the source for AUTO-GENERATED language files. 

   (c) 2004-2014 PCB Piezotronics, Inc. - ALL RIGHTS RESERVED
****************************************************************************/

#ifndef STR_ENGLISH_HPP
#define STR_ENGLISH_HPP

String_t StrEnglish[] =
{
 {IDS_INSTRUMENT_NAME                      ,"Instrument Name"},
 {IDS_CZECH                                ,"Cestina"},
 {IDS_ENGLISH                              ,"English"},
 {IDS_FRENCH                               ,"Français"},
 {IDS_GERMAN                               ,"Deutsch"},
 {IDS_HUNGARIAN                            ,"Magyar"},
 {IDS_ITALIAN                              ,"Italiano"},
 {IDS_NORWEGIAN                            ,"Norsk"},
 {IDS_POLISH                               ,"Polski"},
 {IDS_PORTUGUESE_BR                        ,"Português(BR)"},
 {IDS_PORTUGUESE_PT                        ,"Português(PT)"},
 {IDS_ROMANIAN                             ,"Limba Româna"},
 {IDS_RUSSIAN                              ,"‰¸¶¶ª§¨"},
 {IDS_SPANISH                              ,"Español"},
 {IDS_SWEDISH                              ,"Svenska"},
 {IDS_TURKISH                              ,"Türkçe"},
 {IDS_LASEQ                                ,"L<sub>$#eq</sub>"},
 {IDS_LAS                                  ,"L<sub>$#</sub>"},
 {IDS_LNF                                  ,"L<sub>NF</sub>"},
 {IDS_LAPEAK                               ,"L<sub>^peak</sub>"},
 {IDS_LAPEAKMAX                            ,"L<sub>^peak(max)</sub>"},
 {IDS_LASMAX                               ,"L<sub>$#max</sub>"},
 {IDS_LASMIN                               ,"L<sub>$#min</sub>"},
 {IDS_LASE                                 ,"L<sub>$#E</sub>"},
 {IDS_EAS                                  ,"E<sub>$#</sub>"},
 {IDS_EAS8                                 ,"E<sub>$#8</sub>"},
 {IDS_EAS40                                ,"E<sub>$#40</sub>"},
 {IDS_LASG                                 ,"L<sub>$#</sub> >"},
 {IDS_LAPEAKG                              ,"L<sub>^peak</sub> >"},
 {IDS_LEQ1S                                ,"L<sub>$#eq(1s)</sub>"},
 {IDS_LCEQ                                 ,"L<sub>C#eq</sub>"},
 {IDS_LAEQ                                 ,"L<sub>A#eq</sub>"},
 {IDS_LCEQN                                ,"L<sub>Ceq</sub>"},
 {IDS_LAEQN                                ,"L<sub>Aeq</sub>"},
 {IDS_LZEQN                                ,"L<sub>Zeq</sub>"},
 {IDS_LWMAX                                ,"L<sub>$max</sub>"},
 {IDS_LWMIN                                ,"L<sub>$min</sub>"},
 {IDS_LWAVG                                ,"L<sub>$avg</sub>"},
 {IDS_LWPEAK_MAX                           ,"L<sub>$max(max)</sub>"},
 {IDS_LWPEAK_AVG                           ,"L<sub>$max(avg)</sub>"},
 {IDS_LW                                   ,"L<sub>$</sub>"},
 {IDS_LWDBK                                ,"L<sub>$#bk</sub>"},
 {IDS_CMINUSA                              ,"L<sub>C#eq</sub> - L<sub>A#eq</sub>"},
 {IDS_FREQWT                               ,"Frequency Weighting"},
 {IDS_DETECTOR                             ,"Detector"},
 {IDS_PEAKWT                               ,"Peak Weighting"},
 {IDS_INTEGRATIONMETHOD                    ,"Integration Method"},
 {IDS_A                                    ,"A"},
 {IDS_C                                    ,"C"},
 {IDS_Z                                    ,"Z"},
 {IDS_SLOW                                 ,"Slow"},
 {IDS_FAST                                 ,"Fast"},
 {IDS_IMPL                                 ,"Impl"},
 {IDS_SLOWS                                ,"S"},
 {IDS_FASTF                                ,"F"},
 {IDS_IMPLI                                ,"I"},
 {IDS_LINEAR                               ,"Linear"},
 {IDS_EXPONENTIAL                          ,"Exponential"},
 {IDS_RUNTIME                              ,"Run Time"},
 {IDS_STARTED                              ,"Started"},
 {IDS_TWA24                                ,"TWA"},
 {IDS_PROJTWA                              ,"ProjTWA"},
 {IDS_LEPD                                 ,"Lep,d"},
 {IDS_DOSE                                 ,"DOSE"},
 {IDS_PROJDOSE                             ,"ProjDose"},
 {IDS_WEIGHTING                            ,"Weighting"},
 {IDS_EXCHANGERATE                         ,"Exchange Rate"},
 {IDS_SOUNDEXPOSURELEVEL                   ,"Sound Exposure Level"},
 {IDS_SOUNDEXPOSURE                        ,"Sound Exposure"},
 {IDS_EXCEEDANCES                          ,"Exceedances"},
 {IDS_COUNT                                ,"Count"},
 {IDS_DURATION                             ,"Duration"},
 {IDS_SEA1                                 ,"SEA"},
 {IDS_FREQWEIGHTINGZ                       ,"Frequency Weighting ^"},
 {IDS_STARTTIME                            ,"Start Time"},
 {IDS_ENDTIME                              ,"End Time"},
 {IDS_LEQ                                  ,"L<sub>eq</sub>"},
 {IDS_LMAX                                 ,"L<sub>max</sub>"},
 {IDS_LMIN                                 ,"L<sub>min</sub>"},
 {IDS_VIEWOBA                              ,"View OBA"},
 {IDS_VIEWSLM                              ,"View SLM"},
 {IDS_NORMALIZE                            ,"Normalize"},
 {IDS_LOCATE                               ,"Locate >"},
 {IDS_PLAY                                 ,"Play"},
 {IDS_ENTER                                ,"Enter"},
 {IDS_CLOSE                                ,"Close"},
 {IDS_CLOSE_CENTERED                       ," ,Close, "},
 {IDS_LNPERCENTILES                        ,"Ln Percentiles"},
 {IDS_DATE                                 ,"Date"},
 {IDS_TIME                                 ,"Time"},
 {IDS_RUNTIMER                             ,"Run Timer"},
 {IDS_BATTERY                              ,"Battery"},
 {IDS_USBPOWERED                           ,"USB Powered"},
 {IDS_MEMORY                               ,"Memory"},
 {IDS_DATAFILES                            ,"Data Files"},
 {IDS_FREE                                 ,"Free"},
 {IDS_OF                                   ,"of"},
 {IDS_HR                                   ,"h"},
 {IDS_MEASUREMENT_DESC                     ,"Measurement Description"},
 {IDS_DEFAULTFILENAME                      ,"Default Data File"},
 {IDS_SPLTRIGGER1                          ,"SPL Trigger Level 1"},
 {IDS_SPLTRIGGER2                          ,"SPL Trigger Level 2"},
 {IDS_PEAKTRIGGER1                         ,"Peak 1"},
 {IDS_DB                                   ,"dB"},
 {IDS_PERCENT                              ,"%"},
 {IDS_1                                    ,"1"},
 {IDS_2                                    ,"2"},
 {IDS_3                                    ,"3"},
 {IDS_4                                    ,"4"},
 {IDS_5                                    ,"5"},
 {IDS_6                                    ,"6"},
 {IDS_OBARANGE                             ,"OBA Range"},
 {IDS_NORMAL                               ,"Normal"},
 {IDS_LOW                                  ,"Low"},
 {IDS_MANUAL_STOP                          ,"Manual Stop"},
 {IDS_RUNTILLSTABLE                        ,"Stop When Stable"},
 {IDS_DELTA                                ,"Delta"},
 {IDS_HMS                                  ,"hh:mm:ss"},
 {IDS_TIMED_STOP                           ,"Timed Stop"},
 {IDS_NAME                                 ,"Name"},
 {IDS_ENABLED                              ,"Enabled"},
 {IDS_THRESHOLD                            ,"Threshold"},
 {IDS_CRITERION                            ,"Criterion"},
 {IDS_AUTOCALCULATE                        ,"Auto-Calculate"},
 {IDS_TRIGGERING                           ,"Triggering"},
 {IDS_OSHA1                                ,"OSHA-1"},
 {IDS_OSHA2                                ,"OSHA-2"},
 {IDS_ACGIH                                ,"ACGIH"},
 {IDS_NIOSH                                ,"NIOSH"},
 {IDS_IEC                                  ,"IEC"},
 {IDS_3DB                                  ,"3 dB"},
 {IDS_4DB                                  ,"4 dB"},
 {IDS_5DB                                  ,"5 dB"},
 {IDS_6DB                                  ,"6 dB"},
 {IDS_TABLIVE                              ,"Live"},
 {IDS_OVERALL                              ,"Overall"},
 {IDS_TABSESSIONLOG                        ,"Session Log"},
 {IDS_TABGENERAL                           ,"General"},
 {IDS_TABSLM                               ,"SLM"},
 {IDS_TABDOSE1                             ,"Dosimeter1"},
 {IDS_TABDOSE2                             ,"Dosimeter2"},
 {IDS_TABTRIGGER                           ,"Triggers"},
 {IDS_TABLN                                ,"Ln"},
 {IDS_OBA                                  ,"OBA"},
 {IDS_CONTROL                              ,"Control"},
 {IDS_CP_DATAEXPLORER                      ," Data \n Explorer "},
 {IDS_CP_CALIBRATE                         ,"Calibrate"},
 {IDS_CALIBRATE                            ,"Calibrate"},
 {IDS_CP_LOCK                              ,"Lock"},
 {IDS_CP_ABOUT                             ,"About"},
 {IDS_CP_SYSTEMPROPERTIES                  ," System \n Properties "},
 {IDS_CP_VOICERECORDER                     ," Voice \n Recorder "},
 {IDS_TABSABOUT1                           ,"About"},
 {IDS_TABSABOUT2                           ,"Standards"},
 {IDS_TABSABOUT3                           ,"Options"},
 {IDS_TABSABOUT4                           ,"User"},
 {IDS_TABSCAL1                             ,"Calibrate"},
 {IDS_TABSCAL2                             ,"History"},
 {IDS_TABSCAL3                             ,"Certification"},
 {IDS_MENU                                 ,"Menu"},
 {IDS_TITLE_CONTROL_PANEL                  ,"Control Panel"},
 {IDS_TITLE_ABOUT                          ,"About"},
 {IDS_TITLE_CALIBRATE                      ,"Calibrate Tool"},
 {IDS_TITLE_SYSTEMPROPERTIES               ,"System Properties"},
 {IDS_TITLE_VOICE_RECORDER                 ,"Voice Recorder"},
 {IDS_TITLE_DATA_EXPLORER                  ,"Data Explorer"},
 {IDS_SERIALNUMBER                         ,"Serial Number"},
 {IDS_MANUFACTURED                         ,"Manufactured"},
 {IDS_STANDARDS                            ," Standards "},
 {IDS_LARSONDAVIS                          ,"Larson Davis"},
 {IDS_PREC_INT_SLM_1                       ,"Precision Integrating"},
 {IDS_PREC_INT_SLM_2                       ,"Sound Level Meter"},
 {IDS_FULLOCTAVE                           ,"1/1 Octave"},
 {IDS_VOICEANNOTATION                      ,"Voice Annotation"},
 {IDS_OWNER                                ,"This unit belongs to"},
 {IDS_OPTION                               ,"Option"},
 {IDS_TABSSYSPROP1                         ,"Device"},
 {IDS_TABSSYSPROP2                         ,"Time"},
 {IDS_TABSSYSPROP3                         ,"Power"},
 {IDS_TABSSYSPROP4                         ,"Preferences"},
 {IDS_INSTRUMENTIDENTIFICATION             ,"Instrument Identification"},
 {IDS_AUTOOFFTIME                          ,"Auto-Off Time"},
 {IDS_POWERSAVETIME                        ,"Power-Save Time"},
 {IDS_BACKLIGHTTIME                        ,"Backlight Time"},
 {IDS_BACKLIGHTMODE                        ,"Backlight"},
 {IDS_DISPLAYCONTRAST                      ,"Display Contrast"},
 {IDS_5MIN                                 ,"  5 min"},
 {IDS_10MIN                                ," 10 min"},
 {IDS_30MIN                                ," 30 min"},
 {IDS_60MIN                                ," 60 min"},
 {IDS_NEVER                                ,"Never"},
 {IDS_5SEC                                 ,"  5 s"},
 {IDS_10SEC                                ," 10 s"},
 {IDS_30SEC                                ," 30 s"},
 {IDS_60SEC                                ," 60 s"},
 {IDS_ALWAYSON                             ,"Always On"},
 {IDS_OFF                                  ,"Off"},
 {IDS_DIM                                  ,"Dim"},
 {IDS_BRIGHT                               ,"Bright"},
 {IDS_LANGUAGE                             ,"Language"},
 {IDS_RESETPROMPTING                       ,"Reset Prompting"},
 {IDS_RESETPROMPT                          ,"Reset?"},
 {IDS_RESET                                ,"Clear"},
 {IDS_DECIMALSYMBOL                        ,"Decimal Symbol"},
 {IDS_DATEFORMAT                           ,"Date Format"},
 {IDS_SYNCPC                               ,"Sync Date/Time with PC"},
 {IDS_TAKTENABLED                          ,"Takt Maximal Data"},
 {IDS_COMMA                                ,"Comma (,)"},
 {IDS_PERIOD                               ,"Period (.)"},
 {IDS_DDMMMYYYY                            ,"d-m-y"},
 {IDS_YYYYMMMDD                            ,"y-m-d"},
 {IDS_V                                    ,"V"},
 {IDS_ESTRUNTIME                           ,"Estimated Run Time"},
 {IDS_BATTVOLTAGE                          ,"Battery Voltage"},
 {IDS_TITLE_POWERCONTROL                   ,"Power Control"},
 {IDS_TEMPERATUREINT                       ,"T(internal)"},
 {IDS_DEGREEF                              ,"°F"},
 {IDS_DEGREEC                              ,"°C"},
 {IDS_LOCKMODE                             ,"Lock Mode"},
 {IDS_ALLOWCALWHENLOCKED                   ,"Allow Cal. When Locked"},
 {IDS_LOCKCODE                             ,"Unlock Code"},
 {IDS_UNLOCKED                             ,"Unlocked"},
 {IDS_LOCKAUTOSTORE                        ,"Lock w/Auto Store"},
 {IDS_LOCKMANUAL                           ,"Lock w/Manual Store"},
 {IDS_FULLYLOCKED                          ,"Fully Locked"},
 {IDS_POWERCONTROLNAV                      ,"Off,Close,Setup"},
 {IDS_SYSDATE                              ,"System Date"},
 {IDS_SYSTIME                              ,"System Time"},
 {IDS_JAN                                  ,"Jan"},
 {IDS_FEB                                  ,"Feb"},
 {IDS_MAR                                  ,"Mar"},
 {IDS_APR                                  ,"Apr"},
 {IDS_MAY                                  ,"May"},
 {IDS_JUN                                  ,"Jun"},
 {IDS_JUL                                  ,"Jul"},
 {IDS_AUG                                  ,"Aug"},
 {IDS_SEP                                  ,"Sep"},
 {IDS_OCT                                  ,"Oct"},
 {IDS_NOV                                  ,"Nov"},
 {IDS_DEC                                  ,"Dec"},
 {IDS_AUTOSTOREMODE                        ,"Auto-Store"},
 {IDS_AS_NONE                              ,"None"},
 {IDS_AS_PROMPT                            ,"Prompt"},
 {IDS_AS_STORE                             ,"Store"},
 {IDS_YES                                  ,"Yes"},
 {IDS_NO                                   ,"No"},
 {IDS_OK                                   ,"OK"},
 {IDS_CANCEL                               ,"Cancel"},
 {IDS_SAVE                                 ,"Save"},
 {IDS_SAVEAS                               ,"Save As"},
 {IDS_SETTINGS                             ,"Settings"},
 {IDS_APPLYCHANGES                         ,"Apply Changes?"},
 {IDS_HISTORY                              ,"History"},
 {IDS_PERFORMED                            ,"Performed"},
 {IDS_DUE                                  ,"Due"},
 {IDS_CERTIFICATION                        ,"Certification"},
 {IDS_INTERVAL                             ,"Interval"},
 {IDS_REMINDER                             ,"Reminder"},
 {IDS_15DAYS                               ,"15 Days"},
 {IDS_30DAYS                               ,"30 Days"},
 {IDS_45DAYS                               ,"45 Days"},
 {IDS_60DAYS                               ,"60 Days"},
 {IDS_1YEAR                                ,"1 Year"},
 {IDS_2YEAR                                ,"2 Years"},
 {IDS_3YEAR                                ,"3 Years"},
 {IDS_4YEAR                                ,"4 Years"},
 {IDS_DESCRIPTION                          ,"Description"},
 {IDS_HZ                                   ,"Hz"},
 {IDS_CALIBRATOR                           ,"Calibrator"},
 {IDS_CALIBRATING                          ,"Calibrating"},
 {IDS_TITLE_DATAVIEWER                     ,"Data Viewer"},
 {IDS_TABSDATAVIEWER1                      ,"Data"},
 {IDS_TABSDATAVIEWER2                      ,"Session Log"},
 {IDS_LEVEL1                               ,"SPL 1"},
 {IDS_LEVEL2                               ,"SPL 2"},
 {IDS_SPLTRIGGER                           ,"Trigger Levels"},
 {IDS_LEVEL                                ,"Level"},
 {IDS_UNLOCKPROMPT                         ,"Enter 4-digit code"},
 {IDS_UNLOCK                               ,"Unlock"},
 {IDS_LOCKED1                              ,"This instrument has been"},
 {IDS_LOCKED2                              ,"LOCKED"},
 {IDS_LOCKED3                              ,"Press the Tools key to"},
 {IDS_LOCKED4                              ,"UNLOCK"},
 {IDS_INVALIDCODE                          ,"Invalid Code"},
 {IDS_CAL                                  ,"Cal."},
 {IDS_RUN                                  ,"Run"},
 {IDS_CONFIRM                              ,"Are you sure?"},
 {IDS_WARNING                              ,"Warning!"},
 {IDS_CERTEXPIRING1                        ,"Certification will expire in\n"},
 {IDS_CERTEXPIRING2                        ,"days"},
 {IDS_CERTEXPIRED                          ,"Certification has expired"},
 {IDS_RESETREQ                             ,"Reset Required"},
 {IDS_STOPREQ                              ,"Stop Required"},
 {IDS_SAVEFILE                             ,"Save File?"},
 {IDS_BROWSE                               ,"Browse"},
 {IDS_FILELIST                             ,"Files"},
 {IDS_CONTEXTMENU                          ,"Menu"},
 {IDS_MEASUREMENTOK                        ,"Measurement OK?"},
 {IDS_CALFAILED                            ,"Calibration Failed"},
 {IDS_SAVECAL                              ,"Save Results?"},
 {IDS_RECORD                               ,"Recording"},
 {IDS_PLAYBACK                             ,"Playback"},
 {IDS_SAVERECORDING                        ,"Save Recording?"},
 {IDS_STOP                                 ,"Stop"},
 {IDS_DENAVBUTTONS                         ," By page,Close,Menu"},
 {IDS_VIEW                                 ,"View"},
 {IDS_DELETE                               ,"Delete"},
 {IDS_RENAME                               ,"Rename"},
 {IDS_REFRESH                              ,"Refresh List"},
 {IDS_LOADSETTINGS                         ,"Load Settings"},
 {IDS_RENAMEFILE                           ,"Rename File?"},
 {IDS_DELETEFILE                           ,"Delete File?"},
 {IDS_OVERWRITEFILE                        ,"Overwrite File?"},
 {IDS_FILENAME_EXISTS                      ," Filename Exists \n Overwrite? "},
 {IDS_BATTERYTYPE                          ,"Battery Type"},
 {IDS_ALKALINE                             ,"Alkaline"},
 {IDS_NIMH                                 ,"NiMH"},
 {IDS_MEASUREMENT                          ,"Measurement"},
 {IDS_PAUSE                                ,"Pause"},
 {IDS_RESUME                               ,"Resume"},
 {IDS_VOICE                                ,"Voice"},
 {IDS_SOUND                                ,"Sound"},
 {IDS_KEY                                  ,"Keypress"},
 {IDS_IO                                   ,"IO Command"},
 {IDS_TIMER                                ,"Timer"},
 {IDS_POWER                                ,"Power"},
 {IDS_OUTOFMEMORY                          ,"Out of memory"},
 {IDS_COULDNTSAVE                          ,"Unable to save file"},
 {IDS_ERROR                                ,"Error"},
 {IDS_FIRMWAREREV                          ,"Firmware Rev"},
 {IDS_THIRDOCTAVE                          ,"1/3 Octave"},
 {IDS_PREAMP_CONNECT                       ,"Preamp Connected."},
 {IDS_PREAMP_DISCONNECT                    ,"Preamp Disconnected"},
 {IDS_JACKFUNC                             ,"Jack Function"},
 {IDS_JACKFUNC_ACDC                        ,"AC/DC"},
 {IDS_JACKFUNC_HEADSET                     ,"Headset"},
 {IDS_SETTIME                              ,"Set Time"},
 {IDS_UNLOCK1                              ,"Enter a 4-digit code to use"},
 {IDS_UNLOCK2                              ,"when unlocking this unit."},
 {IDS_UNAVAILABLE                          ," This feature is \n currently unavailable "},
 {IDS_TIMESET                              ,"Time has been set"},
 {IDS_SHUTDOWN_IMMINENT                    ," Low Battery! \n Power Failure Imminent! \n Please save your work. "},
 {IDS_INSTINFO                             ,"Instrument Information"},
 {IDS_PREAMPTYPE                           ,"Preamp"},
 {IDS_STANDARDSINFO1                       ,"This instrument conforms to"},
 {IDS_STANDARDSINFO2                       ,"the following standards"},
 {IDS_OPTIONNAME                           ,"Option Name"},
 {IDS_SETTINGSLOCKED                       ," Settings in use by PC. \n Continue? "},
 {IDS_CP_SYSUTILS                          ," System \n Utilities "},
 {IDS_FSERRCORRECTED                       ," File system errors \n detected and repaired. "},
 {IDS_FSERRNOTCORRECTED                    ," File system corrupt! \n Do you want to reformat? "},
 {IDS_TITLE_SYSUTIL                        ,"System Utilities"},
 {IDS_TABSYSUTIL1                          ,"File System"},
 {IDS_CHECK                                ,"Check File System"},
 {IDS_FORMAT                               ,"Format"},
 {IDS_FORMATALL                            ,"Format / Restore Defaults"},
 {IDS_DSPREV                               ,"DSP Rev"},
 {IDS_DELETEALLINTERNAL                    ,"Delete All Internal"},
 {IDS_CONFIRMDELETEALL                     ,"Delete All Files?"},
 {IDS_NOERRORS                             ," No errors \n found "},
 {IDS_OBABANDWIDTH                         ,"Bandwidth"},
 {IDS_FULLTHIRDOCTAVE                      ,"1/1, 1/3"},
 {IDS_INCOMPATIBLEBOOTLOADER               ," Incompatible bootloader. \n Contact Larson Davis "},
 {IDS_TABCURRENT                           ,"Current"},
 {IDS_TABMEASUREMENT                       ,"Measurement"},
 {IDS_TABTIMEHISTORY                       ,"Time History"},
 {IDS_TABEVENTS                            ,"Events"},
 {IDS_MARKSOUNDTYPE                        ,"Mark Sound Type"},
 {IDS_VIEWNORMALIZED                       ,"View Normalized"},
 {IDS_OVERLOADS                            ,"Overloads"},
 {IDS_LDN                                  ,"LDN"},
 {IDS_LDEN                                 ,"LDEN"},
 {IDS_TAKT                                 ,"LAFTM5"},
 {IDS_COMMUNITYNOISE                       ,"Community Noise"},
 {IDS_LINKTIMEHISTORY                      ,"Link - Time History"},
 {IDS_RECORDNUM                            ,"Record"},
 {IDS_LINKMEASUREMENTHISTORY1              ,"Link - Measurement"},
 {IDS_LINKMEASUREMENTHISTORY               ,"Link - Measurement History"},
 {IDS_SAMPLENUM                            ,"Sample"},
 {IDS_NUMMEASUREMENTS                      ,"Measurements"},
 {IDS_NUMEXCEEDANCES                       ,"Events"},
 {IDS_NUMTIMEHISTORIES                     ,"Time Histories"},
 {IDS_ENTERBYFREQ                          ,"Enter -> By Frequency"},
 {IDS_ENTERBYTIME                          ,"Enter -> By Time"},
 {IDS_PEAKTRIGGER2                         ,"Peak 2"},
 {IDS_PEAKTRIGGER3                         ,"Peak 3"},
 {IDS_DYNTRIGGEROFFSET                     ,"Dynamic Trig. Offset"},
 {IDS_DYNAMICRESPONSE                      ,"Dynamic Response"},
 {IDS_ATMAX                                ,"At Lmax"},
 {IDS_BINMAX                               ,"Bin Max"},
 {IDS_OBAMAXMODE                           ,"Max Spec."},
 {IDS_ENABLEMSMTHISTORY                    ,"Enable Measurement History"},
 {IDS_MEASUREMENTCOUNTER                   ,"Measurement Counter"},
 {IDS_CONTINUOUS                           ,"Continuous"},
 {IDS_SINGLEBLOCK                          ,"Single Block Timer"},
 {IDS_DAILYTIMER                           ,"Daily Timer"},
 {IDS_RUNMODE                              ,"Run Mode"},
 {IDS_MEASUREMENTTIME                      ,"Measurement Time"},
 {IDS_CLOCKSYNC                            ,"Interval Time Sync"},
 {IDS_DAILYAUTOSTORE                       ,"Auto-Store"},
 {IDS_AUTOSTORETIME                        ,"Auto-Store Time"},
 {IDS_AUTOCALCHECK                         ,"Cal. Check"},
 {IDS_AUTOCALCHECKTIME                     ,"Cal. Check Time"},
 {IDS_DAILY                                ,"Daily"},
 {IDS_TABEXCEEDANCEHISTORY                 ,"Event History"},
 {IDS_TABMARKER                            ,"Markers"},
 {IDS_ENABLETIMEHISTORY                    ,"Enable Time History"},
 {IDS_PERIOD1                              ,"Period"},
 {IDS_100PS                                ," 10 ms"},
 {IDS_50PS                                 ," 20 ms"},
 {IDS_20PS                                 ," 50 ms"},
 {IDS_10PS                                 ,"100 ms"},
 {IDS_5PS                                  ,"200 ms"},
 {IDS_2PS                                  ,"500 ms"},
 {IDS_1S                                   ,"  1 s"},
 {IDS_2S                                   ,"  2 s"},
 {IDS_5S                                   ,"  5 s"},
 {IDS_10S                                  ," 10 s"},
 {IDS_15S                                  ," 15 s"},
 {IDS_20S                                  ," 20 s"},
 {IDS_30S                                  ," 30 s"},
 {IDS_1MIN                                 ,"  1 min"},
 {IDS_2MIN                                 ,"  2 min"},
 {IDS_15MIN                                ," 15 min"},
 {IDS_20MIN                                ," 20 min"},
 {IDS_1HR                                  ,"  1 h"},
 {IDS_24HR                                 ," 24 h"},
 {IDS_LTWA1                                ,"Ltwa1"},
 {IDS_LTWA2                                ,"Ltwa2"},
 {IDS_LTWA3                                ,"Ltwa3"},
 {IDS_LTWA4                                ,"Ltwa4"},
 {IDS_LPEAK                                ,"Lpeak"},
 {IDS_LTM5                                 ,"LAFTM5"},
 {IDS_OBALEQ                               ,"OBA Leq Spectrum"},
 {IDS_OBALMAX                              ,"OBA Lmax Spectrum"},
 {IDS_OBALMIN                              ,"OBA Lmin Spectrum"},
 {IDS_2102HUMIDITY                         ,"Preamp Humidity"},
 {IDS_2102TEMPERATURE                      ,"Preamp Temp."},
 {IDS_THOPTIONS                            ,"Time History Options"},
 {IDS_TRIGGER_LEVEL                        ,"Trigger Level"},
 {IDS_TRIGGER_RISE_FALL                    ,"10dB Rise/Fall"},
 {IDS_TRIGGER_DYNAMIC                      ,"Dynamic"},
 {IDS_ENABLEEXCDHISTORY                    ,"Event History"},
 {IDS_MINIMUMDURATION                      ,"Min Duration"},
 {IDS_CONTPERIOD                           ,"Cont Period"},
 {IDS_TRIGGERMETHOD                        ,"Trigger Method"},
 {IDS_ENABLEEXCDTH                         ,"Event Time History"},
 {IDS_EXCDTHPERIOD                         ,"Period"},
 {IDS_ENABLEEXCDSPECTH                     ,"Spectral Mode"},
 {IDS_SEC                                  ,"s"},
 {IDS_VIEW15                               ,"1-5"},
 {IDS_VIEW610                              ,"6-10"},
 {IDS_PREREC                               ,"Pre-trigger Time"},
 {IDS_RECPERIOD                            ,"Recording Time"},
 {IDS_RECORDENABLE                         ,"Record"},
 {IDS_TABDAYNIGHT                          ,"Day/Night"},
 {IDS_TABAUDIO                             ,"Sound"},
 {IDS_DAY                                  ,"Day"},
 {IDS_EVENING                              ,"Evening"},
 {IDS_NIGHT                                ,"Night"},
 {IDS_PENALTY                              ,"Penalty"},
 {IDS_EXCDAUDIO                            ,"Event Sound Rec."},
 {IDS_SAVESNAPSHOT                         ,"Save Snapshot"},
 {IDS_SNAPSHOTPERIOD                       ,"Snapshot Time"},
 {IDS_PRETRIGGERPERIOD                     ,"Pre-trigger Time"},
 {IDS_MSMTAUDIO                            ,"Measurement Sound Rec."},
 {IDS_LEQA                                 ,"L<sub>A#eq</sub>"},
 {IDS_LPEAKA                               ,"L<sub>Apeak</sub>"},
 {IDS_LPEAKAMAX                            ,"L<sub>Apeak(max)</sub>"},
 {IDS_SLOWLMAXA                            ,"L<sub>ASmax</sub>"},
 {IDS_FASTLMAXA                            ,"L<sub>AFmax</sub>"},
 {IDS_IMPLMAXA                             ,"L<sub>AImax</sub>"},
 {IDS_SLOWLMINA                            ,"L<sub>ASmin</sub>"},
 {IDS_FASTLMINA                            ,"L<sub>AFmin</sub>"},
 {IDS_IMPLMINA                             ,"L<sub>AImin</sub>"},
 {IDS_LEQC                                 ,"L<sub>C#eq</sub>"},
 {IDS_LPEAKC                               ,"L<sub>Cpeak</sub>"},
 {IDS_LPEAKCMAX                            ,"L<sub>Cpeak(max)</sub>"},
 {IDS_SLOWLMAXC                            ,"L<sub>CSmax</sub>"},
 {IDS_FASTLMAXC                            ,"L<sub>CFmax</sub>"},
 {IDS_IMPLMAXC                             ,"L<sub>CImax</sub>"},
 {IDS_SLOWLMINC                            ,"L<sub>CSmin</sub>"},
 {IDS_FASTLMINC                            ,"L<sub>CFmin</sub>"},
 {IDS_IMPLMINC                             ,"L<sub>CImin</sub>"},
 {IDS_LEQZ                                 ,"L<sub>Z#eq</sub>"},
 {IDS_LPEAKZ                               ,"L<sub>Zpeak</sub>"},
 {IDS_LPEAKZMAX                            ,"L<sub>Zpeak(max)</sub>"},
 {IDS_SLOWLMAXZ                            ,"L<sub>ZSmax</sub>"},
 {IDS_FASTLMAXZ                            ,"L<sub>ZFmax</sub>"},
 {IDS_IMPLMAXZ                             ,"L<sub>ZImax</sub>"},
 {IDS_SLOWLMINZ                            ,"L<sub>ZSmin</sub>"},
 {IDS_FASTLMINZ                            ,"L<sub>ZFmin</sub>"},
 {IDS_IMPLMINZ                             ,"L<sub>ZImin</sub>"},
 {IDS_EXTPOWER                             ,"External Power"},
 {IDS_INTTEMP                              ,"Internal Temp."},
 {IDS_WINDSPD                              ,"Wind Speed"},
 {IDS_ADC1AVG                              ,"ADC1 Avg."},
 {IDS_ADC2AVG                              ,"ADC2 Avg."},
 {IDS_OBALEQ11                             ,"OBA 1/1 Leq"},
 {IDS_OBAMAX11                             ,"OBA 1/1 max"},
 {IDS_OBAMIN11                             ,"OBA 1/1 min"},
 {IDS_OBALEQ13                             ,"OBA 1/3 Leq"},
 {IDS_OBAMAX13                             ,"OBA 1/3 max"},
 {IDS_OBAMIN13                             ,"OBA 1/3 min"},
 {IDS_ASLOWSPL                             ,"L<sub>AS</sub>"},
 {IDS_AFASTSPL                             ,"L<sub>AF</sub>"},
 {IDS_AIMPLSPL                             ,"L<sub>AI</sub>"},
 {IDS_CSLOWSPL                             ,"L<sub>CS</sub>"},
 {IDS_CFASTSPL                             ,"L<sub>CF</sub>"},
 {IDS_CIMPLSPL                             ,"L<sub>CI</sub>"},
 {IDS_ZSLOWSPL                             ,"L<sub>ZS</sub>"},
 {IDS_ZFASTSPL                             ,"L<sub>ZF</sub>"},
 {IDS_ZIMPLSPL                             ,"L<sub>ZI</sub>"},
 {IDS_OBASPL                               ,"OBA SPL"},
 {IDS_OBASPL11                             ,"OBA 1/1 SPL"},
 {IDS_OBASPL13                             ,"OBA 1/3 SPL"},
 {IDS_USBSTORAGE                           ,"USB Storage"},
 {IDS_OVERWRITEFILES                       ,"Overwrite oldest files"},
 {IDS_COMPRESSDATAFILE                     ,"Compress data files"},
 {IDS_AUTO                                 ,"Auto"},
 {IDS_ENTERBY11FREQ                        ,"Enter -> By 1/1 Frequency"},
 {IDS_ENTERBY13FREQ                        ,"Enter -> By 1/3 Frequency"},
 {IDS_NORMALIZED_SPECTRUM                  ,"Normalized Spectrum"},
 {IDS_NORMALIZEDSPECTRUMNAV                ,"Set,Close,Edit"},
 {IDS_MARKSOUNDTYPE1NAV                    ,"Rec,Close,None"},
 {IDS_MARKSOUNDTYPE2NAV                    ,"Stop,Close,None"},
 {IDS_SPL                                  ,"SPL"},
 {IDS_REF                                  ,"Ref"},
 {IDS_OBAFREQWT                            ,"Freq. Wt."},
 {IDS_FILE                                 ,"File"},
 {IDS_NEGA                                 ,"-A"},
 {IDS_NEGC                                 ,"-C"},
 {IDS_EDIT_SPECTRA                         ,"Edit Reference Spectrum"},
 {IDS_SAVECHANGES                          ,"Save Changes?"},
 {IDS_EDITSPECTRUMNAV                      ," ,Close,Re.1kHz"},
 {IDS_CANTRECORDWHILESTOPPED               ," The instrument must be \n running to record. "},
 {IDS_WINDDIR                              ,"Gust Dir."},
 {IDS_THOPTIONSTURNEDOFF                   ," Some time history \n options have been \n turned off. "},
 {IDS_SOUNDREC                             ,"Sound Recorder"},
 {IDS_DATALOGGING                          ,"Time History"},
 {IDS_ANYDATA                              ,"ANY LEVEL"},
 {IDS_INTERVALS                            ,"Measurement History"},
 {IDS_WEATHER                              ,"Weather"},
 {IDS_GAIN                                 ,"+20dB Gain"},
 {IDS_NODATA                               ,"No Data"},
 {IDS_EXTPOWERED                           ,"Ext Powered"},
 {IDS_LDAY                                 ,"LDay"},
 {IDS_LEVENING                             ,"LEve"},
 {IDS_LNIGHT                               ,"LNight"},
 {IDS_INVALIDDATES                         ," Invalid start/stop dates. \n Continue? "},
 {IDS_PLEASEWAIT                           ,"Please wait..."},
 {IDS_PARTIAL                              ,"partial"},
 {IDS_TIMERSLOST                           ," Daily timers will \n be inactive. \n Continue? "},
 {IDS_LTWA                                 ,"LTWA"},
 {IDS_LOWMEMSTOP                           ," Out of memory! \n Instrument stopped. "},
 {IDS_SETTINGSMAYCHANGE                    ," Some options may change \n because of the time \n history sample period. "},
 {IDS_PREAMP_DISPLAY                       ,"Preamp Interface"},
 {IDS_TABSSYSPROP5                         ,"Displays"},
 {IDS_TABS                                 ,"Tabs"},
 {IDS_PAGES                                ,"Pages"},
 {IDS_STARTTAB                             ,"Start"},
 {IDS_DISP_PROFILE                         ,"Profile"},
 {IDS_DISP_11                              ,"1/1 Octave"},
 {IDS_DISP_13                              ,"1/3 Octave"},
 {IDS_DISP_TRIGGER                         ,"Trigger"},
 {IDS_DISP_POWER                           ,"Power"},
 {IDS_DISP_LEQ                             ,"Leq"},
 {IDS_DISP_DOSE1                           ,"Dose 1"},
 {IDS_DISP_DOSE2                           ,"Dose 2"},
 {IDS_DISP_SEL                             ,"SEL"},
 {IDS_DISP_PERCENTILES                     ,"Percentiles"},
 {IDS_DISP_EXCEEDANCES                     ,"Exceedances"},
 {IDS_DISP_SEA                             ,"SEA"},
 {IDS_DISP_OVERLOAD                        ,"Overloads"},
 {IDS_DISP_MEMORY                          ,"Memory"},
 {IDS_DISP_COMMUNITY                       ,"Community Noise"},
 {IDS_DISP_MISC                            ,"Miscellaneous"},
 {IDS_DISP_HISTORY                         ,"History"},
 {IDS_DISP_METRICS                         ,"Metrics"},
 {IDS_DISP_TIMEHISTORY                     ,"Time History"},
 {IDS_DISP_SPECTRAL_TIMEHISTORY            ,"Spectral Time History"},
 {IDS_NODISPLAYENABLED                     ," At least one \n page must be enabled. "},
 {IDS_GRAPHSETTINGS                        ,"Adjust Graph"},
 {IDS_GRAPHHEIGHT                          ,"Height"},
 {IDS_GRAPHBOTTOM                          ,"Bottom"},
 {IDS_CLOSEWND                             ,"'Enter' to close"},
 {IDS_SETUPMANAGER                         ," Setup \n Manager "},
 {IDS_COULDNTLOAD                          ,"Unable to load file"},
 {IDS_TABWEATHER                           ,"Weather"},
 {IDS_COMPASS                              ,"Compass"},
 {IDS_DEGREES                              ,"Degrees"},
 {IDS_PERCENT_TEXT                         ,"Percent"},
 {IDS_VOLTS                                ,"Volts"},
 {IDS_SCALE                                ,"Scale"},
 {IDS_UNITS                                ,"Units"},
 {IDS_OFFSET                               ,"Offset"},
 {IDS_WINDTHRESHOLD                        ,"Threshold"},
 {IDS_WINDEXCDLEVEL                        ,"Excd. Level"},
 {IDS_WINDHYSTERESIS                       ,"Hysteresis"},
 {IDS_WINDPAUSE                            ,"Pause"},
 {IDS_WIND                                 ,"Wind"},
 {IDS_HIGH                                 ,"High"},
 {IDS_DESC                                 ,"Desc."},
 {IDS_COULDNTSAVEUSB                       ," Couldn't save file to \n USB drive. "},
 {IDS_SAVETOUSB                            ,"Move to USB"},
 {IDS_WINDY                                ,"Windy"},
 {IDS_AVG                                  ,"Avg."},
 {IDS_GUST                                 ,"Gust"},
 {IDS_GUSTSPEED                            ,"Gust Speed"},
 {IDS_ADC1MAX                              ,"ADC1 Max"},
 {IDS_ADC1MIN                              ,"ADC1 Min"},
 {IDS_ADC2MAX                              ,"ADC2 Max"},
 {IDS_ADC2MIN                              ,"ADC2 Min"},
 {IDS_LAE                                  ,"LAE"},
 {IDS_LCE                                  ,"LCE"},
 {IDS_LZE                                  ,"LZE"},
 {IDS_OPT_DOSE                             ,"Industrial Hygiene"},
 {IDS_SPECLNMODE                           ,"Spectral Ln Mode"},
 {IDS_SPECTRAL_LN                          ,"Spectral Ln"},
 {IDS_PEAK                                 ,"Peak"},
 {IDS_SPL_S                                ,"SPL S"},
 {IDS_SPL_F                                ,"SPL F"},
 {IDS_SPL_I                                ,"SPL I"},
 {IDS_MAX_S                                ,"Max S"},
 {IDS_MAX_F                                ,"Max F"},
 {IDS_MAX_I                                ,"Max I"},
 {IDS_MIN_S                                ,"Min S"},
 {IDS_MIN_F                                ,"Min F"},
 {IDS_MIN_I                                ,"Min I"},
 {IDS_OCCURANCE                            ,"Occurance"},
 {IDS_GPS                                  ,"GPS"},
 {IDS_COMMUNICATION                        ,"Communication"},
 {IDS_WIRELESS                             ,"Wireless"},
 {IDS_MODEM                                ,"Modem"},
 {IDS_EXCD                                 ,"Excd"},
 {IDS_ALARM                                ,"Alarm"},
 {IDS_BOTH                                 ,"Both"},
 {IDS_DIALOUT                              ,"Dialout Settings"},
 {IDS_MONITORNUMBER                        ,"Monitor #"},
 {IDS_PHONENUMBER                          ,"Phone #"},
 {IDS_MODEMPASSWORD                        ,"Password"},
 {IDS_INITSTRING                           ,"Init String"},
 {IDS_ON                                   ,"On"},
 {IDS_NONE                                 ,"None"},
 {IDS_PRETRIGGER                           ,"Pre-trigger"},
 {IDS_MAX_SAMPLES                          ,"Max Samples"},
 {IDS_LATITUDE                             ,"Latitude"},
 {IDS_LONGITUDE                            ,"Longitude"},
 {IDS_ELEVATION                            ,"Elevation"},
 {IDS_GPSTIME                              ,"Acquired at"},
 {IDS_FEET                                 ,"Feet"},
 {IDS_METERS                               ,"Meters"},
 {IDS_LOCALIZATION                         ,"Localization"},
 {IDS_GPSMODE                              ,"GPS Mode"},
 {IDS_GPSSYNC                              ,"GPS Synchronized"},
 {IDS_GPSNOSYNC                            ,"GPS Not Synchronized"},
 {IDS_WIRELESS_MODEM                       ,"Wireless Modem"},
 {IDS_APN                                  ,"APN"},
 {IDS_APNUSERNAME                          ,"APN Username"},
 {IDS_APNPASSWORD                          ,"APN Password"},
 {IDS_UNITSSI                              ,"SI"},
 {IDS_UNITSENGLISH                         ,"English"},
 {IDS_RICORRECTION                         ,"Mic Corr."},
 {IDS_RI2FF                                ,"RI:FF"},
 {IDS_FF2RI                                ,"FF:RI"},
 {IDS_FF2RI_2106_8                         ,"FF:RI 2106/8"},
 {IDS_FF2FF_2106_8                         ,"FF:FF 2106/8"},
 {IDS_FF290_2106_8                         ,"FF:90 2106/8"},
 {IDS_ENTERCHANGEREC                       ,"Enter->Change Record"},
 {IDS_ENTERCHANGEMETRICS                   ,"Enter->Change Metrics"},
 {IDS_ENTERCHANGEEVENT                     ,"Enter->Change Event"},
 {IDS_ENTERCHANGEFREQ                      ,"Enter->Change Frequency"},
 {IDS_EVENT                                ,"Event"},
 {IDS_DELETEALLUSB                         ,"Delete All USB"},
 {IDS_RANGE                                ,"Range"},
 {IDS_IMPROPERSHUTDOWN                     ,"Improper Shutdown!"},
 {IDS_RESETDATA                            ," Data will be reset. \n Save data? "},
 {IDS_EDIT                                 ,"Edit"},
 {IDS_GPSGLOBALPOSITION                    ,"GPS Global Position"},
 {IDS_COULDNTDELETE                        ,"Couldn't Delete File"},
 {IDS_USBHOSTPORT                          ,"USB Host Port"},
 {IDS_OPEN                                 ,"Open"},
 {IDS_USBHOSTPORTTURNEDOFF                 ," USB Host Port \n has been turned off "},
 {IDS_TIMEZONECORR                         ,"Timezone (h:m)"},
 {IDS_CANNOTOVERWRITESYSFILE               ," Cannot overwrite \n system files "},
 {IDS_FILEINUSE_PC                         ," The file is already \n in use by the PC. "},
 {IDS_OBALASEQ                             ,"L<sub>$#eq</sub>"},
 {IDS_OBALASMAX                            ,"L<sub>$#max</sub>"},
 {IDS_OBALASMIN                            ,"L<sub>$#min</sub>"},
 {IDS_OBALAS                               ,"L<sub>$#</sub>"},
 {IDS_HM                                   ,"hh:mm"},
 {IDS_INVALIDMSMTTIME                      ," Invalid interval time. \n Time must be greater \n than 1 minute. "},
 {IDS_CAL_CHECK                            ,"Cal. Check"},
 {IDS_LOGICIO                              ,"Logic I/O"},
 {IDS_LOGICIN                              ,"Logic In"},
 {IDS_LOGICOUT                             ,"Logic Out"},
 {IDS_LOGICRUNSTATE                        ,"Run State"},
 {IDS_LOGICRUNSTOP                         ,"Run/Stop"},
 {IDS_USBMOVECOMPLETE                      ,"USB Move Complete"},
 {IDS_INVALIDTIMES                         ," Invalid start/stop times. \n Continue? "},
 {IDS_MICROPHONE                           ,"Microphone"},
 {IDS_TYPE                                 ,"Type"},
 {IDS_SENSITIVITY                          ,"Sensitivity"},
 {IDS_SELFNOISE                            ,"Self Noise"},
 {IDS_OVERLOADLEVEL                        ,"Overload Level"},
 {IDS_UNDERRANGELEVEL                      ,"Under Range Level"},
 {IDS_NOISEFLOOR                           ,"Noise Floor"},
 {IDS_MVPA                                 ,"mV/Pa"},
 {IDS_CALOUTOFRANGE                        ," Calibration outside \n normal range. \n Save anyway? "},
 {IDS_PUBLISHED                            ,"Nominal"},
 {IDS_INVALIDPERIOD                        ," Snapshot Time must be \n greater than event \n minimum duration. "},
 {IDS_EVENTPTCHANGED                       ," Event Pre-trigger time \n changed.  Minimum \n duration too large. "},
 {IDS_REMOVEUSBDRIVE                       ," You may now safely \n remove the USB drive. "},
 {IDS_T                                    ,"Temp"},
 {IDS_RH                                   ,"RH"},
 {IDS_DEWPOINT                             ,"Dew Point"},
 {IDS_OVERLOADIN                           ,"Overload In"},
 {IDS_MAINSPOWER                           ,"Mains Power"},
 {IDS_CALIBRATOR_ON                        ,"Calibrator On"},
 {IDS_SAMPLERATE                           ,"Sample Rate"},
 {IDS_USBFILEEXISTS                        ," The file already \n exists on the USB drive. \n File not moved. "},
 {IDS_SHORTED                              ,"Shorted"},
 {IDS_FAULT                                ,"Fault"},
 {IDS_USBFILETOOLARGE                      ," Insufficient space on \n USB drive. \n Operation canceled. "},
 {IDS_ENV                                  ,"LxT-ENV"},
 {IDS_HDRCMINUSA                           ,"C minus A"},
 {IDS_IMPULSIVITY                          ,"Impulsivity"},
 {IDS_LIEQ                                 ,"L<sub>$Ieq</sub>"},
 {IDS_LACZEQ                               ,"L<sub>$eq</sub>"},
 {IDS_LIEQMINUSLEQ                         ,"L<sub>$Ieq</sub> - L<sub>$eq</sub>"},
 {IDS_HSLOG                                ,"Fast Time History"},
 {IDS_LITH                                 ,"Lithium"},
 {IDS_BACK5S                               ,"Back-5s"},
 {IDS_BACK10S                              ,"Back-10s"},
 {IDS_UNDOBACK                             ,"Undo"},
 {IDS_DUR_FRAC                             ,"Tms"},
 {IDS_WSLOWSPL                             ,"L<sub>$S</sub>"},
 {IDS_WFASTSPL                             ,"L<sub>$F</sub>"},
 {IDS_WIMPLSPL                             ,"L<sub>$I</sub>"},
 {IDS_DISP_PROFILE_LARGE                   ,"Enforcement Market"},
 {IDS_MS                                   ,"ms"},
 {IDS_GRAPH_RELATIVE                       ,"Graph Relative"},
 {IDS_REF1                                 ,"Ref"},
 {IDS_NAME1                                ,"Name"},
 {IDS_JUMP_TO_TOP                          ,"Jump to Beginning"},
 {IDS_JUMP_TO_BOTTOM                       ,"Jump to End"},
 {IDS_CALRANGEDIFF                         ," Calibration change \n more than 0.5dB. \n Save anyway? "},
 {IDS_DENAVBUTTONS1                        ,"By item,Close,Menu"},
 {IDS_TABS_CAL_CHECK                       ,"Cal. Check"},
 {IDS_CAL_LEVEL                            ,"Cal. Level"},
 {IDS_STD_CAL_LEVEL                        ,"Enter Standard Cal. Level"},
 {IDS_TABS_CAL_CHECK_HISTORY               ,"Check History"},
 {IDS_THLOCATE                             ,"Locate"},
 {IDS_THFIRST                              ,"First"},
 {IDS_THLAST                               ,"Last"},
 {IDS_THRECNUM                             ,"Record Number"},
 {IDS_SESSIONLOG                           ,"Session Log"},
 {IDS_LAENEW                               ,"L$E"},
 {IDS_RS232                                ,"RS-232"},
 {IDS_BAUDRATE                             ,"Baud Rate"},
 {IDS_B9600                                ,"9600"},
 {IDS_B19200                               ,"19200"},
 {IDS_B57600                               ,"57600"},
 {IDS_B115200                              ,"115200"},
 {IDS_DLYAUTOSTORENEVER                    ,"Never"},
 {IDS_DLYAUTOSTORE1                        ,"1/day"},
 {IDS_DLYAUTOSTORE2                        ,"2/day"},
 {IDS_DLYAUTOSTORE4                        ,"4/day"},
 {IDS_DLYAUTOSTORE6                        ,"6/day"},
 {IDS_DLYAUTOSTORE8                        ,"8/day"},
 {IDS_DLYAUTOSTORE12                       ,"12/day"},
 {IDS_DLYAUTOSTORE24                       ,"24/day"},
 {IDS_DLYAUTOSTORE48                       ,"48/day"},
 {IDS_DLYAUTOSTORE96                       ,"96/day"},
 {IDS_DLYAUTOSTORE144                      ,"144/day"},
 {IDS_FLOWCONTROL                          ,"Flow Control"},
 {IDS_FCNONE                               ,"None"},
 {IDS_XONXOFF                              ,"Xon/Xoff"},
 {IDS_HARDWARE                             ,"Hardware"},
 {IDS_400PS                                ,"2.5 ms"},
 {IDS_200PS                                ,"  5 ms"},
 {IDS_FST                                  ,"Fast Time History"},
 {IDS_PREPOSTTRIGGER                       ,"Pre/Post Trigger"},
 {IDS_NOTIFYUSBMOVE                        ," USB thumb drive \n still busy. \n Poweroff anyway? "},
 {IDS_SETTINGSCONFLICT                     ," Settings conflict. \n Fix automatically? "},
 {IDS_FSTCONFLICT                          ," Cannot be enabled \n when Fast Time History \n is set. "},
 {IDS_DISP_TRIG_STATUS                     ,"Event Trig. Status Display"},
 {IDS_CAL_CHECK_SPECTRUM                   ,"Cal. Check Spectrum"},
 {IDS_CALIBRATE_SPECTRUM                   ,"Calibration Spectrum"},
 {IDS_POWERINGOFF                          ,"Powering Off"},
 {IDS_FSTOBANOTIFY                         ," OBA 1/1 Octave \n is disabled. "},
 {IDS_MARK                                 ,"Mark"},
 {IDS_GPSTIMESYNC                          ,"Time Sync"},
 {IDS_DELTAT                               ,"Correction"},
 {IDS_EXCDPAUSE                            ,"Excd. Pause"},
 {IDS_ENABLEWEATHER                        ,"Enable Weather"},
 {IDS_THNOTIFY                             ," No option selected. \n Time History \n will be disabled. "},
 {IDS_EXTSHUTOFFVOLT                       ,"Ext Shutoff Voltage"},
 {IDS_REPAIRUSB                            ,"Check/Repair USB"},
 {IDS_USBCHECKSTATUS                       ," USB check/repair \n done. "},
 {IDS_USBFILENOMOUNT                       ,"USB File System not found."},
 {IDS_USBNOCHECK                           ," Cannot check/repair/format \n when move is in progress. "},
 {IDS_USBFORMATSTATUS                      ,"USB drive formatted."},
 {IDS_FORMATUSB                            ,"Format USB"},
 {IDS_ADV_COMM                             ,"Adv. Communication"},
 {IDS_ANALOG_MODEM                         ,"Analog Modem"},
 {IDS_PASSWORD                             ,"Password"},
 {IDS_DISP_FREQ11                          ,"1/1 Octave by Frequency"},
 {IDS_DISP_FREQ13                          ,"1/3 Octave by Frequency"},
 {IDS_DISP_TIME11                          ,"1/1 Octave by Time"},
 {IDS_DISP_TIME13                          ,"1/3 Octave by Time"},
 {IDS_USBSAVENOTIFY                        ," A previous move in progress. \n Cannot move. "},
 {IDS_BATTPOWERED                          ,"Batt Powered"},
 {IDS_DISP_SPTH_BYTIME                     ,"Spectral Time History (t)"},
 {IDS_DAILYTIMERNOTIFY                     ," One or more timers overlap. \n Continue? "},
 {IDS_INVALIDTIME                          ," Invalid time. \n Time must be greater than 1 second. "},
 {IDS_SAVESETUP                            ,"Change active settings?"},
 {IDS_STATUS                               ,"Status"},
 {IDS_CHANNEL                              ,"Channel"},
 {IDS_CURSTATE                             ,"State"},
 {IDS_PREVSTATE                            ,"Previous"},
 {IDS_IN                                   ,"In"},
 {IDS_OUT                                  ,"Out"},
 {IDS_TIMEOUT                              ,"Timeout"},
 {IDS_USB                                  ,"USB"},
 {IDS_TIMERSLOST1                          ," Daily timers will \n be disabled.\nContinue? "},
 {IDS_USBRMNOTIFY                          ," Please wait while \n USB operation cleans up. "},
 {IDS_USBCOMMNOTIFY                        ," Other communication device \n will be disabled. \n Continue? "},
 {IDS_CALCHECK                             ,"Cal. Check"},
 {IDS_CALCHANGE                            ,"Cal. Change"},
 {IDS_CALIBRATIONCHANGED                   ,"Measured difference"},
 {IDS_CALCHECKDB                           ,"Level (dB)"},
 {IDS_CALCHANGEDB                          ,"Change (dB)"},
 {IDS_FSTCONFLICT1                         ," Settings conflict. \n Fast Time History enabled. "},
 {IDS_SAVETOUSBALL                         ,"Move All to USB"},
 {IDS_USBMOVENOTIFY                        ," File in use \n not moved. "},
 {IDS_USBDUPLICATENOTIFY                   ," Duplicate filename(s) \n altered."},
 {IDS_USBNOMOVENOTIFY                      ," Some files not \n moved."},
 {IDS_LN1                                  ,"Ln1"},
 {IDS_LN2                                  ,"Ln2"},
 {IDS_LN3                                  ,"Ln3"},
 {IDS_LN4                                  ,"Ln4"},
 {IDS_LN5                                  ,"Ln5"},
 {IDS_LN6                                  ,"Ln6"},
 {IDS_PAUSETIME                            ,"Pause Time"},
 {IDS_INVALIDMSMTTIME1                     ," Invalid interval time. \n Time must be greater \n than 1 second. Continue? "},
 {IDS_INVALIDMSMTTIME2                     ," Invalid interval time. \n Time must be 1 minute \n or greater. Continue? "},
 {IDS_FORMATFAILED                         ," File System format \n failed. "},
 {IDS_NOPLAYBACK                           ," Cannot play when \n auto-store mode is \n set to store. "},
 {IDS_FILEINUSE                            ,"Cannot open. File in use."},
 {IDS_PCBREV                               ,"PCB Rev"},
 {IDS_SOUNDRECORDINGS                      ,"Sound Recordings"},
 {IDS_FSCHECKNOTIFY                        ," The instrument will be \n stopped. "},
 {IDS_CANNOTDELETEFILE                     ," Cannot delete. \n File is use. "},
 {IDS_NOPLAYBACK1                          ," Please save the \n file before playing. "},
 {IDS_CANNOTRENAME                         ," A file with similar \n name is in use. \n Cannot overwrite. "},
 {IDS_CANNOTRENAMECOPY                     ," Cannot rename. \n File in use. "},
 {IDS_PREAMPNOTSUPPORTED                   ,"Preamp not supported."},
 {IDS_STABLE                               ,"Stable"},
 {IDS_DEMO                                 ,"Demo"},
 {IDS_BACKERASE                            ,"Back Erase"},
 {IDS_PRINT                                ,"Print Summary"},
 {IDS_DOSESETTINGS                         ,"Dose Settings"},
 {IDS_RESULTS                              ,"Results"},
 {IDS_PRINTSCREEN                          ,"Print Screen"},
 {IDS_MTLMEASDESC                          ," Measurement \n Description "},
 {IDS_MTLCOMMUNITYNOISE                    ," Community \n Noise "},
 {IDS_MTLLNPERCENTILE                      ," Ln \n Percentiles "},
 {IDS_MTLOVERALLSETTINGS                   ," Overall \n Settings "},
 {IDS_MTLPRINTSUCCESS                      ,"Printing is complete."},
 {IDS_MTLNOPRINTER                         ,"Printer not present."},
 {IDS_MTLDISCONNECT                        ," Printer disconnected. \n Print failed. "},
 {IDS_DISP_PROFILE_LARGE1                  ,"Big Digit"},
 {IDS_DISPLAYWARNING                       ," Cannot turn off \n all displays. "},
 {IDS_TABSYSOPTIONS                        ,"Options"},
 {IDS_TABSMSOUT                            ,"SMS Out"},
 {IDS_SENDSMSON                            ,"Send SMS On"},
 {IDS_MEMLOW                               ,"Low Memory"},
 {IDS_SMSIN                                ,"SMS In"},
 {IDS_ALL                                  ,"All"},
 {IDS_WEATHERINT                           ,"Weather-INT"},
 {IDS_WEATHERVAISALA                       ,"Vaisala"},
 {IDS_MAXRATE                              ,"Max Rate"},
 {IDS_ACCUMULATION                         ,"Accumulation"},
 {IDS_RAINRATE                             ,"Rain Rate"},
 {IDS_HAILRATE                             ,"Hail Rate"},
 {IDS_OPTIONSWARNING                       ," Cannot turn off all options. \n Turning on default options. "},
 {IDS_OPTIONS                              ,"Options"},
 {IDS_OPTIONSCHANGED                       ," Options changed. \n Please reboot the meter. "},
 {IDS_MM_PER_HOUR                          ,"<sup>mm</sup>/<sub>hr</sub>"},
 {IDS_IN_PER_HOUR                          ,"<sup>in</sup>/<sub>hr</sub>"},
 {IDS_HITS_PER_CM_SQ_HOUR                  ,"<sup>hits</sup>/<sub>cm²h</sub>"},
 {IDS_HITS_PER_IN_SQ_HOUR                  ,"<sup>hits</sup>/<sub>in²h</sub>"},
 {IDS_HITS_PER_CM_SQ                       ,"<sup>hits</sup>/<sub>cm²</sub>"},
 {IDS_HITS_PER_IN_SQ                       ,"<sup>hits</sup>/<sub>in²</sub>"},
 {IDS_METERS_PER_SEC                       ,"m/s"},
 {IDS_MI_PER_HOUR                          ,"mi/h"},
 {IDS_INCHES                               ,"in"},
 {IDS_MILIMETERS                           ,"mm"},
 {IDS_CENTIMETERS                          ,"cm"},
 {IDS_PERCENT_RH                           ,"% RH"},
 {IDS_EMPTY                                ," "},
 {IDS_OPT_QC_TONALITY                      ,"QC Tonality"},
 {IDS_CORRECTED_DBA                        ,"Corrected dBA"},
 {IDS_CORR_OBALASEQ                        ,"Corr. L$#eq"},
 {IDS_WARN_REVISION                        ," Incompatible board revision \n for this feature. "},
 {IDS_RS232_WILL_DISABLE                   ,"RS232 Will Be Disabled..."},
 {IDS_VAISALA_WILL_DISABLE                 ,"Vaisala Will Be Disabled..."},
 {IDS_Q_DISABLE_USB                        ,"Disable USB Port?"},
 {IDS_TALARM                               ,"TA-Larm"},
 {IDS_LN95                                 ,"Ln95"},
 {IDS_LN                                   ,"Ln Statistics"},
 {IDS_SLM                                  ,"SLM"},
 {IDS_Q_CHANGE_MODES                       ,"Change Modes?"},
 {IDS_PRINTENFORCEMENT                     ,"Print Enforcement"},
 {IDS_PRINTCALIBRATION                     ,"Print Calibration"},
 {IDS_MTLLOCATION                          ,"Location"},
 {IDS_MTLBY                                ,"By"},
 {IDS_MTLDEPT                              ,"Dept"},
 {IDS_CALIBRATION                          ,"Calibration"},
 {IDS_SERIALNO                             ,"Serial #"},
 {IDS_REFSPL                               ,"Ref.SPL"},
 {IDS_SELECT                               ,"Select"},
 {IDS_NEW                                  ,"New"},
 {IDS_OLD                                  ,"Old"},
 {IDS_SAVE_CAL_STD_LVL                     ," Save %sdB as \n Standard Cal. Level? "},
 {IDS_USB_LOW_POWER                        ," USB thumb drive disabled \n due to low power. "},
 {IDS_SIL                                  ,"SIL"},
 {IDS_DEVELOPER                            ,"Developer"},
 {IDS_ROOM_ACOUSTICS_NL                    ," Room \n Acoustics "},
 {IDS_ROOM_ACOUSTICS                       ,"Room Acoustics"},
 {IDS_RT60                                 ,"RT-60"},
 {IDS_RT60_SR                              ,"RT-60 Sound Rec."},
 {IDS_SOURCE                               ,"Source"},
 {IDS_RTA                                  ,"RTA"},
 {IDS_RTA_SR                               ,"RTA Sound Rec."},
 {IDS_SPECTRA                              ,"Spectra"},
 {IDS_PROJECT_NAME                         ,"Project Name"},
 {IDS_NOISE_RT60                           ,"RT-60 Noise"},
 {IDS_NOISE_RTA                            ,"RTA Noise"},
 {IDS_NOISE                                ,"Noise"},
 {IDS_NOISE_WHITE                          ,"White"},
 {IDS_NOISE_PINK                           ,"Pink"},
 {IDS_AMPLITUDE                            ,"Amplitude"},
 {IDS_MUTE                                 ,"Mute"},
 {IDS_1_1                                  ,"1/1"},
 {IDS_1_3                                  ,"1/3"},
 {IDS_IMPULSE                              ,"Impulse"},
 {IDS_INT_NOISE                            ,"Interrupted"},
 {IDS_TRIG_FREQ                            ,"Trigger Freq."},
 {IDS_TRIG_SOURCE                          ,"Trigger Source"},
 {IDS_BUILD_TIME                           ,"Build Time"},
 {IDS_MAX_RUN_TIME                         ,"Max Run Time"},
 {IDS_SAVE_AVG_TS                          ,"Save Ensemble Time Series"},
 {IDS_SAVE_ALL_TS                          ,"Save All Time Series"},
 {IDS_EXIT_TIME                            ,"Exit Time"},
 {IDS_LOWEST_BAND                          ,"Lowest Filter"},
 {IDS_HIGHEST_BAND                         ,"Highest Filter"},
 {IDS_ATTENUATION                          ,"Attenuation"},
 {IDS_ADVANCED                             ,"Advanced"},
 {IDS_BACK                                 ,"Back"},
 {IDS_T20                                  ,"T20"},
 {IDS_T30                                  ,"T30"},
 {IDS_EDT                                  ,"EDT"},
 {IDS_SAMPLE                               ,"Sample"},
 {IDS_ENSEMBLE                             ,"Ensemble"},
 {IDS_ENTER_CHANGE_DATA                    ,"Enter->Change Data"},
 {IDS_ENTER_CHANGE                         ,"Enter->Change"},
 {IDS_METHOD                               ,"Method"},
 {IDS_MID_BAND                             ,"Mid Band"},
 {IDS_F_6_3                                ,"6.30 Hz"},
 {IDS_F_8                                  ,"8.00 Hz"},
 {IDS_F_10                                 ,"10.0 Hz"},
 {IDS_F_12_5                               ,"12.5 Hz"},
 {IDS_F_16                                 ,"16.0 Hz"},
 {IDS_F_20                                 ,"20.0 Hz"},
 {IDS_F_25                                 ,"25.0 Hz"},
 {IDS_F_31_5                               ,"31.5 Hz"},
 {IDS_F_40                                 ,"40.0 Hz"},
 {IDS_F_50                                 ,"50.0 Hz"},
 {IDS_F_63                                 ,"63.0 Hz"},
 {IDS_F_80                                 ,"80.0 Hz"},
 {IDS_F_100                                ,"100 Hz"},
 {IDS_F_125                                ,"125 Hz"},
 {IDS_F_160                                ,"160 Hz"},
 {IDS_F_200                                ,"200 Hz"},
 {IDS_F_250                                ,"250 Hz"},
 {IDS_F_315                                ,"315 Hz"},
 {IDS_F_400                                ,"400 Hz"},
 {IDS_F_500                                ,"500 Hz"},
 {IDS_F_630                                ,"630 Hz"},
 {IDS_F_800                                ,"800 Hz"},
 {IDS_F_1000                               ,"1.00 kHz"},
 {IDS_F_1250                               ,"1.25 kHz"},
 {IDS_F_1600                               ,"1.60 kHz"},
 {IDS_F_2000                               ,"2.00 kHz"},
 {IDS_F_2500                               ,"2.50 kHz"},
 {IDS_F_3150                               ,"3.15 kHz"},
 {IDS_F_4000                               ,"4.00 kHz"},
 {IDS_F_5000                               ,"5.00 kHz"},
 {IDS_F_6300                               ,"6.30 kHz"},
 {IDS_F_8000                               ,"8.00 kHz"},
 {IDS_F_10000                              ,"10.0 kHz"},
 {IDS_F_12500                              ,"12.5 kHz"},
 {IDS_F_16000                              ,"16.0 kHz"},
 {IDS_F_20000                              ,"20.0 kHz"},
 {IDS_LINK_TO_DISPLAY                      ,"Link to Source display"},
 {IDS_BT                                   ,"BT"},
 {IDS_BK                                   ,"BK"},
 {IDS_CO                                   ,"Co"},
 {IDS_CU                                   ,"Cu"},
 {IDS_SD                                   ,"SD"},
 {IDS_INCLUDE                              ,"Include"},
 {IDS_EXCLUDE                              ,"Exclude"},
 {IDS_RUN_RA_L1                            ,"Run-L1"},
 {IDS_RUN_RA_L2                            ,"Run-L2"},
 {IDS_RUN_RA_B2                            ,"Run-B2"},
 {IDS_RUN_RA_T2                            ,"Run-T2"},
 {IDS_RUN_RA_TH                            ,"Run Time History"},
 {IDS_MASK_OPTION_MATCH                    ," Options changed. \n Cannot view the file. "},
 {IDS_NOPLAYBACK_RUNNING                   ," Cannot play when \n the meter is running. "},
 {IDS_NL                                   ,"NL"},
 {IDS_RT60_STATUS                          ,"RT-60 Status"},
 {IDS_RT60_TIMES                           ,"RT-60 Times"},
 {IDS_RT60_DECAYS                          ,"RT-60 Decays"},
 {IDS_RT60_LEVELS                          ,"RT-60 Levels"},
 {IDS_QI_SUMMARY1                          ,"Quality Summary"},
 {IDS_QI_SUMMARY2                          ,"Quality Summary 2"},
 {IDS_QI_DETAIL                            ,"Quality Detail"},
 {IDS_SURVEY                               ,"Survey"},
 {IDS_ENGINEERING                          ,"Engineering"},
 {IDS_PRECISION                            ,"Precision"},
 {IDS_POSITION                             ,"Position"},
 {IDS_POSITIONS                            ,"Positions"},
 {IDS_DECAY_PER_POS                        ,"Decays/Position"},
 {IDS_DECAY                                ,"Decay"},
 {IDS_DECAYS                               ,"Decays"},
 {IDS_EST_GRADE                            ,"Estimated Grade"},
 {IDS_FREG_RANGE                           ,"Frequency Range"},
 {IDS_DASHES                               ,"- - -"},
 {IDS_ACTUAL                               ,"Actual"},
 {IDS_REQUIRED                             ,"Required"},
 {IDS_CONFIRM_DELETEALL_SLM                ,"Delete All SLM Files?"},
 {IDS_CONFIRM_DELETEALL_RA                 ,"Delete All RA Files?"},
 {IDS_CONFIRM_DELETEALL_FFT                ,"Delete All FFT Files?"},
 {IDS_INSTALLED                            ,"Installed"},
 {IDS_TEMPERATURE                          ,"Temperature"},
 {IDS_HUMIDITY                             ,"Relative Humidity"},
 {IDS_L1_RANGE                             ,"L1 Range"},
 {IDS_L2_RANGE                             ,"L2 Range"},
 {IDS_B2_RANGE                             ,"B2 Range"},
 {IDS_B2                                   ,"B2"},
 {IDS_L1L2                                 ,"L1 L2"},
 {IDS_SAMPLEPERIOD                         ,"Sample Period"},
 {IDS_MAX_POSITION                         ," Max Position Count \n Reached "},
 {IDS_SETTING_CONFLICT                     ,"Setting conflict"},
 {IDS_NOT_APPLICABLE                       ,"Not Applicable"},
 {IDS_FFT                                  ,"FFT"},
 {IDS_FFT_LIVE                             ,"FFT Live"},
 {IDS_CREATE_AVG                           ,"Create Average"},
 {IDS_ADD_TO_AVG                           ,"Add to Average"},
 {IDS_ERROR_CANNOT_AVERAGE                 ," Settings conflict. \n Cannot average. "},
 {IDS_CREATED_AVERAGE                      ,"File Avg"},
 {IDS_FILE_AVERAGING                       ,"File Averaging"},
 {IDS_WINDOW                               ,"Window"},
 {IDS_HANNING                              ,"Hanning"},
 {IDS_FLATTOP                              ,"Flat Top"},
 {IDS_RECTANGULAR                          ,"Rectangular"},
 {IDS_FREQUENCY_SPAN                       ,"Frequency Span"},
 {IDS_LINES                                ,"Lines"},
 {IDS_6400                                 ,"6400"},
 {IDS_3200                                 ,"3200"},
 {IDS_1600                                 ,"1600"},
 {IDS_800                                  ,"800"},
 {IDS_400                                  ,"400"},
 {IDS_MANUAL                               ,"Manual"},
 {IDS_COUNT_STOP                           ,"Count Stop"},
 {IDS_CURSOR                               ,"Cursor"},
 {IDS_CURSOR_TYPE                          ,"Cursor Type"},
 {IDS_MAX_TRACKING                         ,"Max-Tracking"},
 {IDS_HARMONICS                            ,"Harmonics"},
 {IDS_TO                                   ,"To"},
 {IDS_BAD_TIMES                            ," Invalid evening time. \n Fix automatically? "},
 {IDS_FLASH_ERROR                          ," Bad Flash blocks detected. \n Please backup data and \n format the file-system. "},
 {IDS_COMMS_WATCHDOG                       ,"Communications Watchdog"},
 {IDS_COMMS_WATCHDOG_COUNT                 ,"Comm WD Count"},
 {IDS_TEMPERATURE_AVG                      ,"Temperature Avg."},
 {IDS_TEMPERATURE_MAX                      ,"Temperature Max"},
 {IDS_TEMPERATURE_MIN                      ,"Temperature Min"},
 {IDS_HUMIDITY_AVG                         ,"Humidity Avg."},
 {IDS_HUMIDITY_MAX                         ,"Humidity Max"},
 {IDS_HUMIDITY_MIN                         ,"Humidity Min"},
 {IDS_OFF_CLOSE                            ,"Off,Close, "},
 {IDS_ERROR_LOG                            ,"Error Log"},
 {IDS_TIMER_EXPIRED                        ,"Expired"},
 {IDS_TONALITYX                            ,"Tonality"},
 {IDS_1996_TONALITY                        ,"ISO 1996-2 Tonality"},
 {IDS_TONE                                 ,"Tone"},
 {IDS_TONES                                ,"Tones"},
 {IDS_NO_TONES                             ,"No Tones"},
 {IDS_LPT                                  ,"Lpt"},
 {IDS_LPN                                  ,"Lpn"},
 {IDS_LTA                                  ,"Lta"},
 {IDS_KT                                   ,"Kt"},
 {IDS_BCRIT                                ,"Bcrit"},
 {IDS_SETTINGS_DIFFER                      ," Settings differ from the \n tonality standard. \n Fix automatically? "},
 {IDS_RUNNING                              ,"Running"},
 {IDS_TONE_SEEK_DELTA                      ,"Tone Seek Delta"},
 {IDS_TONE_SEEK_DELTA_1                    ,"1 dB"},
 {IDS_TONE_SEEK_DELTA_2                    ,"2 dB"},
 {IDS_TONE_SEEK_DELTA_3                    ,"3 dB"},
 {IDS_TONE_SEEK_DELTA_4                    ,"4 dB"},
 {IDS_LR_SPAN_PERCENT                      ,"Regression Range"},
 {IDS_LR_SPAN_PERCENT_50                   ," 50 %"},
 {IDS_LR_SPAN_PERCENT_75                   ," 75 %"},
 {IDS_LR_SPAN_PERCENT_100                  ,"100 %"},
 {IDS_LR_SPAN_PERCENT_150                  ,"150 %"},
 {IDS_LR_SPAN_PERCENT_200                  ,"200 %"},
 {IDS_HEATER                               ,"Heater"},
 {IDS_AC_OUT_DISABLED                      ," AC/DC jack function \n has been disabled "},
 {IDS_WATCHDOG                             ,"Watchdog"},
 {IDS_831_INT_ET                           ,"831 INT-ET"},
 {IDS_COUNTER_WRAP                         ,"Timer Limit"},
 {IDS_NF30_LN                              ,"NF30 Ln"},
 {IDS_FAST_WEATHER                         ,"Fast Weather"},
 {IDS_REMAINING_LEQ                        ,"Remaining Leq"},
 {IDS_ELAPSED                              ,"Elapsed"},
 {IDS_CURRENT                              ,"Current"},
 {IDS_REMAINING                            ,"Remaining"},
 {IDS_TARGET                               ,"Target"},
 {IDS_VAISALA_WEATHER                      ,"Vaisala Weather"},
 {IDS_OTHER                                ,"Other"},
 {IDS_RAM_SIZE                             ,"RAM Size"},
 {IDS_NETWORK                              ,"Network"},
 {IDS_IP_ADDR                              ,"IP"},
 {IDS_MAC_ADDR                             ,"MAC"},
 {IDS_TIME_WEIGHTED_AVE                    ,"Time-Weighted Averages"},
 {IDS_MTIME_RES                            ,"Millisecond Time Resolution"},
 {IDS_SETTINGS_MODIFIED                    ,"Settings have been modified."},
 {IDS_SETTOACTIVE                          ,"Set to Active"},
 {IDS_HLD_YOU_MUST_ENABLE                      ,"You must enable"},
 {IDS_HLD_SETTINGSCONFLICT_INTEGRATION         ,"Settings conflict: Integration Method must be Linear also Measurement, Save Snapshot and Event History must be disabled to enable this setting. Fix automatically?"},
 {IDS_HLD_SETTINGSCONFLICT_SAVE_SNAP           ,"Settings conflict: Save Snapshot Event must be disabled to enable this setting. Fix automatically?"},
 {IDS_HLD_FST_ONENTHIRD_OPTIONS           ,"You must enable the Fast Time History, 1/1 Octave and 1/3 Octave Options."},
 {IDS_HLD_SAMPLERATE_TOOHIGH              ,"Settings conflict: Sound Recording sample rate set too high; max is 8 ksps with Time History. Fix automatically?"},
 {IDS_HLD_SOUNDRECORDING_OPTION           ,"You must enable the Sound Recording Option."},
 {IDS_HLD_USBHOSTPORT_GPS                 ,"You must enable the USB Host Port and the GPS Mode must be On."},
 {IDS_HLD_ENABLE_USBHOSTPORT              ,"You must enable the USB Host Port."},
 {IDS_HLD_ENABLE_MEASHISTORY              ,"You must enable Measurement History."},
 {IDS_HLD_RUNTIME_59SECS                  ,"Run Time must be greater than 59 seconds."},
 {IDS_HLD_EN_MEASHIST_NOTMANUAL           ,"You must enable Measurement History and the Run Mode must not be 'Manual Stop'"},
 {IDS_HLD_EN_MEASHIST_OPTION              ,"You must enable the Measurement History Option."},
 {IDS_HLD_EN_EVENTHIST                    ,"You must enable Event History."},
 {IDS_HLD_EN_MEASHIST_N_OPTION            ,"You must enable Measurement History and the Measurement History Option."},
 {IDS_HLD_DIFFER_TONALITYSTD_FIX          ,"Settings differ from the tonality standard. Fix automatically?"},
 {IDS_HLD_RS232DISABLED                   ,"RS232 will be disabled.  Continue?"},
 {IDS_HLD_EN_TIMEDSTOP                    ,"Must enable Timed Stop"},
 {IDS_HLD_REQUIREDPREAMP                  ,"Not supported with attached preamplifier."},
 {IDS_HLD_RT60METHOD_INTERRUPTED          ,"RT-60 Method must be set to Interrupted."},
 {IDS_HLD_STOREONCEDAILY                  ,"You must choose to Store at least once daily."},
 {IDS_HLD_MUSTBE_INTET                    ,"The meter must be seated in an INT/INT-ET."},
 {IDS_FF2RI_2116                         ,"FF:RI 2116"},
 {IDS_FF2FF_2116                         ,"FF:FF 2116"},
 {IDS_FF290_2116                         ,"FF:90 2116"},
 {IDS_HLD_DYNAMIC_RANGE                  ,"Dynamic Range Compression"},
 {IDS_HLD_SAVEFILE , "Save to File"},
 {IDS_HLD_BUFFERLEN , "Buffer Length"},
 {IDS_HLD_ARMS ,"a<sub>RMS</sub>"},
 {IDS_HLD_APEAK ,"a<sub>PEAK</sub>"},
 {IDS_HLD_AMIN ,"a<sub>MIN</sub>"},
 {IDS_HLD_AMAX ,"MTVV"},
 {IDS_HLD_RETURNOVERALL ,"Return to Overall tab"},
 {IDS_HLD_UPLOADFIRM ,"Upload Firmware"},
 {IDS_HLD_MODEL ,"Model"},
 {IDS_HLD_CONN_TYPE ,"Connection Type"},
 {IDS_HLD_SENSORSTAT ,"Sensor Status"},
 {IDS_HLD_TEDS ,"TEDS"},
 {IDS_HLD_SYSSTAT ,"System Status"},
 {IDS_HLD_WIFI ,"WiFi"},
 {IDS_HLD_CHARGING ,"Charging"},
 {IDS_HLD_MISSING ,"Missing"},
 {IDS_HLD_USING ,"Using"},
 {IDS_HLD_CHARGED ,"Charged"},
 {IDS_HLD_BATLOW ,"Low"},
 {IDS_HLD_SAVE_MEASPROPS ,"Save Measurement Properties"},
 {IDS_HLD_SAVE_SYSPROPS ,"Save System Properties"},
 {IDS_HLD_FIRMWARE ,"Firmware"},
 {IDS_HLD_FILETYPE ,"File Type"},
 {IDS_HLD_INTERNAL_MEM ,"Using Internal Memory"},
 {IDS_HLD_FAIL_FSCK ,"SD Card: File System Error; Remove and format with computer." },
 {IDS_HLD_TIME_REM ,"Time Remaining (H:M)"},
 {IDS_HLD_SENS_ERROR ,"Not Connected or Error"},
 {IDS_HLD_SETWIFI ,"Setup WiFi"},
 {IDS_HLD_SENSOR ,"Sensor"},
 {IDS_HLD_ADD ,"Add"},
 {IDS_HLD_SETAP ,"Set Access Point"},
 {IDS_HLD_UP ,"Up"},
 {IDS_HLD_DOWN ,"Down"},
 {IDS_HLD_SETNET ,"Connect to WiFi"},
 {IDS_HLD_SETNET_ERROR ,"You must have at least one configured WiFi network."},
 {IDS_HLD_WIFI_NET ,"WiFi Network"},
 {IDS_HLD_MY_IP ,"My IP"},
 {IDS_HLD_SAVED ,"Saved"},
 {IDS_HLD_NETWORKS ,"Network"},
 {IDS_HLD_PRIORITY ,"Preference"},
 {IDS_HLD_SIGNAL ,"Signal"},
 {IDS_HLD_SCANNING ,"Scanning"},
 {IDS_HLD_NET_OPEN ,"Open"},
 {IDS_HLD_NETSECURE ,"Secured"},
 {IDS_HLD_CONFIRM_REM_NET ,"Are you sure you wish to forget this WiFi network?"},
 {IDS_HLD_CONFIRM_DELETE ,"Forget Confirmation"},
 {IDS_HLD_CONFIRM_UPGRADE ,"Upgrade Confirmation"},
 {IDS_HLD_CONFIRM_DELFILE ,"You are about to delete this file"},
 {IDS_HLD_CONF_CON_NET ,"Connect to WiFi Network"},
 {IDS_HLD_CONF_LOSECON ,"If you proceed, you may lose connection with the meter if not connected via USB. Please connect to the same network as the meter."},
 {IDS_HLD_CONF_SET_AP ,"Set as Access Point"},
 {IDS_HLD_FILEMAN ,"File Manager"},
 {IDS_HLD_VIBRATION ,"Vibration"},
 {IDS_HLD_HANDARM ,"Hand/Arm"},
 {IDS_HLD_WHOLEBODY ,"Whole Body"},
 {IDS_HLD_DATAFILE ,"Data File"},
 {IDS_HLD_VIEWFILE ,"View data file"},
 {IDS_HLD_DELSELFILE ,"Delete selected file"},
 {IDS_HLD_REFLIST ,"Refresh file list"},
 {IDS_HLD_UPNEWFIRM ,"Upload New Firmware"},
 {IDS_HLD_CONFREQ ,"Confirmation Required"},
 {IDS_HLD_ANNOMEAS ,"Annotate Measurement"},
 {IDS_HLD_ANNOTIME ,"Annotation Time"},
 {IDS_HLD_ANNOTATE ,"Annotate"},
 {IDS_HLD_ANNONOTE ,"Note"},
 {IDS_HLD_SUMMATION ,"Σ Summation"},
 {IDS_HLD_AXIS ,"Axis"},
 {IDS_HLD_TOTAL ,"Total"},
 {IDS_HLD_MODE ,"Mode"},
 {IDS_HLD_OVLD ,"Overloaded"},
 {IDS_HLD_CONF ,"Confirm"},
 {IDS_HLD_WILLREBOOT ,"The meter will be rebooted."},
 {IDS_HLD_WILLSTOPREBOOT ,"The meter will be stopped and rebooted."},
 {IDS_HLD_PROCFILE ,"Processing file"},
 {IDS_HLD_REBOOTING ,"Rebooting"},
 {IDS_HLD_CLOSING ,"Closing"},
 {IDS_HLD_SETUP ,"Setup"},
 {IDS_HLD_SCHEDULE ,"Schedule"},
 {IDS_HLD_MISC ,"Misc"},
 {IDS_HLD_TOOLS ,"Tools"},
 {IDS_HLD_TOOLS2 ,"Tools 2"},
 {IDS_HLD_OPERATING_MODE ,"Operating Mode"},
 {IDS_HLD_OM_VIB ,"Vibration"},
 {IDS_HLD_OM_HA ,"Hand/Arm"},
 {IDS_HLD_OM_WB ,"Whole Body"},
 {IDS_HLD_STORE_INTER_TIME ,"Store Interval Time"},
 {IDS_HLD_SEC ,"Sec"},
 {IDS_HLD_MIN ,"Min"},
 {IDS_HLD_HR ,"Hr"},
 {IDS_HLD_W_WS ,"Ws Severity"},
 {IDS_HLD_W_FA ,"Fa 0.4-100 Hz"},
 {IDS_HLD_W_FB ,"Fb 0.4-1250 Hz"},
 {IDS_HLD_W_FC ,"Fc 6.3-1250 Hz"},
 {IDS_HLD_W_WH ,"Wh"},
 {IDS_HLD_W_WM ,"Wm Buildings"},
 {IDS_HLD_W_WB ,"Wb Railways-Z"},
 {IDS_HLD_W_WC ,"Wc Seatback-X"},
 {IDS_HLD_W_WD ,"Wd Horizontal-XY"},
 {IDS_HLD_W_WE ,"We Rotational"},
 {IDS_HLD_W_WG ,"Wg BS 8461-Z"},
 {IDS_HLD_W_WJ ,"Wj Head-X"},
 {IDS_HLD_W_WK ,"Wk Vertical-Z"},
 {IDS_HLD_W_WF ,"Wf Low Freq"},
 {IDS_HLD_DELAY_START ,"Delay Start"},
 {IDS_HLD_RUN_DUR ,"Run Duration"},
 {IDS_HLD_STOR_RAW ,"Store Raw Data"},
 {IDS_HLD_STOR_PEAK ,"Store Peak Data"},
 {IDS_HLD_AUTOSTOP ,"Autostop"},
 {IDS_HLD_OBA_TH ,"OBA Time History"},
 {IDS_HLD_DB_REF ,"dB Reference"},
 {IDS_HLD_EXP_LIMIT ,"Exposure Limit"},
 {IDS_HLD_EXP_ACTION ,"Exposure Action"},
 {IDS_HLD_DIS_UNITS ,"Display Units"},
 {IDS_HLD_INTEGRATION ,"Integration"},
 {IDS_HLD_K_FACTOR ,"k-Factor"},
 {IDS_HLD_BASE_NAME ,"Data File Name"},
 {IDS_HLD_SF_NAME ,"Setting File Name"},
 {IDS_HLD_AUTO_STORE ,"Auto Store"},
 {IDS_HLD_STORE_TIME ,"Store Time"},
 {IDS_HLD_SINGLE ,"Single"},
 {IDS_HLD_DOUBLE ,"Double"},
 {IDS_HLD_ACDC_OUTPUT ,"AC/DC Output"},
 {IDS_HLD_AC_W ,"AC: Weighted"},
 {IDS_HLD_AC_B ,"AC: BandLimit"},
 {IDS_HLD_DC_RMS ,"DC: RMS"},
 {IDS_HLD_DC_MIN ,"DC: Min"},
 {IDS_HLD_DC_MAX ,"DC: Max"},
 {IDS_HLD_DC_PEAK ,"DC: Peak"},
 {IDS_HLD_DC_RMS_SUM ,"DC: RMS Sum"},
 {IDS_HLD_DC_MIN_SUM ,"DC: Min Sum"},
 {IDS_HLD_DC_MAX_SUM ,"DC: Max Sum"},
 {IDS_HLD_DC_PEAK_SUM ,"DC: Peak Sum"},
 {IDS_HLD_RPT_HEADERS ,"Report Headers"},
 {IDS_HLD_PRNT_HSTRY ,"Print History"},
 {IDS_HLD_SENSOR_LIST ,"Sensor List"},
 {IDS_HLD_ACCEL_TYPE ,"Accelerometer"},
 {IDS_HLD_DIRECT ,"Direct"},
 {IDS_HLD_CHARGE ,"Charge"},
 {IDS_HLD_SENSORS ,"Sensors"},
 {IDS_HLD_SERIAL_NUM ,"Serial #"},
 {IDS_HLD_X_SENS ,"x Sens."},
 {IDS_HLD_Y_SENS ,"y Sens."},
 {IDS_HLD_Z_SENS ,"z Sens."},
 {IDS_HLD_ADD ,"Add"},
 {IDS_HLD_STDATE ,"Start Date"},
 {IDS_HLD_ENDATE ,"End Date"},
 {IDS_HLD_SENSOR_NA ,"Error or sensor doesn't support TEDS."},
 {IDS_HLD_CONNECTED ,"Connected"},
 {IDS_HLD_NOTCONN ,"Not Connected"},
 {IDS_HLD_ALERT ,"Alert"},
 {IDS_HLD_CN_FAIL ,"Failed to Connect to Network. Meter is still an Access Point."},
 {IDS_HLD_CN_SUCC ,"Meter is now connected with IP"},
 {IDS_HLD_CN_RESET ,"Meter is resetting WiFi"},
 {IDS_HLD_AP_SUCC ,"Meter is now set to be an Access Point."},
 {IDS_HLD_AP_ERR ,"Error Setting Access Point."},
 {IDS_HLD_STATUS ,"Status"},
 {IDS_HLD_WF_ENTNETPASS ,"Enter Network Password"},
 {IDS_HLD_WF_ADDNET ,"Add Network"},
 {IDS_FIRMUPG_CHOS ,"Choose Firmware"},
 {IDS_FIRMUPG_SAME ,"The meter was succesfully updated to the same configuration."},
 {IDS_FIRMUPG_SUCCESS ,"Successfully updated the meter."},
 {IDS_FIRMUPG_FAIL ,"The meter failed to update. The update file may have been invalid or the connection may have been lost during transmission. Verify that you have a valid update file and try again."},
 {IDS_HLD_FAIL ,"Failed"},
 {IDS_HLD_FINISHED ,"Finished"},
 {IDS_HLD_REFERENCE ,"Reference"},
 {IDS_HLD_SET ,"Set"},
 {IDS_HLD_UPG_AP ,"You must reconnect to the meter's WiFi (access point). Closing this window."},
 {IDS_HLD_APOINT ,"Access Point"},
 {IDS_HLD_AP_LOSECON ,"If you proceed, you will be temporarily disconnected from the meter and may need to reconnect to the network."},
 {IDS_HLD_CNCTING ,"Connecting"},
 {IDS_HLD_LOSTDLG ,"It appears the connection was lost. Select 'Home' to return to the meter list."},
 {IDS_HLD_LOSTCON ,"Lost Connection"},
 {IDS_HLD_MINPASS ,"Either no password or at least an 8 character password must be entered to match your WiFi network."},
 {IDS_HLD_MISNAME ,"You must enter a valid WiFi network name (SSID)."},
 {IDS_STOP_METER  ,"Stop the Meter?"},
 {IDS_HLD_STOP_METER ,"Stop the Meter?"},
 {IDS_HLD_DO_CAL ,"Do Calibration"},
 {IDS_HLD_QUESTION ,"Question"},
 {IDS_HLD_PREAMP ,"Preamplifier"},
 {IDS_HLD_DBPK ,"dB<sub>pk</sub>"},
 {IDS_HLD_MIC_SAVED ,"Sensitivity data has been written to the meter."},
};


#endif
/*****************************************************************************/
// end of module

