	/*1149*/ {IDS_INSTRUMENT_NAME                      ,"Instrument Name"},
	/*1150*/ {IDS_CZECH                                ,"Cestina"},
	/*1151*/ {IDS_ENGLISH                              ,"English"},
	/*1152*/ {IDS_FRENCH                               ,"Français"},
	/*1153*/ {IDS_GERMAN                               ,"Deutsch"},
	/*1154*/ {IDS_HUNGARIAN                            ,"Magyar"},
	/*1155*/ {IDS_ITALIAN                              ,"Italiano"},
	/*1156*/ {IDS_NORWEGIAN                            ,"Norsk"},
	/*1157*/ {IDS_POLISH                               ,"Polski"},
	/*1158*/ {IDS_PORTUGUESE_BR                        ,"Português(BR)"},
	/*1159*/ {IDS_PORTUGUESE_PT                        ,"Português(PT)"},
	/*1160*/ {IDS_ROMANIAN                             ,"Limba Româna"},
	/*1161*/ {IDS_RUSSIAN                              ,"‰¸¶¶ª§¨"},
	/*1162*/ {IDS_SPANISH                              ,"Español"},
	/*1163*/ {IDS_SWEDISH                              ,"Svenska"},
	/*1164*/ {IDS_TURKISH                              ,"Türkçe"},
	/*1165*/ {IDS_LASEQ                                ,"L$#eq"},
	/*1166*/ {IDS_LAS                                  ,"L$#"},
	/*1167*/ {IDS_LAPEAK                               ,"L^peak"},
	/*1168*/ {IDS_LAPEAKMAX                            ,"L^peak(max)"},
	/*1169*/ {IDS_LASMAX                               ,"L$#max"},
	/*1170*/ {IDS_LASMIN                               ,"L$#min"},
	/*1171*/ {IDS_LASE                                 ,"L$#E"},
	/*1172*/ {IDS_EAS                                  ,"E$#"},
	/*1173*/ {IDS_EAS8                                 ,"E$#8"},
	/*1174*/ {IDS_EAS40                                ,"E$#40"},
	/*1175*/ {IDS_LASG                                 ,"L$# >"},
	/*1176*/ {IDS_LAPEAKG                              ,"L^peak >"},
	/*1177*/ {IDS_LEQ1S                                ,"L$#eq(1s)"},
	/*1178*/ {IDS_LCEQ                                 ,"LC#eq"},
	/*1179*/ {IDS_LAEQ                                 ,"LA#eq"},
	/*1180*/ {IDS_LWMAX                                ,"L$max"},
	/*1181*/ {IDS_LWMIN                                ,"L$min"},
	/*1182*/ {IDS_LWAVG                                ,"L$avg"},
	/*1183*/ {IDS_LWPEAK_MAX                           ,"L$max(max)"},
	/*1184*/ {IDS_LWPEAK_AVG                           ,"L$max(avg)"},
	/*1185*/ {IDS_LW                                   ,"L$"},
	/*1186*/ {IDS_LWDBK                                ,"L$#bk"},
	/*1187*/ {IDS_CMINUSA                              ,"LC#eq - LA#eq"},
	/*1188*/ {IDS_FREQWT                               ,"Frequenzbewertung"},
	/*1189*/ {IDS_DETECTOR                             ,"Zeitbewertung"},
	/*1190*/ {IDS_PEAKWT                               ,"Peakbewertung"},
	/*1191*/ {IDS_INTEGRATIONMETHOD                    ,"Mittelung"},
	/*1192*/ {IDS_A                                    ,"A"},
	/*1193*/ {IDS_C                                    ,"C"},
	/*1194*/ {IDS_Z                                    ,"Z"},
	/*1195*/ {IDS_SLOW                                 ,"Slow"},
	/*1196*/ {IDS_FAST                                 ,"Fast"},
	/*1197*/ {IDS_IMPL                                 ,"Impl"},
	/*1198*/ {IDS_SLOWS                                ,"S"},
	/*1199*/ {IDS_FASTF                                ,"F"},
	/*1200*/ {IDS_IMPLI                                ,"I"},
	/*1201*/ {IDS_LINEAR                               ,"Linear"},
	/*1202*/ {IDS_EXPONENTIAL                          ,"Exponentiell"},
	/*1203*/ {IDS_RUNTIME                              ,"Messzeit:"},
	/*1204*/ {IDS_STARTED                              ,"Start:"},
	/*1205*/ {IDS_TWA24                                ,"TWA"},
	/*1206*/ {IDS_PROJTWA                              ,"ProjTWA"},
	/*1207*/ {IDS_LEPD                                 ,"Lep,d"},
	/*1208*/ {IDS_DOSE                                 ,"Dosis"},
	/*1209*/ {IDS_PROJDOSE                             ,"ProjDosis"},
	/*1210*/ {IDS_WEIGHTING                            ,"Bewertung"},
	/*1211*/ {IDS_EXCHANGERATE                         ,"Halbierungsp."},
	/*1212*/ {IDS_SOUNDEXPOSURELEVEL                   ,"Schallexpositionspegel"},
	/*1213*/ {IDS_SOUNDEXPOSURE                        ,"Schallexposition"},
	/*1214*/ {IDS_EXCEEDANCES                          ,"Überschreitungen"},
	/*1215*/ {IDS_COUNT                                ,"Anzahl"},
	/*1216*/ {IDS_DURATION                             ,"Dauer"},
	/*1217*/ {IDS_SEA1                                 ,"SEA"},
	/*1218*/ {IDS_FREQWEIGHTINGZ                       ,"Frequenzbewertung: ^"},
	/*1219*/ {IDS_STARTTIME                            ,"Startzeit"},
	/*1220*/ {IDS_ENDTIME                              ,"Stopzeit"},
	/*1221*/ {IDS_LEQ                                  ,"Leq"},
	/*1222*/ {IDS_LMAX                                 ,"Lmax"},
	/*1223*/ {IDS_LMIN                                 ,"Lmin"},
	/*1224*/ {IDS_VIEWOBA                              ,"Terzanalyse"},
	/*1225*/ {IDS_VIEWSLM                              ,"Pegelanzeige"},
	/*1226*/ {IDS_NORMALIZE                            ,"Normiert"},
	/*1227*/ {IDS_LOCATE                               ,"Suchen >"},
	/*1228*/ {IDS_PLAY                                 ,"Abspielen"},
	/*1229*/ {IDS_ENTER                                ,"Ausführen"},
	/*1230*/ {IDS_CLOSE                                ,"Schließen"},
	/*1231*/ {IDS_CLOSE_CENTERED                       ," ,Schließen, "},
	/*1232*/ {IDS_LNPERCENTILES                        ,"Ln Perzentile"},
	/*1233*/ {IDS_DATE                                 ,"Datum "},
	/*1234*/ {IDS_TIME                                 ,"Zeit"},
	/*1235*/ {IDS_RUNTIMER                             ,"Messdauer"},
	/*1236*/ {IDS_BATTERY                              ,"Batterie"},
	/*1237*/ {IDS_USBPOWERED                           ,"USB- Versorgung"},
	/*1238*/ {IDS_MEMORY                               ,"Speicher"},
	/*1239*/ {IDS_DATAFILES                            ,"Datenfiles"},
	/*1240*/ {IDS_FREE                                 ,"Frei"},
	/*1241*/ {IDS_OF                                   ,"aus"},
	/*1242*/ {IDS_HR                                   ,"h"},
	/*1243*/ {IDS_MEASUREMENT_DESC                     ,"Beschreibung"},
	/*1244*/ {IDS_DEFAULTFILENAME                      ,"Grundeinstellung Dateiname"},
	/*1245*/ {IDS_SPLTRIGGER1                          ,"Pegeltrigger 1"},
	/*1246*/ {IDS_SPLTRIGGER2                          ,"Pegeltrigger 2"},
	/*1247*/ {IDS_PEAKTRIGGER1                         ,"Peak 1"},
	/*1248*/ {IDS_DB                                   ,"dB"},
	/*1249*/ {IDS_PERCENT                              ,"%"},
	/*1250*/ {IDS_1                                    ,"1"},
	/*1251*/ {IDS_2                                    ,"2"},
	/*1252*/ {IDS_3                                    ,"3"},
	/*1253*/ {IDS_4                                    ,"4"},
	/*1254*/ {IDS_5                                    ,"5"},
	/*1255*/ {IDS_6                                    ,"6"},
	/*1256*/ {IDS_OBARANGE                             ,"Messbereich Terzen"},
	/*1257*/ {IDS_NORMAL                               ,"Normal"},
	/*1258*/ {IDS_LOW                                  ,"Niedrig"},
	/*1259*/ {IDS_MANUAL_STOP                          ,"Stop manuell"},
	/*1260*/ {IDS_RUNTILLSTABLE                        ,"Stop wenn konstant"},
	/*1261*/ {IDS_DELTA                                ,"Delta"},
	/*1262*/ {IDS_HMS                                  ,"hh:mm:ss"},
	/*1263*/ {IDS_TIMED_STOP                           ,"Stop nach Zeit"},
	/*1264*/ {IDS_NAME                                 ,"Name"},
	/*1265*/ {IDS_ENABLED                              ,"Aktiviert"},
	/*1266*/ {IDS_THRESHOLD                            ,"Triggerschwelle"},
	/*1267*/ {IDS_CRITERION                            ,"Kriterium"},
	/*1268*/ {IDS_AUTOCALCULATE                        ,"Auto- Berechnung"},
	/*1269*/ {IDS_TRIGGERING                           ,"Trigger"},
	/*1270*/ {IDS_OSHA1                                ,"OSHA-1"},
	/*1271*/ {IDS_OSHA2                                ,"OSHA-2"},
	/*1272*/ {IDS_ACGIH                                ,"ACGIH"},
	/*1273*/ {IDS_NIOSH                                ,"NIOSH"},
	/*1274*/ {IDS_IEC                                  ,"IEC"},
	/*1275*/ {IDS_3DB                                  ,"3 dB"},
	/*1276*/ {IDS_4DB                                  ,"4 dB"},
	/*1277*/ {IDS_5DB                                  ,"5 dB"},
	/*1278*/ {IDS_6DB                                  ,"6 dB"},
	/*1279*/ {IDS_TABLIVE                              ,"Echtzeit"},
	/*1280*/ {IDS_OVERALL                              ,"Übersicht"},
	/*1281*/ {IDS_TABSESSIONLOG                        ,"Dokumentation"},
	/*1282*/ {IDS_TABGENERAL                           ,"Standard"},
	/*1283*/ {IDS_TABSLM                               ,"Pegel"},
	/*1284*/ {IDS_TABDOSE1                             ,"Dosimeter1"},
	/*1285*/ {IDS_TABDOSE2                             ,"Dosimeter2"},
	/*1286*/ {IDS_TABTRIGGER                           ,"Trigger"},
	/*1287*/ {IDS_TABLN                                ,"Ln"},
	/*1288*/ {IDS_OBA                                  ,"Filter"},
	/*1289*/ {IDS_CONTROL                              ,"Einstellungen"},
	/*1290*/ {IDS_CP_DATAEXPLORER                      ," Daten- \n explorer "},
	/*1291*/ {IDS_CP_CALIBRATE                         ,"Kalibrierung"},
	/*1292*/ {IDS_CALIBRATE                            ,"Kalibrierung"},
	/*1293*/ {IDS_CP_LOCK                              ,"Sperre"},
	/*1294*/ {IDS_CP_ABOUT                             ,"Systeminfo"},
	/*1295*/ {IDS_CP_SYSTEMPROPERTIES                  ," System- \n einstellungen "},
	/*1296*/ {IDS_CP_VOICERECORDER                     ," Sprach- \n aufzeichnung "},
	/*1297*/ {IDS_TABSABOUT1                           ,"Systeminfo"},
	/*1298*/ {IDS_TABSABOUT2                           ,"Normen"},
	/*1299*/ {IDS_TABSABOUT3                           ,"Optionen"},
	/*1300*/ {IDS_TABSABOUT4                           ,"Anwender"},
	/*1301*/ {IDS_TABSCAL1                             ,"Kalibrierung"},
	/*1302*/ {IDS_TABSCAL2                             ,"Historie"},
	/*1303*/ {IDS_TABSCAL3                             ,"Zertifizierung"},
	/*1304*/ {IDS_MENU                                 ,"Menü"},
	/*1305*/ {IDS_TITLE_CONTROL_PANEL                  ,"Systemmenü"},
	/*1306*/ {IDS_TITLE_ABOUT                          ,"Systeminfo"},
	/*1307*/ {IDS_TITLE_CALIBRATE                      ,"Kalibrierung"},
	/*1308*/ {IDS_TITLE_SYSTEMPROPERTIES               ,"Systemeinstellungen"},
	/*1309*/ {IDS_TITLE_VOICE_RECORDER                 ,"Sprachaufzeichnung"},
	/*1310*/ {IDS_TITLE_DATA_EXPLORER                  ,"Datenexplorer"},
	/*1311*/ {IDS_SERIALNUMBER                         ,"Seriennummer:"},
	/*1312*/ {IDS_MANUFACTURED                         ,"Hergestellt:"},
	/*1313*/ {IDS_STANDARDS                            ,"Normen "},
	/*1314*/ {IDS_LARSONDAVIS                          ,"Larson Davis"},
	/*1315*/ {IDS_PREC_INT_SLM_1                       ,"Integrierender"},
	/*1316*/ {IDS_PREC_INT_SLM_2                       ,"Schallpegelmesser"},
	/*1317*/ {IDS_FULLOCTAVE                           ,"Oktavspektrum"},
	/*1318*/ {IDS_VOICEANNOTATION                      ,"Sprach-\naufzeichnung"},
	/*1319*/ {IDS_OWNER                                ,"Das Gerät gehört:"},
	/*1320*/ {IDS_OPTION                               ,"Option"},
	/*1321*/ {IDS_TABSSYSPROP1                         ,"Gerät"},
	/*1322*/ {IDS_TABSSYSPROP2                         ,"Uhrzeit"},
	/*1323*/ {IDS_TABSSYSPROP3                         ,"Einstellungen"},
	/*1324*/ {IDS_TABSSYSPROP4                         ,"Präferenzen"},
	/*1325*/ {IDS_INSTRUMENTIDENTIFICATION             ,"Geräteidentifikation"},
	/*1326*/ {IDS_AUTOOFFTIME                          ,"Zeit bis Auto-Stopp"},
	/*1327*/ {IDS_POWERSAVETIME                        ,"Zeit bis Standby"},
	/*1328*/ {IDS_BACKLIGHTTIME                        ,"Bel.-Dauer"},
	/*1329*/ {IDS_BACKLIGHTMODE                        ,"Beleuchtung"},
	/*1330*/ {IDS_DISPLAYCONTRAST                      ,"Kontrast"},
	/*1331*/ {IDS_5MIN                                 ," 5 min"},
	/*1332*/ {IDS_10MIN                                ,"10 min"},
	/*1333*/ {IDS_30MIN                                ,"30 min"},
	/*1334*/ {IDS_60MIN                                ,"60 min"},
	/*1335*/ {IDS_NEVER                                ,"Nie"},
	/*1336*/ {IDS_5SEC                                 ," 5 s"},
	/*1337*/ {IDS_10SEC                                ,"10 s"},
	/*1338*/ {IDS_30SEC                                ,"30 s"},
	/*1339*/ {IDS_60SEC                                ,"60 s"},
	/*1340*/ {IDS_ALWAYSON                             ,"Immer an"},
	/*1341*/ {IDS_OFF                                  ,"Aus"},
	/*1342*/ {IDS_DIM                                  ,"Mittel"},
	/*1343*/ {IDS_BRIGHT                               ,"Hell"},
	/*1344*/ {IDS_LANGUAGE                             ,"Sprache"},
	/*1345*/ {IDS_RESETPROMPTING                       ,"Reset bestätigen"},
	/*1346*/ {IDS_RESETPROMPT                          ,"Reset?"},
	/*1347*/ {IDS_DECIMALSYMBOL                        ,"Dezimalsymbol"},
	/*1348*/ {IDS_DATEFORMAT                           ,"Datumsformat"},
	/*1349*/ {IDS_SYNCPC                               ,"Sync. Datum/Uhrzeit mit PC"},
	/*1350*/ {IDS_TAKTENABLED                          ,"Taktmaximalpegel"},
	/*1351*/ {IDS_COMMA                                ,"Komma (,)"},
	/*1352*/ {IDS_PERIOD                               ,"Punkt (.)"},
	/*1353*/ {IDS_DDMMMYYYY                            ,"T-M-J"},
	/*1354*/ {IDS_YYYYMMMDD                            ,"J-M-T"},
	/*1355*/ {IDS_V                                    ,"V"},
	/*1356*/ {IDS_ESTRUNTIME                           ,"Batteriebetrieb ca."},
	/*1357*/ {IDS_BATTVOLTAGE                          ,"Batteriespannung"},
	/*1358*/ {IDS_TITLE_POWERCONTROL                   ,"Spannungsversorgung"},
	/*1359*/ {IDS_TEMPERATUREINT                       ,"Temp.(intern)"},
	/*1360*/ {IDS_DEGREEF                              ,"°F"},
	/*1361*/ {IDS_DEGREEC                              ,"°C"},
	/*1362*/ {IDS_LOCKMODE                             ,"Sperrmodus"},
	/*1363*/ {IDS_ALLOWCALWHENLOCKED                   ,"Kalibrierung, wenn gesperrt"},
	/*1364*/ {IDS_LOCKCODE                             ,"Endsperr-Code"},
	/*1365*/ {IDS_UNLOCKED                             ,"Endsperrt"},
	/*1366*/ {IDS_LOCKAUTOSTORE                        ,"Gesperrt - autm.Sp."},
	/*1367*/ {IDS_LOCKMANUAL                           ,"Gesperrt - man.Sp."},
	/*1368*/ {IDS_FULLYLOCKED                          ,"Komplett gesperrt"},
	/*1369*/ {IDS_POWERCONTROLNAV                      ,"Aus,Schließen,Setup"},
	/*1370*/ {IDS_SYSDATE                              ,"Systemdatum"},
	/*1371*/ {IDS_SYSTIME                              ,"Systemuhrzeit"},
	/*1372*/ {IDS_JAN                                  ,"Jan"},
	/*1373*/ {IDS_FEB                                  ,"Feb"},
	/*1374*/ {IDS_MAR                                  ,"Mär"},
	/*1375*/ {IDS_APR                                  ,"Apr"},
	/*1376*/ {IDS_MAY                                  ,"Mai"},
	/*1377*/ {IDS_JUN                                  ,"Jun"},
	/*1378*/ {IDS_JUL                                  ,"Jul"},
	/*1379*/ {IDS_AUG                                  ,"Aug"},
	/*1380*/ {IDS_SEP                                  ,"Sep"},
	/*1381*/ {IDS_OCT                                  ,"Okt"},
	/*1382*/ {IDS_NOV                                  ,"Nov"},
	/*1383*/ {IDS_DEC                                  ,"Dez"},
	/*1384*/ {IDS_AUTOSTOREMODE                        ,"Autom. Speichern"},
	/*1385*/ {IDS_AS_NONE                              ,"Nein"},
	/*1386*/ {IDS_AS_PROMPT                            ,"Sofort"},
	/*1387*/ {IDS_AS_STORE                             ,"Speichern"},
	/*1388*/ {IDS_YES                                  ,"Ja "},
	/*1389*/ {IDS_NO                                   ,"Nein"},
	/*1390*/ {IDS_OK                                   ,"OK"},
	/*1391*/ {IDS_CANCEL                               ,"Abbrechen"},
	/*1392*/ {IDS_SAVE                                 ,"Speichern"},
	/*1393*/ {IDS_SAVEAS                               ,"Speichern als"},
	/*1394*/ {IDS_SETTINGS                             ,"Einstellungen"},
	/*1395*/ {IDS_APPLYCHANGES                         ,"Aenderungen uebernehmen?"},
	/*1396*/ {IDS_HISTORY                              ,"Historie"},
	/*1397*/ {IDS_PERFORMED                            ,"Ausgefuehrt:"},
	/*1398*/ {IDS_DUE                                  ,"Faellig:"},
	/*1399*/ {IDS_CERTIFICATION                        ,"Zertifizierung"},
	/*1400*/ {IDS_INTERVAL                             ,"Intervall"},
	/*1401*/ {IDS_REMINDER                             ,"Erinnerung"},
	/*1402*/ {IDS_15DAYS                               ,"15 Tage"},
	/*1403*/ {IDS_30DAYS                               ,"30 Tage"},
	/*1404*/ {IDS_45DAYS                               ,"45 Tage"},
	/*1405*/ {IDS_60DAYS                               ,"60 Tage"},
	/*1406*/ {IDS_1YEAR                                ,"1 Jahr"},
	/*1407*/ {IDS_2YEAR                                ,"2 Jahre"},
	/*1408*/ {IDS_3YEAR                                ,"3 Jahre"},
	/*1409*/ {IDS_4YEAR                                ,"4 Jahre"},
	/*1410*/ {IDS_DESCRIPTION                          ,"Beschreibung"},
	/*1411*/ {IDS_HZ                                   ,"Hz"},
	/*1412*/ {IDS_CALIBRATOR                           ,"Kalibrator"},
	/*1413*/ {IDS_CALIBRATING                          ,"Kalibrierung"},
	/*1414*/ {IDS_TITLE_DATAVIEWER                     ,"Ergebnisse Anzeigen"},
	/*1415*/ {IDS_TABSDATAVIEWER1                      ,"Daten"},
	/*1416*/ {IDS_TABSDATAVIEWER2                      ,"Doku"},
	/*1417*/ {IDS_LEVEL1                               ,"Pegel 1"},
	/*1418*/ {IDS_LEVEL2                               ,"Pegel 2"},
	/*1419*/ {IDS_SPLTRIGGER                           ,"Trigger Pegel"},
	/*1420*/ {IDS_LEVEL                                ,"Pegel"},
	/*1421*/ {IDS_UNLOCKPROMPT                         ,"Geben Sie 4 Zeichen ein"},
	/*1422*/ {IDS_UNLOCK                               ,"Entsperren"},
	/*1423*/ {IDS_LOCKED1                              ,"Dieses Geraet ist "},
	/*1424*/ {IDS_LOCKED2                              ,"GESPERRT"},
	/*1425*/ {IDS_LOCKED3                              ,"Taste Tools druecken zum"},
	/*1426*/ {IDS_LOCKED4                              ,"ENTSPERREN"},
	/*1427*/ {IDS_INVALIDCODE                          ,"Falsche Eingabe"},
	/*1428*/ {IDS_CAL                                  ,"Kal."},
	/*1429*/ {IDS_RUN                                  ,"Start"},
	/*1430*/ {IDS_CONFIRM                              ,"Sind Sie sicher?"},
	/*1431*/ {IDS_WARNING                              ,"Warnung!"},
	/*1432*/ {IDS_CERTEXPIRING1                        ,"Werkskalibrierung erlischt in"},
	/*1433*/ {IDS_CERTEXPIRING2                        ,"Tagen"},
	/*1434*/ {IDS_CERTEXPIRED                          ,"Werkskalibrierung ist nicht mehr gueltig!"},
	/*1435*/ {IDS_RESETREQ                             ,"Reset ist notwendig"},
	/*1436*/ {IDS_STOPREQ                              ,"Stop ist notwendig"},
	/*1437*/ {IDS_SAVEFILE                             ,"Daten speichern?"},
	/*1438*/ {IDS_BROWSE                               ,"Blaettern"},
	/*1439*/ {IDS_FILELIST                             ,"Daten"},
	/*1440*/ {IDS_CONTEXTMENU                          ,"Menue"},
	/*1441*/ {IDS_MEASUREMENTOK                        ,"Messung ok?"},
	/*1442*/ {IDS_CALFAILED                            ,"Kalibrierung fehlgeschlagen."},
	/*1443*/ {IDS_SAVECAL                              ,"Ergebnis speichern?"},
	/*1444*/ {IDS_RECORD                               ,"Start"},
	/*1445*/ {IDS_PLAYBACK                             ,"Abspielen"},
	/*1446*/ {IDS_SAVERECORDING                        ,"Aufnahme speichern?"},
	/*1447*/ {IDS_STOP                                 ,"Stop"},
	/*1448*/ {IDS_DENAVBUTTONS                         ,"Seite,Schliessen,Menue"},
	/*1449*/ {IDS_VIEW                                 ,"Ansicht"},
	/*1450*/ {IDS_DELETE                               ,"Loeschen"},
	/*1451*/ {IDS_RENAME                               ,"Umbenennen"},
	/*1452*/ {IDS_REFRESH                              ,"Liste aktualisieren"},
	/*1453*/ {IDS_LOADSETTINGS                         ,"Einstellungen laden"},
	/*1454*/ {IDS_RENAMEFILE                           ,"File umbenennen?"},
	/*1455*/ {IDS_DELETEFILE                           ,"File loeschen?"},
	/*1456*/ {IDS_OVERWRITEFILE                        ,"File ueberschreiben?"},
	/*1457*/ {IDS_BATTERYTYPE                          ,"Batterietyp"},
	/*1458*/ {IDS_ALKALINE                             ,"Alkali"},
	/*1459*/ {IDS_NIMH                                 ,"NiMH"},
	/*1460*/ {IDS_MEASUREMENT                          ,"Messung"},
	/*1461*/ {IDS_PAUSE                                ,"Pause"},
	/*1462*/ {IDS_RESUME                               ,"Wiederaufnahme"},
	/*1463*/ {IDS_VOICE                                ,"Sprache"},
	/*1464*/ {IDS_SOUND                                ,"Sound"},
	/*1465*/ {IDS_KEY                                  ,"Tastendruck"},
	/*1466*/ {IDS_IO                                   ,"IO- Befehl"},
	/*1467*/ {IDS_TIMER                                ,"Timer"},
	/*1468*/ {IDS_POWER                                ,"Spannungsversorgung"},
	/*1469*/ {IDS_OUTOFMEMORY                          ,"Zu wenig Speicher"},
	/*1470*/ {IDS_COULDNTSAVE                          ,"Speichern nicht möglich"},
	/*1471*/ {IDS_ERROR                                ,"Fehler"},
	/*1472*/ {IDS_FIRMWAREREV                          ,"Firmware Vers:"},
	/*1473*/ {IDS_THIRDOCTAVE                          ,"Terzspektrum"},
	/*1474*/ {IDS_PREAMP_CONNECT                       ,"Vorverst. angeschlossen"},
	/*1475*/ {IDS_PREAMP_DISCONNECT                    ,"Vorverst. nicht angeschlossen"},
	/*1476*/ {IDS_JACKFUNC                             ,"Steckerfunktion"},
	/*1477*/ {IDS_JACKFUNC_ACDC                        ,"AC/DC"},
	/*1478*/ {IDS_JACKFUNC_HEADSET                     ,"Kopfhoerer"},
	/*1479*/ {IDS_SETTIME                              ,"Einstellen"},
	/*1480*/ {IDS_UNLOCK1                              ,"Geben Sie 4 Zeichen ein um"},
	/*1481*/ {IDS_UNLOCK2                              ,"Geraet zu entsperren."},
	/*1482*/ {IDS_UNAVAILABLE                          ,"Diese Einstellung ist\naktuell nicht moeglich."},
	/*1483*/ {IDS_TIMESET                              ,"Uhrzeit ist eingestellt"},
	/*1484*/ {IDS_SHUTDOWN_IMMINENT                    ,"Niedrige Batterispannung!\nGeraet schaltet ab!\nMessung speichern!"},
	/*1485*/ {IDS_INSTINFO                             ,"Geraeteinformation"},
	/*1486*/ {IDS_PREAMPTYPE                           ,"Vorverst.:"},
	/*1487*/ {IDS_STANDARDSINFO1                       ,"Dieses Geraet erfuellt"},
	/*1488*/ {IDS_STANDARDSINFO2                       ,"folgende Normen:"},
	/*1489*/ {IDS_OPTIONNAME                           ,"Optionen"},
	/*1490*/ {IDS_SETTINGSLOCKED                       ,"Einstellungen über PC.\nFortfahren?"},
	/*1491*/ {IDS_CP_SYSUTILS                          ,"System\nUtilities"},
	/*1492*/ {IDS_FSERRCORRECTED                       ,"Fehler auf Datentraeger\ngefunden und repariert."},
	/*1493*/ {IDS_FSERRNOTCORRECTED                    ,"Datentraeger beschaedigt.\nSystem formatieren?"},
	/*1494*/ {IDS_TITLE_SYSUTIL                        ,"System Utilities"},
	/*1495*/ {IDS_TABSYSUTIL1                          ,"Datentraeger"},
	/*1496*/ {IDS_CHECK                                ,"Daten pruefen"},
	/*1497*/ {IDS_FORMAT                               ,"Format"},
	/*1498*/ {IDS_FORMATALL                            ,"Werkseinstellungen"},
	/*1499*/ {IDS_DSPREV                               ,"DSP Vers:"},
	/*1500*/ {IDS_DELETEALLINTERNAL                    ,"Alle Files loeschen"},
	/*1501*/ {IDS_CONFIRMDELETEALL                     ,"Alle Daten loeschen?"},
	/*1502*/ {IDS_NOERRORS                             ,"Keine Fehler\ngefunden."},
	/*1503*/ {IDS_OBABANDWIDTH                         ,"Bandbreite"},
	/*1504*/ {IDS_FULLTHIRDOCTAVE                      ,"Terz- und Oktavsp."},
	/*1505*/ {IDS_INCOMPATIBLEBOOTLOADER               ,"Bootsoftware inkompatibel.\nKontaktieren Sie Larson Davis"},
	/*1506*/ {IDS_TABCURRENT                           ,"Aktuell"},
	/*1507*/ {IDS_TABMEASUREMENT                       ,"Messung"},
	/*1508*/ {IDS_TABTIMEHISTORY                       ,"Zeitverlauf"},
	/*1509*/ {IDS_TABEVENTS                            ,"Ereignisse"},
	/*1510*/ {IDS_MARKSOUNDTYPE                        ,"Geraeuschart"},
	/*1511*/ {IDS_VIEWNORMALIZED                       ,"Genormte Ansicht"},
	/*1512*/ {IDS_OVERLOADS                            ,"Uebersteuerung"},
	/*1513*/ {IDS_LDN                                  ,"LDN"},
	/*1514*/ {IDS_LDEN                                 ,"LDEN"},
	/*1515*/ {IDS_TAKT                                 ,"LAFTM5"},
	/*1516*/ {IDS_COMMUNITYNOISE                       ,"Umgebungslaerm"},
	/*1517*/ {IDS_LINKTIMEHISTORY                      ,"Link - Zeitverlauf"},
	/*1518*/ {IDS_RECORDNUM                            ,"Aufzeichnung"},
	/*1519*/ {IDS_LINKMEASUREMENTHISTORY1              ,"Link - Messung"},
	/*1520*/ {IDS_LINKMEASUREMENTHISTORY               ,"Link - Doku"},
	/*1521*/ {IDS_SAMPLENUM                            ,"Beispiel"},
	/*1522*/ {IDS_NUMMEASUREMENTS                      ,"Messungen"},
	/*1523*/ {IDS_NUMEXCEEDANCES                       ,"Ereignisse"},
	/*1524*/ {IDS_NUMTIMEHISTORIES                     ,"Doku"},
	/*1525*/ {IDS_ENTERBYFREQ                          ,"Eingabe -> Frequenz"},
	/*1526*/ {IDS_ENTERBYTIME                          ,"Eingabe -> Zeit"},
	/*1527*/ {IDS_PEAKTRIGGER2                         ,"Peak 2"},
	/*1528*/ {IDS_PEAKTRIGGER3                         ,"Peak 3"},
	/*1529*/ {IDS_DYNTRIGGEROFFSET                     ,"Dynamischer Trig. Offset"},
	/*1530*/ {IDS_DYNAMICRESPONSE                      ,"Dynamischer Rücklauf"},
	/*1531*/ {IDS_ATMAX                                ,"At Lmax"},
	/*1532*/ {IDS_BINMAX                               ,"Bin max"},
	/*1533*/ {IDS_OBAMAXMODE                           ,"Max Spektr."},
	/*1534*/ {IDS_ENABLEMSMTHISTORY                    ,"Doku Messungen aktiviert"},
	/*1535*/ {IDS_MEASUREMENTCOUNTER                   ,"Zaehler Messungen"},
	/*1536*/ {IDS_CONTINUOUS                           ,"Fortlaufend"},
	/*1537*/ {IDS_SINGLEBLOCK                          ,"Einzelmessung"},
	/*1538*/ {IDS_DAILYTIMER                           ,"Tägliche Messung"},
	/*1539*/ {IDS_RUNMODE                              ,"Modus"},
	/*1540*/ {IDS_MEASUREMENTTIME                      ,"Messdauer"},
	/*1541*/ {IDS_CLOCKSYNC                            ,"Sync. Uhrzeit"},
	/*1542*/ {IDS_DAILYAUTOSTORE                       ,"Autom. Speichern"},
	/*1543*/ {IDS_AUTOSTORETIME                        ,"Uhrzeit"},
	/*1544*/ {IDS_AUTOCALCHECK                         ,"Kal-Check"},
	/*1545*/ {IDS_AUTOCALCHECKTIME                     ,"Kal-Check Zeit"},
	/*1546*/ {IDS_DAILY                                ,"Taeglich"},
	/*1547*/ {IDS_TABEXCEEDANCEHISTORY                 ,"Ereignisverlauf"},
	/*1548*/ {IDS_TABMARKER                            ,"Marker"},
	/*1549*/ {IDS_ENABLETIMEHISTORY                    ,"Zeitverlauf aktivieren"},
	/*1550*/ {IDS_PERIOD1                              ,"Periode"},
	/*1551*/ {IDS_100PS                                ," 10 ms"},
	/*1552*/ {IDS_50PS                                 ," 20 ms"},
	/*1553*/ {IDS_20PS                                 ," 50 ms"},
	/*1554*/ {IDS_10PS                                 ,"100 ms"},
	/*1555*/ {IDS_5PS                                  ,"200 ms"},
	/*1556*/ {IDS_2PS                                  ,"500 ms"},
	/*1557*/ {IDS_1S                                   ," 1 s"},
	/*1558*/ {IDS_2S                                   ," 2 s"},
	/*1559*/ {IDS_5S                                   ," 5 s"},
	/*1560*/ {IDS_10S                                  ,"10 s"},
	/*1561*/ {IDS_15S                                  ,"15 s"},
	/*1562*/ {IDS_20S                                  ,"20 s"},
	/*1563*/ {IDS_30S                                  ,"30 s"},
	/*1564*/ {IDS_1MIN                                 ," 1 m"},
	/*1565*/ {IDS_2MIN                                 ," 2 m"},
	/*1566*/ {IDS_15MIN                                ,"15 m"},
	/*1567*/ {IDS_20MIN                                ,"20 m"},
	/*1568*/ {IDS_1HR                                  ,"  1 h"},
	/*1569*/ {IDS_24HR                                 ,"24 h"},
	/*1570*/ {IDS_LTWA1                                ,"Ltwa1"},
	/*1571*/ {IDS_LTWA2                                ,"Ltwa2"},
	/*1572*/ {IDS_LTWA3                                ,"Ltwa3"},
	/*1573*/ {IDS_LTWA4                                ,"Ltwa4"},
	/*1574*/ {IDS_LPEAK                                ,"Lpeak"},
	/*1575*/ {IDS_LTM5                                 ,"LAFTM5"},
	/*1576*/ {IDS_OBALEQ                               ,"Leq Spektrum"},
	/*1577*/ {IDS_OBALMAX                              ,"Lmax Spektrum"},
	/*1578*/ {IDS_OBALMIN                              ,"Lmin Spektrum"},
	/*1579*/ {IDS_2102HUMIDITY                         ,"Vorverst. Luftfeuchtigkeit"},
	/*1580*/ {IDS_2102TEMPERATURE                      ,"Vorverst. Temp."},
	/*1581*/ {IDS_THOPTIONS                            ,"Optionen Zeitverlauf"},
	/*1582*/ {IDS_TRIGGER_LEVEL                        ,"Triggerpegel"},
	/*1583*/ {IDS_TRIGGER_RISE_FALL                    ,"10dB Anstieg/Abfall"},
	/*1584*/ {IDS_TRIGGER_DYNAMIC                      ,"Dynamik"},
	/*1585*/ {IDS_ENABLEEXCDHISTORY                    ,"Ereignisverlauf"},
	/*1586*/ {IDS_MINIMUMDURATION                      ,"Minimale Dauer"},
	/*1587*/ {IDS_CONTPERIOD                           ,"Fortlauf. Periode"},
	/*1588*/ {IDS_TRIGGERMETHOD                        ,"Trig. Methode"},
	/*1589*/ {IDS_ENABLEEXCDTH                         ,"Ereignis-Zeitverlauf"},
	/*1590*/ {IDS_EXCDTHPERIOD                         ,"Periode"},
	/*1591*/ {IDS_ENABLEEXCDSPECTH                     ,"Spektrum"},
	/*1592*/ {IDS_SEC                                  ,"s"},
	/*1593*/ {IDS_VIEW15                               ,"1-5"},
	/*1594*/ {IDS_VIEW610                              ,"6-10"},
	/*1595*/ {IDS_PREREC                               ,"Pre-Trigger-Zeit"},
	/*1596*/ {IDS_RECPERIOD                            ,"Aufnahmezeit"},
	/*1597*/ {IDS_RECORDENABLE                         ,"Aufnahme"},
	/*1598*/ {IDS_TABDAYNIGHT                          ,"Tag/Nacht"},
	/*1599*/ {IDS_TABAUDIO                             ,"Sound"},
	/*1600*/ {IDS_DAY                                  ,"Tag"},
	/*1601*/ {IDS_EVENING                              ,"Abend"},
	/*1602*/ {IDS_NIGHT                                ,"Nacht"},
	/*1603*/ {IDS_PENALTY                              ,"Zuschlag"},
	/*1604*/ {IDS_EXCDAUDIO                            ,"Ereignis Sound Rek."},
	/*1605*/ {IDS_SAVESNAPSHOT                         ,"Schnappschuss speichern"},
	/*1606*/ {IDS_SNAPSHOTPERIOD                       ,"Dauer Schnappschusss"},
	/*1607*/ {IDS_PRETRIGGERPERIOD                     ,"Pre-Trigger Zeit"},
	/*1608*/ {IDS_MSMTAUDIO                            ,"Audio Messung"},
	/*1609*/ {IDS_LEQA                                 ,"LAeq"},
	/*1610*/ {IDS_LPEAKA                               ,"LApeak"},
	/*1611*/ {IDS_LPEAKAMAX                            ,"LApeak(max)"},
	/*1612*/ {IDS_SLOWLMAXA                            ,"LASmax"},
	/*1613*/ {IDS_FASTLMAXA                            ,"LAFmax"},
	/*1614*/ {IDS_IMPLMAXA                             ,"LAImax"},
	/*1615*/ {IDS_SLOWLMINA                            ,"LASmin"},
	/*1616*/ {IDS_FASTLMINA                            ,"LAFmin"},
	/*1617*/ {IDS_IMPLMINA                             ,"LAImin"},
	/*1618*/ {IDS_LEQC                                 ,"LCeq"},
	/*1619*/ {IDS_LPEAKC                               ,"LCpeak"},
	/*1620*/ {IDS_LPEAKCMAX                            ,"LCpeak(max)"},
	/*1621*/ {IDS_SLOWLMAXC                            ,"LCSmax"},
	/*1622*/ {IDS_FASTLMAXC                            ,"LCFmax"},
	/*1623*/ {IDS_IMPLMAXC                             ,"LCImax"},
	/*1624*/ {IDS_SLOWLMINC                            ,"LCSmin"},
	/*1625*/ {IDS_FASTLMINC                            ,"LCFmin"},
	/*1626*/ {IDS_IMPLMINC                             ,"LCImin"},
	/*1627*/ {IDS_LEQZ                                 ,"LZeq"},
	/*1628*/ {IDS_LPEAKZ                               ,"LZpeak"},
	/*1629*/ {IDS_LPEAKZMAX                            ,"LZpeak(max)"},
	/*1630*/ {IDS_SLOWLMAXZ                            ,"LZSmax"},
	/*1631*/ {IDS_FASTLMAXZ                            ,"LZFmax"},
	/*1632*/ {IDS_IMPLMAXZ                             ,"LZImax"},
	/*1633*/ {IDS_SLOWLMINZ                            ,"LZSmin"},
	/*1634*/ {IDS_FASTLMINZ                            ,"LZFmin"},
	/*1635*/ {IDS_IMPLMINZ                             ,"LZImin"},
	/*1636*/ {IDS_EXTPOWER                             ,"Externe Stromversorgung"},
	/*1637*/ {IDS_INTTEMP                              ,"Temp. (intern)"},
	/*1638*/ {IDS_WINDSPD                              ,"Windgeschwindigkeit"},
	/*1639*/ {IDS_ADC1AVG                              ,"ADC1 Avg."},
	/*1640*/ {IDS_ADC2AVG                              ,"ADC2 Avg."},
	/*1641*/ {IDS_OBALEQ11                             ,"Oktav Leq"},
	/*1642*/ {IDS_OBAMAX11                             ,"Oktav max"},
	/*1643*/ {IDS_OBAMIN11                             ,"Oktav min"},
	/*1644*/ {IDS_OBALEQ13                             ,"Terz Leq"},
	/*1645*/ {IDS_OBAMAX13                             ,"Terz max"},
	/*1646*/ {IDS_OBAMIN13                             ,"Terz min"},
	/*1647*/ {IDS_ASLOWSPL                             ,"LAS"},
	/*1648*/ {IDS_AFASTSPL                             ,"LAF"},
	/*1649*/ {IDS_AIMPLSPL                             ,"LAI"},
	/*1650*/ {IDS_CSLOWSPL                             ,"LCS"},
	/*1651*/ {IDS_CFASTSPL                             ,"LCF"},
	/*1652*/ {IDS_CIMPLSPL                             ,"LCI"},
	/*1653*/ {IDS_ZSLOWSPL                             ,"LZS"},
	/*1654*/ {IDS_ZFASTSPL                             ,"LZF"},
	/*1655*/ {IDS_ZIMPLSPL                             ,"LZI"},
	/*1656*/ {IDS_OBASPL                               ,"Pegel Spektrum"},
	/*1657*/ {IDS_OBASPL11                             ,"Pegel Oktav"},
	/*1658*/ {IDS_OBASPL13                             ,"Pegel Terz"},
	/*1659*/ {IDS_USBSTORAGE                           ,"USB Speicher"},
	/*1660*/ {IDS_OVERWRITEFILES                       ,"Aelteste Daten ueberschreiben"},
	/*1661*/ {IDS_COMPRESSDATAFILE                     ,"Daten komprimieren"},
	/*1662*/ {IDS_AUTO                                 ,"Auto"},
	/*1663*/ {IDS_ENTERBY11FREQ                        ,"Eingabe -> Oktaven"},
	/*1664*/ {IDS_ENTERBY13FREQ                        ,"Eingabe -> Terzen"},
	/*1665*/ {IDS_NORMALIZED_SPECTRUM                  ,"Normalisiertes Spektrum"},
	/*1666*/ {IDS_NORMALIZEDSPECTRUMNAV                ,"Einstellen, Schliessen, Editieren"},
	/*1667*/ {IDS_MARKSOUNDTYPE1NAV                    ,"Aufnahme, Schliessen, Keine"},
	/*1668*/ {IDS_MARKSOUNDTYPE2NAV                    ,"Stop, Schliessen, Keine"},
	/*1669*/ {IDS_SPL                                  ,"Pegel"},
	/*1670*/ {IDS_REF                                  ,"Ref:"},
	/*1671*/ {IDS_OBAFREQWT                            ,"Frequ. Bew."},
	/*1672*/ {IDS_FILE                                 ,"File"},
	/*1673*/ {IDS_NEGA                                 ,"-A"},
	/*1674*/ {IDS_NEGC                                 ,"-C"},
	/*1675*/ {IDS_EDIT_SPECTRA                         ,"Referenzpektrum einstellen"},
	/*1676*/ {IDS_SAVECHANGES                          ,"Änderungen speichern?"},
	/*1677*/ {IDS_EDITSPECTRUMNAV                      ," ,Schliessen,Re.1kHz"},
	/*1678*/ {IDS_CANTRECORDWHILESTOPPED               ,"Geraet muss zum Aufzeichnen messen."},
	/*1679*/ {IDS_WINDDIR                              ,"Windrichtung"},
	/*1680*/ {IDS_THOPTIONSTURNEDOFF                   ,"Zeitverlauf\nOptionen sind\ndeaktiviert"},
	/*1681*/ {IDS_SOUNDREC                             ,"Soundrekorder"},
	/*1682*/ {IDS_DATALOGGING                          ,"Zeitverlauf"},
	/*1683*/ {IDS_ANYDATA                              ,"Alle Daten"},
	/*1684*/ {IDS_INTERVALS                            ,"Historie"},
	/*1685*/ {IDS_WEATHER                              ,"Wetter"},
	/*1686*/ {IDS_GAIN                                 ,"+20dB Gain"},
	/*1687*/ {IDS_NODATA                               ,"Keine Daten"},
	/*1688*/ {IDS_EXTPOWERED                           ,"Externe Spannungsversorgung"},
	/*1689*/ {IDS_LDAY                                 ,"LTag"},
	/*1690*/ {IDS_LEVENING                             ,"LAbend"},
	/*1691*/ {IDS_LNIGHT                               ,"LNacht"},
	/*1692*/ {IDS_INVALIDDATES                         ,"Ungültige Start/Stop Daten"},
	/*1693*/ {IDS_PLEASEWAIT                           ,"Bitte warten..."},
	/*1694*/ {IDS_PARTIAL                              ,"partiell"},
	/*1695*/ {IDS_TIMERSLOST                           ,"Taegl. Zeitgeber\niaktiv.\nFortfahren?"},
	/*1696*/ {IDS_LTWA                                 ,"LTWA"},
	/*1697*/ {IDS_LOWMEMSTOP                           ,"Zu wenig Speicherplatz!\nLD831 wurde angehalten."},
	/*1698*/ {IDS_SETTINGSMAYCHANGE                    ,"Geaenderte Einstellung\nwegen Zeit/Historie\nIntervall."},
	/*1699*/ {IDS_PREAMP_DISPLAY                       ,"Vorverst. Interface"},
	/*1700*/ {IDS_TABSSYSPROP5                         ,"Displays"},
	/*1701*/ {IDS_TABS                                 ,"Tabs"},
	/*1702*/ {IDS_PAGES                                ,"Seiten"},
	/*1703*/ {IDS_STARTTAB                             ,"Start"},
	/*1704*/ {IDS_DISP_PROFILE                         ,"Profil"},
	/*1705*/ {IDS_DISP_11                              ,"Oktaven"},
	/*1706*/ {IDS_DISP_13                              ,"Terzen"},
	/*1707*/ {IDS_DISP_TRIGGER                         ,"Trigger"},
	/*1708*/ {IDS_DISP_POWER                           ,"Energieversorgung"},
	/*1709*/ {IDS_DISP_LEQ                             ,"Leq"},
	/*1710*/ {IDS_DISP_DOSE1                           ,"Dosis 1"},
	/*1711*/ {IDS_DISP_DOSE2                           ,"Dosis 2"},
	/*1712*/ {IDS_DISP_SEL                             ,"SEL"},
	/*1713*/ {IDS_DISP_PERCENTILES                     ,"Perzentile"},
	/*1714*/ {IDS_DISP_EXCEEDANCES                     ,"Überschreitungen"},
	/*1715*/ {IDS_DISP_SEA                             ,"SEA"},
	/*1716*/ {IDS_DISP_OVERLOAD                        ,"Uebersteuerung"},
	/*1717*/ {IDS_DISP_MEMORY                          ,"Speicher"},
	/*1718*/ {IDS_DISP_COMMUNITY                       ,"Umgebungslaerm"},
	/*1719*/ {IDS_DISP_MISC                            ,"Sonstiges"},
	/*1720*/ {IDS_DISP_HISTORY                         ,"Historie"},
	/*1721*/ {IDS_DISP_METRICS                         ,"Metrik"},
	/*1722*/ {IDS_DISP_TIMEHISTORY                     ,"Zeitverlauf"},
	/*1723*/ {IDS_DISP_SPECTRAL_TIMEHISTORY            ,"Spektrum Zeitverlauf"},
	/*1724*/ {IDS_NODISPLAYENABLED                     ," Mindestens eine Seite \n muß aktiviert sein. "},
	/*1725*/ {IDS_GRAPHSETTINGS                        ,"Skalierung"},
	/*1726*/ {IDS_GRAPHHEIGHT                          ,"Maximum"},
	/*1727*/ {IDS_GRAPHBOTTOM                          ,"Minimum"},
	/*1728*/ {IDS_CLOSEWND                             ,"'Enter' zum schliessen."},
	/*1729*/ {IDS_SETUPMANAGER                         ," Setup- \n Verwaltung "},
	/*1730*/ {IDS_COULDNTLOAD                          ,"File kann nicht \ngeladen werden."},
	/*1731*/ {IDS_TABWEATHER                           ,"Wetter"},
	/*1732*/ {IDS_COMPASS                              ,"Kompass"},
	/*1733*/ {IDS_DEGREES                              ,"Grad"},
	/*1734*/ {IDS_PERCENT_TEXT                         ,"Prozent"},
	/*1735*/ {IDS_VOLTS                                ,"Volt"},
	/*1736*/ {IDS_SCALE                                ,"Skala"},
	/*1737*/ {IDS_UNITS                                ,"Einheiten"},
	/*1738*/ {IDS_OFFSET                               ,"Offset"},
	/*1739*/ {IDS_WINDTHRESHOLD                        ,"Schwellenwert"},
	/*1740*/ {IDS_WINDEXCDLEVEL                        ,"Ueberschreitungspegel"},
	/*1741*/ {IDS_WINDHYSTERESIS                       ,"Hysterese"},
	/*1742*/ {IDS_WINDPAUSE                            ,"Pause"},
	/*1743*/ {IDS_WIND                                 ,"Wind"},
	/*1744*/ {IDS_HIGH                                 ,"Hoch"},
	/*1745*/ {IDS_DESC                                 ,"Beschr."},
	/*1746*/ {IDS_COULDNTSAVEUSB                       ,"Speicherung der Daten auf\nUSB-Medium nicht moeglich."},
	/*1747*/ {IDS_SAVETOUSB                            ,"Auf USB speichern"},
	/*1748*/ {IDS_WINDY                                ,"Windig"},
	/*1749*/ {IDS_AVG                                  ,"Durchschnitt"},
	/*1750*/ {IDS_GUST                                 ,"Boee"},
	/*1751*/ {IDS_GUSTSPEED                            ,"v- Boee"},
	/*1752*/ {IDS_ADC1MAX                              ,"ADC1 Max"},
	/*1753*/ {IDS_ADC1MIN                              ,"ADC1 Min"},
	/*1754*/ {IDS_ADC2MAX                              ,"ADC2 Max"},
	/*1755*/ {IDS_ADC2MIN                              ,"ADC2 Min"},
	/*1756*/ {IDS_LAE                                  ,"LAE"},
	/*1757*/ {IDS_LCE                                  ,"LCE"},
	/*1758*/ {IDS_LZE                                  ,"LZE"},
	/*1759*/ {IDS_OPT_DOSE                             ,"Arbeitsschutz"},
	/*1760*/ {IDS_SPECLNMODE                           ,"Ln Modus"},
	/*1761*/ {IDS_SPECTRAL_LN                          ,"Spektral Ln"},
	/*1762*/ {IDS_PEAK                                 ,"Peak"},
	/*1763*/ {IDS_SPL_S                                ,"SPL S"},
	/*1764*/ {IDS_SPL_F                                ,"SPL F"},
	/*1765*/ {IDS_SPL_I                                ,"SPL I"},
	/*1766*/ {IDS_MAX_S                                ,"Max S"},
	/*1767*/ {IDS_MAX_F                                ,"Max F"},
	/*1768*/ {IDS_MAX_I                                ,"Max I"},
	/*1769*/ {IDS_MIN_S                                ,"Min S"},
	/*1770*/ {IDS_MIN_F                                ,"Min F"},
	/*1771*/ {IDS_MIN_I                                ,"Min I"},
	/*1772*/ {IDS_OCCURANCE                            ,"Auftreten"},
	/*1773*/ {IDS_GPS                                  ,"GPS"},
	/*1774*/ {IDS_COMMUNICATION                        ,"Kommunikation"},
	/*1775*/ {IDS_WIRELESS                             ,"Drahtlos"},
	/*1776*/ {IDS_MODEM                                ,"Modem"},
	/*1777*/ {IDS_EXCD                                 ,"Überschreitung"},
	/*1778*/ {IDS_ALARM                                ,"Alarm"},
	/*1779*/ {IDS_BOTH                                 ,"Beide"},
	/*1780*/ {IDS_DIALOUT                              ,"Einst. Auswahl"},
	/*1781*/ {IDS_MONITORNUMBER                        ,"Monitor #"},
	/*1782*/ {IDS_PHONENUMBER                          ,"Telefon #"},
	/*1783*/ {IDS_MODEMPASSWORD                        ,"Passwort"},
	/*1784*/ {IDS_INITSTRING                           ,"Init String"},
	/*1785*/ {IDS_ON                                   ,"An"},
	/*1786*/ {IDS_NONE                                 ,"Kein"},
	/*1787*/ {IDS_PRETRIGGER                           ,"Pre-Trigger"},
	/*1788*/ {IDS_MAX_SAMPLES                          ,"Max. Samples"},
	/*1789*/ {IDS_LATITUDE                             ,"Breitengrad"},
	/*1790*/ {IDS_LONGITUDE                            ,"Laengengrad"},
	/*1791*/ {IDS_ELEVATION                            ,"Hoehe (NN)"},
	/*1792*/ {IDS_GPSTIME                              ,"Erfasst um"},
	/*1793*/ {IDS_FEET                                 ,"Fuss"},
	/*1794*/ {IDS_METERS                               ,"Meter"},
	/*1795*/ {IDS_LOCALIZATION                         ,"Standort"},
	/*1796*/ {IDS_GPSMODE                              ,"GPS Modus"},
	/*1797*/ {IDS_GPSSYNC                              ,"GPS synchronisiert"},
	/*1798*/ {IDS_GPSNOSYNC                            ,"GPS nicht synchronisiert"},
	/*1799*/ {IDS_WIRELESS_MODEM                       ,"Modem drahtlos"},
	/*1800*/ {IDS_APN                                  ,"APN"},
	/*1801*/ {IDS_APNUSERNAME                          ,"APN Anwendername"},
	/*1802*/ {IDS_APNPASSWORD                          ,"APN Passwort"},
	/*1803*/ {IDS_UNITSSI                              ,"SI"},
	/*1804*/ {IDS_UNITSENGLISH                         ,"Englisch"},
	/*1805*/ {IDS_RICORRECTION                         ,"Mik.- Korrektur"},
	/*1806*/ {IDS_RI2FF                                ,"RI -> FF"},
	/*1807*/ {IDS_FF2RI                                ,"FF -> RI"},
	/*1808*/ {IDS_ENTERCHANGEREC                       ,"Enter->Zeitverlauf"},
	/*1809*/ {IDS_ENTERCHANGEMETRICS                   ,"Enter->Metrik aendern"},
	/*1810*/ {IDS_ENTERCHANGEEVENT                     ,"Enter->Ereignis aendern"},
	/*1811*/ {IDS_ENTERCHANGEFREQ                      ,"Enter->Frequenz aendern"},
	/*1812*/ {IDS_EVENT                                ,"Ereignis"},
	/*1813*/ {IDS_DELETEALLUSB                         ,"USB vollstaendig\nloeschen."},
	/*1814*/ {IDS_RANGE                                ,"Bereich"},
	/*1815*/ {IDS_IMPROPERSHUTDOWN                     ,"Fehler beim Abschalten!"},
	/*1816*/ {IDS_RESETDATA                            ,"Daten werden geloescht.\nDaten sichern?"},
	/*1817*/ {IDS_EDIT                                 ,"Bearb."},
	/*1818*/ {IDS_GPSGLOBALPOSITION                    ,"GPS Global Position"},
	/*1819*/ {IDS_COULDNTDELETE                        ,"File loeschen nicht moeglich."},
	/*1820*/ {IDS_USBHOSTPORT                          ,"USB Host Port"},
	/*1821*/ {IDS_OPEN                                 ,"Offen"},
	/*1822*/ {IDS_USBHOSTPORTTURNEDOFF                 ,"USB Host Port\nwurde deaktiviert."},
	/*1823*/ {IDS_TIMEZONECORR                         ,"Zeitzone (h:m)"},
	/*1824*/ {IDS_CANNOTOVERWRITESYSFILE               ,"System Files können\nnicht ueberschrieben werden."},
	/*1825*/ {IDS_FILEINUSE_PC                         ,"Die Files werden vom\nPC verwendet."},
	/*1826*/ {IDS_OBALASEQ                             ,"L$#eq"},
	/*1827*/ {IDS_OBALASMAX                            ,"L$#max"},
	/*1828*/ {IDS_OBALASMIN                            ,"L$#min"},
	/*1829*/ {IDS_OBALAS                               ,"L$#"},
	/*1830*/ {IDS_HM                                   ,"hh:mm"},
	/*1831*/ {IDS_INVALIDMSMTTIME                      ,"Ungueltige Zeit.\nZeit muß groesser\nals 1 min sein."},
	/*1832*/ {IDS_CAL_CHECK                            ,"E.A. Pruefung"},
	/*1833*/ {IDS_LOGICIO                              ,"Logic I/O"},
	/*1834*/ {IDS_LOGICIN                              ,"Logic In"},
	/*1835*/ {IDS_LOGICOUT                             ,"Logic Out"},
	/*1836*/ {IDS_LOGICRUNSTATE                        ,"Run Status"},
	/*1837*/ {IDS_LOGICRUNSTOP                         ,"Run/Stop"},
	/*1838*/ {IDS_USBMOVECOMPLETE                      ,"USB Speicherung abgeschlossen."},
	/*1839*/ {IDS_INVALIDTIMES                         ,"Ungueltige Start/Stop Zeiten"},
	/*1840*/ {IDS_MICROPHONE                           ,"Mikrofon"},
	/*1841*/ {IDS_TYPE                                 ,"Typ"},
	/*1842*/ {IDS_SENSITIVITY                          ,"Empfindl."},
	/*1843*/ {IDS_SELFNOISE                            ,"Eigenrauschen"},
	/*1844*/ {IDS_OVERLOADLEVEL                        ,"Ueberschreitungsp."},
	/*1845*/ {IDS_UNDERRANGELEVEL                      ,"Unterschreitungsp."},
	/*1846*/ {IDS_NOISEFLOOR                           ,"Grundrauschen"},
	/*1847*/ {IDS_MVPA                                 ,"mV/Pa"},
	/*1848*/ {IDS_CALOUTOFRANGE                        ,"Kalibrierung ausserhalb\ndes Bereichs.\nSpeichern?"},
	/*1849*/ {IDS_PUBLISHED                            ,"Nominal"},
	/*1850*/ {IDS_INVALIDPERIOD                        ,"Schnappschusszeit muß\ngrößer als die\nminimale Eventlaenge sein."},
	/*1851*/ {IDS_EVENTPTCHANGED                       ,"Event Pre-trigger Zeit\nwurde geaendert.\nWert ungueltig."},
	/*1852*/ {IDS_REMOVEUSBDRIVE                       ,"Sie koennen nun den\nUSB Speicher entfernen."},
	/*1853*/ {IDS_T                                    ,"T:"},
	/*1854*/ {IDS_RH                                   ,"RH:"},
	/*1855*/ {IDS_DEWPOINT                             ,"Taupunkt"},
	/*1856*/ {IDS_OVERLOADIN                           ,"Ueberspannung"},
	/*1857*/ {IDS_MAINSPOWER                           ,"Stromversorgung"},
	/*1858*/ {IDS_CALIBRATOR_ON                        ,"E.A. Kalibrator An"},
	/*1859*/ {IDS_SAMPLERATE                           ,"Abtastrate"},
	/*1860*/ {IDS_USBFILEEXISTS                        ,"Diese Messung ist bereits auf\ndem USB-Speicher vorhanden.\nMessung nicht kopiert."},
	/*1861*/ {IDS_SHORTED                              ,"Gekuerzt"},
	/*1862*/ {IDS_FAULT                                ,"Fehler"},
	/*1863*/ {IDS_USBFILETOOLARGE                      ,"Fehlerhafter USB-Speicherplatz.\nVorgang\nabgebrochen."},
	/*1864*/ {IDS_ENV                                  ,"LxT-ENV"},
	/*1865*/ {IDS_HDRCMINUSA                           ,"C - A"},
	/*1866*/ {IDS_IMPULSIVITY                          ,"Impulshaltigkeit"},
	/*1867*/ {IDS_LIEQ                                 ,"L$Ieq"},
	/*1868*/ {IDS_LACZEQ                               ,"L$eq"},
	/*1869*/ {IDS_LIEQMINUSLEQ                         ,"L$Ieq-L$eq"},
	/*1870*/ {IDS_HSLOG                                ,"Zeitverlauf Fast"},
	/*1871*/ {IDS_LITH                                 ,"Lithium"},
	/*1872*/ {IDS_BACK5S                               ,"Rueck-5s"},
	/*1873*/ {IDS_BACK10S                              ,"Rueck-10s"},
	/*1874*/ {IDS_UNDOBACK                             ,"Rueckgaengig"},
	/*1875*/ {IDS_DUR_FRAC                             ,"Tms"},
	/*1876*/ {IDS_WSLOWSPL                             ,"L$S"},
	/*1877*/ {IDS_WFASTSPL                             ,"L$F"},
	/*1878*/ {IDS_WIMPLSPL                             ,"L$I"},
	/*1879*/ {IDS_DISP_PROFILE_LARGE                   ,"Gesetzliches Messwesen"},
	/*1880*/ {IDS_MS                                   ,"ms"},
	/*1881*/ {IDS_GRAPH_RELATIVE                       ,"Relativer Graph"},
	/*1882*/ {IDS_REF1                                 ,"Ref"},
	/*1883*/ {IDS_NAME1                                ,"Name:"},
	/*1884*/ {IDS_JUMP_TO_TOP                          ,"Zum Anfang"},
	/*1885*/ {IDS_JUMP_TO_BOTTOM                       ,"Zum Ende"},
	/*1886*/ {IDS_CALRANGEDIFF                         ,"Abweichung groesser\nals 0.5dB.\nSpeichern?"},
	/*1887*/ {IDS_DENAVBUTTONS1                        ,"Aktiv,Schließen,Menü"},
	/*1888*/ {IDS_TABS_CAL_CHECK                       ,"E. A. Pruefung"},
	/*1889*/ {IDS_CAL_LEVEL                            ,"E. A. Pegel"},
	/*1890*/ {IDS_STD_CAL_LEVEL                        ,"Standard E. A. Pegel eingeben"},
	/*1891*/ {IDS_TABS_CAL_CHECK_HISTORY               ,"E. A. Historie"},
	/*1892*/ {IDS_THLOCATE                             ,"Suchen"},
	/*1893*/ {IDS_THFIRST                              ,"Erstes"},
	/*1894*/ {IDS_THLAST                               ,"Letztes"},
	/*1895*/ {IDS_THRECNUM                             ,"Messung Nummer"},
	/*1896*/ {IDS_SESSIONLOG                           ,"Messung Log"},
	/*1897*/ {IDS_LAENEW                               ,"L$E"},
	/*1898*/ {IDS_RS232                                ,"RS-232"},
	/*1899*/ {IDS_BAUDRATE                             ,"Baud Rate"},
	/*1900*/ {IDS_B9600                                ,"9600"},
	/*1901*/ {IDS_B19200                               ,"19200"},
	/*1902*/ {IDS_B57600                               ,"57600"},
	/*1903*/ {IDS_B115200                              ,"115200"},
	/*1904*/ {IDS_DLYAUTOSTORENEVER                    ,"Nie"},
	/*1905*/ {IDS_DLYAUTOSTORE1                        ,"1/Tag"},
	/*1906*/ {IDS_DLYAUTOSTORE2                        ,"2/Tag"},
	/*1907*/ {IDS_DLYAUTOSTORE4                        ,"4/Tag"},
	/*1908*/ {IDS_DLYAUTOSTORE6                        ,"6/Tag"},
	/*1909*/ {IDS_DLYAUTOSTORE8                        ,"8/Tag"},
	/*1910*/ {IDS_DLYAUTOSTORE12                       ,"12/Tag"},
	/*1911*/ {IDS_DLYAUTOSTORE24                       ,"24/Tag"},
	/*1912*/ {IDS_FLOWCONTROL                          ,"Flow Control"},
	/*1913*/ {IDS_FCNONE                               ,"Kein"},
	/*1914*/ {IDS_XONXOFF                              ,"Xon/Xoff"},
	/*1915*/ {IDS_HARDWARE                             ,"Hardware"},
	/*1916*/ {IDS_400PS                                ,"2.5 ms"},
	/*1917*/ {IDS_200PS                                ,"  5 ms"},
	/*1918*/ {IDS_FST                                  ,"Zeitverlauf Fast"},
	/*1919*/ {IDS_PREPOSTTRIGGER                       ,"Pre/Post Trigger"},
	/*1920*/ {IDS_NOTIFYUSBMOVE                        ,"Kopieren laeuft\ndennoch ausschalten?"},
	/*1921*/ {IDS_SETTINGSCONFLICT                     ,"Konflikt mit Einstellungen.\nAutomatisch korrigieren?"},
	/*1922*/ {IDS_FSTCONFLICT                          ,"Kann nicht aktiviert werden,\nwenn Fast Zeitverlauf\naktiviert ist."},
	/*1923*/ {IDS_DISP_TRIG_STATUS                     ,"Display Ereign. Trig. Status"},
	/*1924*/ {IDS_CAL_CHECK_SPECTRUM                   ,"E. A. Check Spektrum"},
	/*1925*/ {IDS_CALIBRATE_SPECTRUM                   ,"Kalibrierspektrum"},
	/*1926*/ {IDS_POWERINGOFF                          ,"Ausschalten"},
	/*1927*/ {IDS_FSTOBANOTIFY                         ,"Oktaven\ndeaktiviert."},
	/*1928*/ {IDS_MARK                                 ,"Markierung"},
	/*1929*/ {IDS_GPSTIMESYNC                          ,"Zeitsynchronisierung"},
	/*1930*/ {IDS_DELTAT                               ,"Korrektur"},
	/*1931*/ {IDS_EXCDPAUSE                            ,"Ereign. Pause"},
	/*1932*/ {IDS_ENABLEWEATHER                        ,"Wetter aktivieren"},
	/*1933*/ {IDS_THNOTIFY                             ,"Keine Option gewaehlt.\nZeitverlauf wird\ndeaktiviert"},
	/*1934*/ {IDS_EXTSHUTOFFVOLT                       ,"Externe Spannungsquelle\naus."},
	/*1935*/ {IDS_REPAIRUSB                            ,"USB ueberpruefen und reparieren"},
	/*1936*/ {IDS_USBCHECKSTATUS                       ,"USB ueberprueft\nund\nkorrigiert."},
	/*1937*/ {IDS_USBFILENOMOUNT                       ,"USB Files nicht gefunden."},
	/*1938*/ {IDS_USBNOCHECK                           ,"Kein Prüfung\nwährend Kopiervorgang"},
	/*1939*/ {IDS_USBFORMATSTATUS                      ,"USB Speicher formatiert."},
	/*1940*/ {IDS_FORMATUSB                            ,"USB formatieren"},
	/*1941*/ {IDS_ADV_COMM                             ,"Kommunikation"},
	/*1942*/ {IDS_ANALOG_MODEM                         ,"Analog Modem"},
	/*1943*/ {IDS_PASSWORD                             ,"Passwort"},
	/*1944*/ {IDS_DISP_FREQ11                          ,"Oktav über Frequenz"},
	/*1945*/ {IDS_DISP_FREQ13                          ,"Terz über Frequenz"},
	/*1946*/ {IDS_DISP_TIME11                          ,"Oktav über Zeit"},
	/*1947*/ {IDS_DISP_TIME13                          ,"Terz über Zeit"},
	/*1948*/ {IDS_USBSAVENOTIFY                        ,"Prozess laeuft. \nAktion nicht moeglich"},
	/*1949*/ {IDS_BATTPOWERED                          ,"Batterieversorgung"},
	/*1950*/ {IDS_DISP_SPTH_BYTIME                     ,"Zeitverlauf Spektrum (t)"},
	/*1951*/ {IDS_DAILYTIMERNOTIFY                     ,"Einer oder mehrerer Timer\nüberschneiden sich."},
	/*1952*/ {IDS_INVALIDTIME                          ,"Ungueltige Zeit.\nZeit muß groesser als\n1 Sekunde sein."},
	/*1953*/ {IDS_SAVESETUP                            ,"Aktive Einstellungen veraendern?"},
	/*1954*/ {IDS_STATUS                               ,"Status"},
	/*1955*/ {IDS_CHANNEL                              ,"Kanal"},
	/*1956*/ {IDS_CURSTATE                             ,"Status"},
	/*1957*/ {IDS_PREVSTATE                            ,"Letzte:"},
	/*1958*/ {IDS_IN                                   ,"In:"},
	/*1959*/ {IDS_OUT                                  ,"Out:"},
	/*1960*/ {IDS_TIMEOUT                              ,"Timeout:"},
	/*1961*/ {IDS_USB                                  ,"USB"},
	/*1962*/ {IDS_TIMERSLOST1                          ,"Tagtimer\nwird deaktiviert.\nFortfahren?"},
	/*1963*/ {IDS_USBRMNOTIFY                          ,"Bitte warten bis\nUSB Anwendung stopt."},
	/*1964*/ {IDS_USBCOMMNOTIFY                        ,"Andere Kommunikatation\n wird deaktiviert.\nFortfahren?"},
	/*1965*/ {IDS_CALCHECK                             ,"Kal. pruefen"},
	/*1966*/ {IDS_CALCHANGE                            ,"Kal. aendern"},
	/*1967*/ {IDS_CALIBRATIONCHANGED                   ,"Differenz"},
	/*1968*/ {IDS_CALCHECKDB                           ,"Pegel (dB)"},
	/*1969*/ {IDS_CALCHANGEDB                          ,"Aenderung (dB)"},
	/*1970*/ {IDS_FSTCONFLICT1                         ,"Konflikt mit Einstellungen.\nFast Zeitverlauf aktiviert."},
	/*1971*/ {IDS_SAVETOUSBALL                         ,"Auf Speicher verschieben"},
	/*1972*/ {IDS_USBMOVENOTIFY                        ,"File in Verwendung!\nnicht kopiert."},
	/*1973*/ {IDS_USBDUPLICATENOTIFY                   ,"Doppelte Filenamen\ngeaendert."},
	/*1974*/ {IDS_USBNOMOVENOTIFY                      ,"Einige Files wurden\nnicht kopiert."},
	/*1975*/ {IDS_LN1                                  ,"Ln1"},
	/*1976*/ {IDS_LN2                                  ,"Ln2"},
	/*1977*/ {IDS_LN3                                  ,"Ln3"},
	/*1978*/ {IDS_LN4                                  ,"Ln4"},
	/*1979*/ {IDS_LN5                                  ,"Ln5"},
	/*1980*/ {IDS_LN6                                  ,"Ln6"},
	/*1981*/ {IDS_PAUSETIME                            ,"Pausendauer:"},
	/*1982*/ {IDS_INVALIDMSMTTIME1                     ,"Ungueltiges Intervall.\nMuß groesser als\n1 s sein."},
	/*1983*/ {IDS_INVALIDMSMTTIME2                     ,"Ungültiges Zeitinterval.\n Interval muß 1 Minute\n oder größer sein"},
	/*1984*/ {IDS_FORMATFAILED                         ,"Formatierung\nfehlgeschlagen."},
	/*1985*/ {IDS_NOPLAYBACK                           ,"Wiedergabe nicht\nmoeglich, wenn\nAuto-Speichern aktiv."},
	/*1986*/ {IDS_FILEINUSE                            ,"Oeffnen nicht moeglich.\nFile wird verwendet."},
	/*1987*/ {IDS_PCBREV                               ,"PCB-Vers.:"},
	/*1988*/ {IDS_SOUNDRECORDINGS                      ,"Audioaufzeichnungen"},
	/*1989*/ {IDS_FSCHECKNOTIFY                        ,"Geraet wird angehalten."},
	/*1990*/ {IDS_CANNOTDELETEFILE                     ,"Loeschen nicht moeglich.\nFile wird verwendet."},
	/*1991*/ {IDS_NOPLAYBACK1                          ,"File vor Wiedergabe\nbitte speichern."},
	/*1992*/ {IDS_CANNOTRENAME                         ,"Ueberschreiben nicht\nmoeglich. File mit aehnlichem\nName wird verwendet."},
	/*1993*/ {IDS_CANNOTRENAMECOPY                     ,"Umbenennen nicht\nmoeglich. File\nwird verwendet."},
	/*1994*/ {IDS_PREAMPNOTSUPPORTED                   ,"Vorverst. wird\nnicht unterstuezt."},
	/*1995*/ {IDS_STABLE                               ,"Konstant"},
	/*1996*/ {IDS_DEMO                                 ,"Demo"},
	/*1997*/ {IDS_BACKERASE                            ,"Rueckloeschung"},
	/*1998*/ {IDS_PRINT                                ,"Uebersicht drucken"},
	/*1999*/ {IDS_DOSESETTINGS                         ,"Dosis Einstellugnen"},
	/*2000*/ {IDS_RESULTS                              ,"Ergebnisse"},
	/*2001*/ {IDS_PRINTSCREEN                          ,"Display drucken"},
	/*2002*/ {IDS_MTLMEASDESC                          ,"Beschreibung\n der Messung"},
	/*2003*/ {IDS_MTLCOMMUNITYNOISE                    ,"EU-Direktive"},
	/*2004*/ {IDS_MTLLNPERCENTILE                      ,"Ln\nPerzentile"},
	/*2005*/ {IDS_MTLOVERALLSETTINGS                   ,"Grund\nEinstellunen"},
	/*2006*/ {IDS_MTLPRINTSUCCESS                      ,"Druck ist beendet."},
	/*2007*/ {IDS_MTLNOPRINTER                         ,"Drucker ist nicht aktiv."},
	/*2008*/ {IDS_MTLDISCONNECT                        ,"Drucker nicht angeschlossen.\nDruck ist fehlgeschlagen."},
	/*2009*/ {IDS_DISP_PROFILE_LARGE1                  ,"Digital"},
	/*2010*/ {IDS_DISPLAYWARNING                       ,"Es koennen nicht\nalle Displays deaktiviert werden."},
	/*2011*/ {IDS_TABSYSOPTIONS                        ,"Optionen"},
	/*2012*/ {IDS_TABSMSOUT                            ,"SMS Aus"},
	/*2013*/ {IDS_SENDSMSON                            ,"SMS An"},
	/*2014*/ {IDS_MEMLOW                               ,"Wenig Speicher"},
	/*2015*/ {IDS_SMSIN                                ,"SMS In"},
	/*2016*/ {IDS_ALL                                  ,"Alle"},
	/*2017*/ {IDS_WEATHERINT                           ,"Klima-INT"},
	/*2018*/ {IDS_WEATHERVAISALA                       ,"Vaisala"},
	/*2019*/ {IDS_MAXRATE                              ,"Max Rate"},
	/*2020*/ {IDS_ACCUMULATION                         ,"Akkumulation"},
	/*2021*/ {IDS_RAINRATE                             ,"Niederschlagsmenge"},
	/*2022*/ {IDS_HAILRATE                             ,"Hagelmenge"},
	/*2023*/ {IDS_OPTIONSWARNING                       ,"Alle Optionen koennen nicht\ndeaktiviert werden.\n Default Optionen werden eingestellt."},
	/*2024*/ {IDS_OPTIONS                              ,"Optionen"},
	/*2025*/ {IDS_OPTIONSCHANGED                       ,"Optionen geaendert.\nBitte Geraet neu starten."},
	/*2026*/ {IDS_MM_PER_HOUR                          ,"mm/hr"},
	/*2027*/ {IDS_IN_PER_HOUR                          ,"in/hr"},
	/*2028*/ {IDS_HITS_PER_CM_SQ_HOUR                  ,"hits/cm²h"},
	/*2029*/ {IDS_HITS_PER_IN_SQ_HOUR                  ,"hits/in²h"},
	/*2030*/ {IDS_HITS_PER_CM_SQ                       ,"hits/cm²"},
	/*2031*/ {IDS_HITS_PER_IN_SQ                       ,"hits/in²"},
	/*2032*/ {IDS_METERS_PER_SEC                       ,"m/s"},
	/*2033*/ {IDS_MI_PER_HOUR                          ,"m/h"},
	/*2034*/ {IDS_INCHES                               ,"in"},
	/*2035*/ {IDS_MILIMETERS                           ,"mm"},
	/*2036*/ {IDS_CENTIMETERS                          ,"cm"},
	/*2037*/ {IDS_PERCENT_RH                           ,"% RH"},
	/*2038*/ {IDS_EMPTY                                ,"  "},
	/*2039*/ {IDS_OPT_QC_TONALITY                      ,"QC- Tonhaltigkeit"},
	/*2040*/ {IDS_CORRECTED_DBA                        ,"Korrigierter dBA"},
	/*2041*/ {IDS_CORR_OBALASEQ                        ,"Kor. L$#eq"},
	/*2042*/ {IDS_WARN_REVISION                        ,"Falsche Version \nfür dieses Merkmal."},
	/*2043*/ {IDS_RS232_WILL_DISABLE                   ,"RS232 wird deaktiviert..."},
	/*2044*/ {IDS_VAISALA_WILL_DISABLE                 ,"Vaisala wird deaktiviert..."},
	/*2045*/ {IDS_Q_DISABLE_USB                        ,"USB Port deaktivieren?"},
	/*2046*/ {IDS_TALARM                               ,"TA-Laerm"},
	/*2047*/ {IDS_LN95                                 ,"Ln95"},
	/*2048*/ {IDS_LN                                   ,"Ln Statistik"},
	/*2049*/ {IDS_SLM                                  ,"SPM"},
	/*2050*/ {IDS_Q_CHANGE_MODES                       ,"Modus aendern?"},
	/*2051*/ {IDS_PRINTENFORCEMENT                     ,"Regel drucken"},
	/*2052*/ {IDS_PRINTCALIBRATION                     ,"Ka librierung drucken"},
	/*2053*/ {IDS_MTLLOCATION                          ,"Ort:"},
	/*2054*/ {IDS_MTLBY                                ,"Von:"},
	/*2055*/ {IDS_MTLDEPT                              ,"Abt:"},
	/*2056*/ {IDS_CALIBRATION                          ,"Kalibrierung"},
	/*2057*/ {IDS_SERIALNO                             ,"Serien-Nr.:"},
	/*2058*/ {IDS_REFSPL                               ,"Ref. SPL"},
	/*2059*/ {IDS_SELECT                               ,"Auswahl"},
	/*2060*/ {IDS_NEW                                  ,"Neu"},
	/*2061*/ {IDS_OLD                                  ,"Alt"},
	/*2062*/ {IDS_SAVE_CAL_STD_LVL                     ,"Save %sdB as\nStandard E.A. Level?"},
	/*2063*/ {IDS_USB_LOW_POWER                        ,"USB deaktiviert\nzu geringe Spannung."},
	/*2064*/ {IDS_SIL                                  ,"SIL"},
	/*2065*/ {IDS_DEVELOPER                            ,"Entwickler"},
	/*2066*/ {IDS_ROOM_ACOUSTICS_NL                    ,"Raumakustik"},
	/*2067*/ {IDS_ROOM_ACOUSTICS                       ,"Raumakustik"},
	/*2068*/ {IDS_RT60                                 ,"RT-60"},
	/*2069*/ {IDS_RT60_SR                              ,"RT-60 Tonsignal"},
	/*2070*/ {IDS_SOURCE                               ,"Quelle"},
	/*2071*/ {IDS_RTA                                  ,"RTA"},
	/*2072*/ {IDS_RTA_SR                               ,"Soundaufzeichnung"},
	/*2073*/ {IDS_SPECTRA                              ,"Spektrum"},
	/*2074*/ {IDS_PROJECT_NAME                         ,"Projektname"},
	/*2075*/ {IDS_NOISE_RT60                           ,"Rauschen RT60"},
	/*2076*/ {IDS_NOISE_RTA                            ,"Rauschen RTA"},
	/*2077*/ {IDS_NOISE                                ,"Rauschen"},
	/*2078*/ {IDS_NOISE_WHITE                          ,"Weisses "},
	/*2079*/ {IDS_NOISE_PINK                           ,"Rosa"},
	/*2080*/ {IDS_AMPLITUDE                            ,"Amplitude"},
	/*2081*/ {IDS_MUTE                                 ,"Dämpfung"},
	/*2082*/ {IDS_1_1                                  ,"Oktav"},
	/*2083*/ {IDS_1_3                                  ,"Terz"},
	/*2084*/ {IDS_IMPULSE                              ,"Impuls"},
	/*2085*/ {IDS_INT_NOISE                            ,"Unterbrechung"},
	/*2086*/ {IDS_TRIG_FREQ                            ,"Trigger Freq."},
	/*2087*/ {IDS_TRIG_SOURCE                          ,"Triggerquelle"},
	/*2088*/ {IDS_BUILD_TIME                           ,"Zeit"},
	/*2089*/ {IDS_MAX_RUN_TIME                         ,"Max Messzeit"},
	/*2090*/ {IDS_SAVE_AVG_TS                          ,"Mitteln Zeitsignale"},
	/*2091*/ {IDS_SAVE_ALL_TS                          ,"Speihern Zeitsignale  "},
	/*2092*/ {IDS_EXIT_TIME                            ,"Zeit"},
	/*2093*/ {IDS_LOWEST_BAND                          ,"Niedrigstes Band"},
	/*2094*/ {IDS_HIGHEST_BAND                         ,"Hoechstes Band"},
	/*2095*/ {IDS_ATTENUATION                          ,"Abschwaechung"},
	/*2096*/ {IDS_ADVANCED                             ,"Erweitert"},
	/*2097*/ {IDS_BACK                                 ,"Zurueck"},
	/*2098*/ {IDS_T20                                  ,"T20"},
	/*2099*/ {IDS_T30                                  ,"T30"},
	/*2100*/ {IDS_EDT                                  ,"EDT"},
	/*2101*/ {IDS_SAMPLE                               ,"Wert"},
	/*2102*/ {IDS_ENSEMBLE                             ,"Mittelung"},
	/*2103*/ {IDS_ENTER_CHANGE_DATA                    ,"Enter -> Daten aendern"},
	/*2104*/ {IDS_ENTER_CHANGE                         ,"Enter -> Aendern"},
	/*2105*/ {IDS_METHOD                               ,"Vorgehensweise"},
	/*2106*/ {IDS_MID_BAND                             ,"Mittenfrequenz"},
	/*2107*/ {IDS_F_6_3                                ,"6,3 Hz"},
	/*2108*/ {IDS_F_8                                  ,"8 Hz"},
	/*2109*/ {IDS_F_10                                 ,"10 Hz"},
	/*2110*/ {IDS_F_12_5                               ,"12,5 Hz"},
	/*2111*/ {IDS_F_16                                 ,"16 Hz"},
	/*2112*/ {IDS_F_20                                 ,"20 Hz"},
	/*2113*/ {IDS_F_25                                 ,"25 Hz"},
	/*2114*/ {IDS_F_31_5                               ,"31,5 Hz"},
	/*2115*/ {IDS_F_40                                 ,"40 Hz"},
	/*2116*/ {IDS_F_50                                 ,"50 Hz"},
	/*2117*/ {IDS_F_63                                 ,"63 Hz"},
	/*2118*/ {IDS_F_80                                 ,"80 Hz"},
	/*2119*/ {IDS_F_100                                ,"100 Hz"},
	/*2120*/ {IDS_F_125                                ,"125 Hz"},
	/*2121*/ {IDS_F_160                                ,"160 Hz"},
	/*2122*/ {IDS_F_200                                ,"200 Hz"},
	/*2123*/ {IDS_F_250                                ,"250 Hz"},
	/*2124*/ {IDS_F_315                                ,"315 Hz"},
	/*2125*/ {IDS_F_400                                ,"400 Hz"},
	/*2126*/ {IDS_F_500                                ,"500 Hz"},
	/*2127*/ {IDS_F_630                                ,"630 Hz"},
	/*2128*/ {IDS_F_800                                ,"800 Hz"},
	/*2129*/ {IDS_F_1000                               ,"1,00 kHz"},
	/*2130*/ {IDS_F_1250                               ,"1,25 kHz"},
	/*2131*/ {IDS_F_1600                               ,"1,60 kHz"},
	/*2132*/ {IDS_F_2000                               ,"2,00 kHz"},
	/*2133*/ {IDS_F_2500                               ,"2,50 kHz"},
	/*2134*/ {IDS_F_3150                               ,"3,15 kHz"},
	/*2135*/ {IDS_F_4000                               ,"4,00 kHz"},
	/*2136*/ {IDS_F_5000                               ,"5,00 kHz"},
	/*2137*/ {IDS_F_6300                               ,"6,30 kHz"},
	/*2138*/ {IDS_F_8000                               ,"8,00 kHz"},
	/*2139*/ {IDS_F_10000                              ,"10,0 kHz"},
	/*2140*/ {IDS_F_12500                              ,"12,5 kHz"},
	/*2141*/ {IDS_F_16000                              ,"16,0 kHz"},
	/*2142*/ {IDS_F_20000                              ,"20,0 kHz"},
	/*2143*/ {IDS_LINK_TO_DISPLAY                      ,"Bildschirm"},
	/*2144*/ {IDS_BT                                   ,"BT"},
	/*2145*/ {IDS_BK                                   ,"BG"},
	/*2146*/ {IDS_CO                                   ,"Co"},
	/*2147*/ {IDS_CU                                   ,"Cu"},
	/*2148*/ {IDS_SD                                   ,"SD"},
	/*2149*/ {IDS_INCLUDE                              ,"Inklusiv"},
	/*2150*/ {IDS_EXCLUDE                              ,"Exklusiv"},
	/*2151*/ {IDS_RUN_RA_L1                            ,"Start-L1"},
	/*2152*/ {IDS_RUN_RA_L2                            ,"Start-L2"},
	/*2153*/ {IDS_RUN_RA_B2                            ,"Start-B2"},
	/*2154*/ {IDS_RUN_RA_T2                            ,"Start-T2"},
	/*2155*/ {IDS_RUN_RA_TH                            ,"Historie"},
	/*2156*/ {IDS_MASK_OPTION_MATCH                    ,"File kann nicht angezeigt werden"},
	/*2157*/ {IDS_NOPLAYBACK_RUNNING                   ,"Kein Abspielen waehrend\nMessung laeuft"},
	/*2158*/ {IDS_NL                                   ,"NL"},
	/*2159*/ {IDS_RT60_STATUS                          ,"RT-60 Status"},
	/*2160*/ {IDS_RT60_TIMES                           ,"RT60 Zeitprofil"},
	/*2161*/ {IDS_RT60_DECAYS                          ,"RT60 Abklingkurve"},
	/*2162*/ {IDS_RT60_LEVELS                          ,"RT-60 Pegel"},
	/*2163*/ {IDS_QI_SUMMARY1                          ,"Qualität Zusammenfassung 1"},
	/*2164*/ {IDS_QI_SUMMARY2                          ,"Qualität Zusammenfassung 2"},
	/*2165*/ {IDS_QI_DETAIL                            ,"Qualität Detail"},
	/*2166*/ {IDS_SURVEY                               ,"Ueberblick"},
	/*2167*/ {IDS_ENGINEERING                          ,"Technik"},
	/*2168*/ {IDS_PRECISION                            ,"Genauigkeit"},
	/*2169*/ {IDS_POSITION                             ,"Position"},
	/*2170*/ {IDS_POSITIONS                            ,"Positionen"},
	/*2171*/ {IDS_DECAY_PER_POS                        ,"Abklingkurve/Position"},
	/*2172*/ {IDS_DECAY                                ,"Abklingrate"},
	/*2173*/ {IDS_DECAYS                               ,"Abklingrate"},
	/*2174*/ {IDS_EST_GRADE                            ,"Vorraussichtlicher Rang"},
	/*2175*/ {IDS_FREG_RANGE                           ,"Frequenzbereich"},
	/*2176*/ {IDS_DASHES                               ,"- - -"},
	/*2177*/ {IDS_ACTUAL                               ,"Aktuell:"},
	/*2178*/ {IDS_REQUIRED                             ,"Erforderlich:"},
	/*2179*/ {IDS_CONFIRM_DELETEALL_SLM                ,"Alle Pegel Files loeschen?"},
	/*2180*/ {IDS_CONFIRM_DELETEALL_RA                 ,"Alle RA Files loeschen?"},
	/*2181*/ {IDS_CONFIRM_DELETEALL_FFT                ,"Alle FFT Files loeschen?"},
	/*2182*/ {IDS_INSTALLED                            ,"Installiert"},
	/*2183*/ {IDS_TEMPERATURE                          ,"Temperatur"},
	/*2184*/ {IDS_HUMIDITY                             ,"Luftfeuchte"},
	/*2185*/ {IDS_L1_RANGE                             ,"L1 Bereich"},
	/*2186*/ {IDS_L2_RANGE                             ,"L2 Bereich"},
	/*2187*/ {IDS_B2_RANGE                             ,"B2 Bereich"},
	/*2188*/ {IDS_B2                                   ,"B2"},
	/*2189*/ {IDS_L1L2                                 ,"L1 L2"},
	/*2190*/ {IDS_SAMPLEPERIOD                         ,"Aufnahmerate"},
	/*2191*/ {IDS_MAX_POSITION                         ,"Max. Anzahl\n erreicht"},
	/*2192*/ {IDS_SETTING_CONFLICT                     ,"Falsche Einstellung"},
	/*2193*/ {IDS_NOT_APPLICABLE                       ,"Nicht verfuegbar"},
	/*2194*/ {IDS_FFT                                  ,"FFT"},
	/*2195*/ {IDS_FFT_LIVE                             ,"FFT Live"},
	/*2196*/ {IDS_CREATE_AVG                           ,"Mittelung"},
	/*2197*/ {IDS_ADD_TO_AVG                           ,"Hinzufügen"},
	/*2198*/ {IDS_ERROR_CANNOT_AVERAGE                 ,"Einstellungsfehler\n"},
	/*2199*/ {IDS_CREATED_AVERAGE                      ,"Datei-Mitt"},
	/*2200*/ {IDS_FILE_AVERAGING                       ,"Datei-Mittelung"},
	/*2201*/ {IDS_WINDOW                               ,"FFT Fenster"},
	/*2202*/ {IDS_HANNING                              ,"Hanning"},
	/*2203*/ {IDS_FLATTOP                              ,"Flat Top"},
	/*2204*/ {IDS_RECTANGULAR                          ,"Rechteck"},
	/*2205*/ {IDS_FREQUENCY_SPAN                       ,"Bandbreite"},
	/*2206*/ {IDS_LINES                                ,"Linien"},
	/*2207*/ {IDS_6400                                 ,"6400"},
	/*2208*/ {IDS_3200                                 ,"3200"},
	/*2209*/ {IDS_1600                                 ,"1600"},
	/*2210*/ {IDS_800                                  ,"800"},
	/*2211*/ {IDS_400                                  ,"400"},
	/*2212*/ {IDS_MANUAL                               ,"Manuell"},
	/*2213*/ {IDS_COUNT_STOP                           ,"Zählerstop"},
	/*2214*/ {IDS_CURSOR                               ,"Cursor"},
	/*2215*/ {IDS_CURSOR_TYPE                          ,"Cursor Typ"},
	/*2216*/ {IDS_MAX_TRACKING                         ,"Maxwert"},
	/*2217*/ {IDS_HARMONICS                            ,"Harmonische"},
	/*2218*/ {IDS_TO                                   ,"bis"},
	/*2219*/ {IDS_LPT                                  ,"Lpt"},
	/*2220*/ {IDS_LPN                                  ,"Lpn"},
	/*2221*/ {IDS_LTA                                  ,"Lta"},
	/*2222*/ {IDS_KT                                   ,"Kt"},
	/*2223*/ {IDS_BCRIT                                ,"Bcrit"},
	/*2224*/ {IDS_TONE_SEEK_DELTA                      ,"Tone Seek "},
	/*2225*/ {IDS_TONE_SEEK_DELTA_1                    ,"1 dB"},
	/*2226*/ {IDS_TONE_SEEK_DELTA_2                    ,"2 dB"},
	/*2227*/ {IDS_TONE_SEEK_DELTA_3                    ,"3 dB"},
	/*2228*/ {IDS_TONE_SEEK_DELTA_4                    ,"4 dB"},
	/*2229*/ {IDS_LR_SPAN_PERCENT_50                   ," 50 %"},
	/*2230*/ {IDS_LR_SPAN_PERCENT_75                   ," 75 %"},
	/*2231*/ {IDS_LR_SPAN_PERCENT_100                  ,"100 %"},
	/*2232*/ {IDS_LR_SPAN_PERCENT_150                  ,"150 %"},
	/*2233*/ {IDS_LR_SPAN_PERCENT_200                  ,"200 %"},
	/*2234*/ {IDS_831_INT_ET                           ,"831 INT-ET"},
	/*2235*/ {IDS_NF30_LN                              ,"NF30 Ln"},
	/*2236*/ {IDS_CURRENT                              ,"Aktuell"},
	/*2237*/ {IDS_IP_ADDR                              ,"IP"},
	/*2238*/ {IDS_MAC_ADDR                             ,"MAC"},
	/*2239*/ {IDS_FILENAME_EXISTS                      ,"Dateiname vorhanden \n Ueberschreiben?"},
	/*2240*/ {IDS_FF2RI_2106_8                         ,"FF:RI 2106/8"},
	/*2241*/ {IDS_FF2FF_2106_8                         ,"FF:FF 2106/8"},
	/*2242*/ {IDS_FF290_2106_8                         ,"FF:90 2106/8"},
	/*2243*/ {IDS_DLYAUTOSTORE48                       ,"48/Tag"},
	/*2244*/ {IDS_DLYAUTOSTORE96                       ,"96/Tag"},
	/*2245*/ {IDS_DLYAUTOSTORE144                      ,"144/Tag"},
	/*2246*/ {IDS_BAD_TIMES                            ,"Ungueltige Abendzeit. \n Autom. korrigieren?"},
	/*2247*/ {IDS_FLASH_ERROR                          ,"Korrupte Flash Sektoren. \n Bitte Daten speichern und \n Dateisystem formattieren."},
	/*2248*/ {IDS_COMMS_WATCHDOG                       ,"Kommunikations Watchdog"},
	/*2249*/ {IDS_COMMS_WATCHDOG_COUNT                 ,"Komm WD Zaehler"},
	/*2250*/ {IDS_TEMPERATURE_AVG                      ,"Temp. Mittelwert"},
	/*2251*/ {IDS_TEMPERATURE_MAX                      ,"Temperatur Max"},
	/*2252*/ {IDS_TEMPERATURE_MIN                      ,"Temperatur Min"},
	/*2253*/ {IDS_HUMIDITY_AVG                         ,"Feuchte Mittelwert"},
	/*2254*/ {IDS_HUMIDITY_MAX                         ,"Feuchte Max"},
	/*2255*/ {IDS_HUMIDITY_MIN                         ,"Feuchte Min"},
	/*2256*/ {IDS_OFF_CLOSE                            ,"Aus,Zu,"},
	/*2257*/ {IDS_ERROR_LOG                            ,"Fehlerspeicher"},
	/*2258*/ {IDS_TIMER_EXPIRED                        ,"Abgelaufen"},
	/*2259*/ {IDS_TONALITYX                            ,"Tonhaltigkeit"},
	/*2260*/ {IDS_1996_TONALITY                        ,"ISO 1996-2 Tonality"},
	/*2261*/ {IDS_TONE                                 ,"Ton"},
	/*2262*/ {IDS_TONES                                ,"Töne"},
	/*2263*/ {IDS_NO_TONES                             ,"Kein Töne"},
	/*2264*/ {IDS_SETTINGS_DIFFER                      ,"Einstellungen weichen \n von Standard ab. \n Autom. korrigieren?"},
	/*2265*/ {IDS_RUNNING                              ,"Laeuft"},
	/*2266*/ {IDS_LR_SPAN_PERCENT                      ,"Regressionsbereich"},
	/*2267*/ {IDS_HEATER                               ,"Heizung"},
	/*2268*/ {IDS_AC_OUT_DISABLED                      ,"AC/DC Buchsenfunktion \n wurde deaktiviert"},
	/*2269*/ {IDS_WATCHDOG                             ,"Watchdog"},
	/*2270*/ {IDS_COUNTER_WRAP                         ,"Zeitlimit"},
	/*2271*/ {IDS_FAST_WEATHER                         ,"Schnelles Wetter"},
	/*2272*/ {IDS_REMAINING_LEQ                        ,"Verbleibender Leq"},
	/*2273*/ {IDS_ELAPSED                              ,"Verstrichen"},
	/*2274*/ {IDS_REMAINING                            ,"Verbleibend"},
	/*2275*/ {IDS_TARGET                               ,"Ziel"},
	/*2276*/ {IDS_VAISALA_WEATHER                      ,"Vaisala Wetter"},
	/*2277*/ {IDS_OTHER                                ,"Andere"},
	/*2278*/ {IDS_RAM_SIZE                             ,"RAM Groesse:"},
	/*2279*/ {IDS_NETWORK                              ,"Netzwerk"},
	/*2280*/ {IDS_TIME_WEIGHTED_AVE                    ,"Zeitbewertete Mittelwerte"},
	/*2281*/ {IDS_MTIME_RES                            ,"Millisekundenaufloesung"},
	/*2282*/ {IDS_SETTINGS_MODIFIED                    ,"Einstellungen wurde geaendert."},
	/*2283*/ {IDS_SETTOACTIVE                          ,"Aktiv gesetzt"},
	/*2284*/ {IDS_HLD_YOU_MUST_ENABLE                  ,"Sie muessen erlauben"},
	/*2285*/ {IDS_HLD_SETTINGSCONFLICT_INTEGRATION     ,"Einstellungskonflikt: Integrationsmethode muss linear sein, Mess-, Schnappschuss- und Eventhistorie muessen deaktiviert sein. Automatisch korrigieren?"},
	/*2286*/ {IDS_HLD_SETTINGSCONFLICT_SAVE_SNAP       ,"Einstellungskonflikt: Schnappschusshistorie muss deaktiviert sein für diese Einstellung. Automatisch korrigieren?"},
	/*2287*/ {IDS_HLD_FST_ONENTHIRD_OPTIONS            ,"Sie müssen die Optionen Fast Time History, Oktaven (1/1) und Terzen (1/3) aktivieren."},
	/*2288*/ {IDS_HLD_SAMPLERATE_TOOHIGH               ,"Einstellungskonflikt: Geraeuschaufzeichnungsabtastrate zu hoch eingestellt, 8 ksps mit Zeithistorie. Automatisch korrigieren?"},
	/*2289*/ {IDS_HLD_SOUNDRECORDING_OPTION            ,"Sie muessen die Option Sound Recording aktivieren."},
	/*2290*/ {IDS_HLD_USBHOSTPORT_GPS                  ,"Sie muessen den USB Host und den GPS Modus aktivieren."},
	/*2291*/ {IDS_HLD_ENABLE_USBHOSTPORT               ,"Sie muessen den USB Host aktivieren."},
	/*2292*/ {IDS_HLD_ENABLE_MEASHISTORY               ,"Sie muessen die Messhistorie aktivieren."},
	/*2293*/ {IDS_HLD_RUNTIME_59SECS                   ,"Die Laufzeit muss mehr als 59 Sekunden betragen."},
	/*2294*/ {IDS_HLD_EN_MEASHIST_NOTMANUAL            ,"Sie muessen die Messhistorie aktivieren und den Modus nicht auf 'manueller Stopp' setzen."},
	/*2295*/ {IDS_HLD_EN_MEASHIST_OPTION               ,"Sie muessen die Option Messhistorie aktivieren."},
	/*2296*/ {IDS_HLD_EN_EVENTHIST                     ,"Sie muessen die Option Eventhistorie aktivieren."},
	/*2297*/ {IDS_HLD_EN_MEASHIST_N_OPTION             ,"Sie muessen die Option Messhistorie aktivieren."},
	/*2298*/ {IDS_HLD_DIFFER_TONALITYSTD_FIX           ,"Einstellungen nicht nach Standrad fuer Tonhaltigkeit. Automatisch korrigieren?"},
	/*2299*/ {IDS_HLD_RS232DISABLED                    ,"RS232 wird deaktiviert. Fortfahren?"},
	/*2300*/ {IDS_HLD_EN_TIMEDSTOP                     ,"Sie muessen 'zeitlicher Stopp' aktivieren."},
	/*2301*/ {IDS_HLD_REQUIREDPREAMP                   ,"Sie muessen den benoetigten Vorverstaerker benutzen."},
	/*2302*/ {IDS_HLD_RT60METHOD_INTERRUPTED           ,"RT60 Modus muss auf 'interrupted' gesetzt werden."},
	/*2303*/ {IDS_HLD_STOREONCEDAILY                   ,"Sie muessen wenigstens einmal taeglich speichern auswaehlen."},
	/*2304*/ {IDS_HLD_MUSTBE_INTET                     ,"Das Messgeraet muss sich im INT/INT-ET befinden."},
	/*2305*/ {GID_MAY_WAIT_FOR_OTHER_SPREADSHEETS      ,"Kann warten, wenn andere Tabellen sind "Gebäude"."},
	/*2306*/ {IDS_LNF                                  ,"L <sub> NF </ sub>"},
	/*2307*/ {IDS_LCEQN                                ,"L<sub>Ceq</sub>"},
	/*2308*/ {IDS_LAEQN                                ,"L<sub>Aeq</sub>"},
	/*2309*/ {IDS_LZEQN                                ,"L<sub>Zeq</sub>"},
	/*2310*/ {IDS_RESET                                ,"Klar"},
	/*2311*/ {IDS_FF2RI_2116                           ,"FF:RI 2116"},
	/*2312*/ {IDS_FF2FF_2116                           ,"FF:FF 2116"},
	/*2313*/ {IDS_FF290_2116                           ,"FF:90 2116"},
	/*2314*/ {IDS_HLD_DYNAMIC_RANGE                    ,"Dynamic Range Compression"},
	/*2315*/ {IDS_HLD_SAVEFILE                         ,"IDS_HLD_SAVEFILE, "Save to File"},
	/*2316*/ {IDS_HLD_BUFFERLEN                        ,"IDS_HLD_BUFFERLEN "Pufferlänge"},
	/*2317*/ {IDS_HLD_ARMS                             ,"a <sub> RMS </ sub>"},
	/*2318*/ {IDS_HLD_APEAK                            ,"a<sub>PEAK</sub>"},
	/*2319*/ {IDS_HLD_AMIN                             ,"a<sub>MIN</sub>"},
	/*2320*/ {IDS_HLD_AMAX                             ,"MTVV"},
	/*2321*/ {IDS_HLD_RETURNOVERALL                    ,"Zurück zur Gesamt Registerkarte"},
	/*2322*/ {IDS_HLD_UPLOADFIRM                       ,"Upload Firmware"},
	/*2323*/ {IDS_HLD_MODEL                            ,"Modell"},
	/*2324*/ {IDS_HLD_CONN_TYPE                        ,"Verbindungstyp"},
	/*2325*/ {IDS_HLD_SENSORSTAT                       ,"Sensor Status"},
	/*2326*/ {IDS_HLD_TEDS                             ,"TEDS"},
	/*2327*/ {IDS_HLD_SYSSTAT                          ,"Systemstatus"},
	/*2328*/ {IDS_HLD_WIFI                             ,"W-lan"},
	/*2329*/ {IDS_HLD_CHARGING                         ,"Lade"},
	/*2330*/ {IDS_HLD_MISSING                          ,"fehlende"},
	/*2331*/ {IDS_HLD_USING                            ,"Verwendung"},
	/*2332*/ {IDS_HLD_CHARGED                          ,"Berechnet"},
	/*2333*/ {IDS_HLD_BATLOW                           ,"Niedrig"},
	/*2334*/ {IDS_HLD_SAVE_MEASPROPS                   ,"Save Measurement Eigenschaften"},
	/*2335*/ {IDS_HLD_SAVE_SYSPROPS                    ,"Sparen Sie Systemeigenschaften"},
	/*2336*/ {IDS_HLD_FIRMWARE                         ,"Firmware"},
	/*2337*/ {IDS_HLD_FILETYPE                         ,"Dateityp"},
	/*2338*/ {IDS_HLD_INTERNAL_MEM                     ,"Verwendung des internen Speichers"},
	/*2339*/ {IDS_HLD_TIME_REM                         ,"Verbleibende Zeit (h: m)"},
	/*2340*/ {IDS_HLD_SENS_ERROR                       ,"Nicht angeschlossen oder Fehler"},
	/*2341*/ {IDS_HLD_SETWIFI                          ,"Setup WiFi"},
	/*2342*/ {IDS_HLD_SENSOR                           ,"Sensor"},
	/*2343*/ {IDS_HLD_ADD                              ,"Hinzufügen"},
	/*2344*/ {IDS_HLD_SETAP                            ,"Set Access Point"},
	/*2345*/ {IDS_HLD_UP                               ,"Oben"},
	/*2346*/ {IDS_HLD_DOWN                             ,"nach unten"},
	/*2347*/ {IDS_HLD_SETNET                           ,"Eine Verbindung mit WiFi"},
	/*2348*/ {IDS_HLD_SETNET_ERROR                     ,"Sie müssen mindestens einen konfigurierten WLAN-Netzwerk zu haben."},
	/*2349*/ {IDS_HLD_WIFI_NET                         ,"WiFi Netz"},
	/*2350*/ {IDS_HLD_MY_IP                            ,"Meine IP-"},
	/*2351*/ {IDS_HLD_SAVED                            ,"gespeichert"},
	/*2352*/ {IDS_HLD_NETWORKS                         ,"Netzwerk"},
	/*2353*/ {IDS_HLD_PRIORITY                         ,"Vorliebe"},
	/*2354*/ {IDS_HLD_SIGNAL                           ,"Signal"},
	/*2355*/ {IDS_HLD_SCANNING                         ,"Scannen"},
	/*2356*/ {IDS_HLD_NET_OPEN                         ,"Öffnen"},
	/*2357*/ {IDS_HLD_NETSECURE                        ,"Gesichert"},
	/*2358*/ {IDS_HLD_CONFIRM_REM_NET                  ,"Sind Sie sicher, dass Sie diese WiFi-Netzwerk zu vergessen wollen?"},
	/*2359*/ {IDS_HLD_CONFIRM_DELETE                   ,"Passwort Bestätigung"},
	/*2360*/ {IDS_HLD_CONFIRM_UPGRADE                  ,"Upgrade-Bestätigung"},
	/*2361*/ {IDS_HLD_CONFIRM_DELFILE                  ,"Sie sind dabei, diese Datei zu löschen"},
	/*2362*/ {IDS_HLD_CONF_CON_NET                     ,"Eine Verbindung mit WiFi-Netzwerk"},
	/*2363*/ {IDS_HLD_CONF_LOSECON                     ,"Wenn Sie fortfahren, können Sie Verbindung mit dem Messgerät zu verlieren, wenn nicht über USB angeschlossen. Bitte verbinden Sie mit dem gleichen Netzwerk wie das Gerät."},
	/*2364*/ {IDS_HLD_CONF_SET_AP                      ,"Als Access Point"},
	/*2365*/ {IDS_HLD_FILEMAN                          ,"Dateimanager"},
	/*2366*/ {IDS_HLD_VIBRATION                        ,"Vibration"},
	/*2367*/ {IDS_HLD_HANDARM                          ,"Hand / Arm"},
	/*2368*/ {IDS_HLD_WHOLEBODY                        ,"Ganzer Körper"},
	/*2369*/ {IDS_HLD_DATAFILE                         ,"Datendatei"},
	/*2370*/ {IDS_HLD_VIEWFILE                         ,"Ansicht-Datendatei"},
	/*2371*/ {IDS_HLD_DELSELFILE                       ,"Löschen ausgewählte Datei"},
	/*2372*/ {IDS_HLD_REFLIST                          ,"Aktualisieren der Dateiliste"},
	/*2373*/ {IDS_HLD_UPNEWFIRM                        ,"Neue Firmware hochladen"},
	/*2374*/ {IDS_HLD_CONFREQ                          ,"Bestätigung erforderlich"},
	/*2375*/ {IDS_HLD_ANNOMEAS                         ,"Anmerken Mess"},
	/*2376*/ {IDS_HLD_ANNOTIME                         ,"Annotation Zeit"},
	/*2377*/ {IDS_HLD_ANNOTATE                         ,"Kommentieren"},
	/*2378*/ {IDS_HLD_ANNONOTE                         ,"Notiz"},
	/*2379*/ {IDS_HLD_SUMMATION                        ,"Σ Summen"},
	/*2380*/ {IDS_HLD_AXIS                             ,"Achse"},
	/*2381*/ {IDS_HLD_TOTAL                            ,"Gesamt"},
	/*2382*/ {IDS_HLD_MODE                             ,"Modus"},
	/*2383*/ {IDS_HLD_OVLD                             ,"Überladen"},
	/*2384*/ {IDS_HLD_CONF                             ,"Bestätigen"},
	/*2385*/ {IDS_HLD_WILLREBOOT                       ,"Der Zähler wird neu gestartet."},
	/*2386*/ {IDS_HLD_WILLSTOPREBOOT                   ,"Das Messgerät wird angehalten und neu gestartet werden."},
	/*2387*/ {IDS_HLD_PROCFILE                         ,"Verarbeitungsdatei"},
	/*2388*/ {IDS_HLD_REBOOTING                        ,"Neustart"},
	/*2389*/ {IDS_HLD_CLOSING                          ,"Schließen"},
	/*2390*/ {IDS_HLD_SETUP                            ,"Einrichten"},
	/*2391*/ {IDS_HLD_SCHEDULE                         ,"Zeitplan"},
	/*2392*/ {IDS_HLD_MISC                             ,"misc"},
	/*2393*/ {IDS_HLD_TOOLS                            ,"Tools"},
	/*2394*/ {IDS_HLD_TOOLS2                           ,"Tools 2"},
	/*2395*/ {IDS_HLD_OPERATING_MODE                   ,"Betriebsart"},
	/*2396*/ {IDS_HLD_OM_VIB                           ,"Vibration"},
	/*2397*/ {IDS_HLD_OM_HA                            ,"Hand / Arm"},
	/*2398*/ {IDS_HLD_OM_WB                            ,"Ganzer Körper"},
	/*2399*/ {IDS_HLD_STORE_INTER_TIME                 ,"Shop Intervallzeit"},
	/*2400*/ {IDS_HLD_SEC                              ,"Sekunde"},
	/*2401*/ {IDS_HLD_MIN                              ,"min"},
	/*2402*/ {IDS_HLD_HR                               ,"Hr"},
	/*2403*/ {IDS_HLD_W_WS                             ,"Ws Severity"},
	/*2404*/ {IDS_HLD_W_FA                             ,"Fa 0,4 bis 100 Hz"},
	/*2405*/ {IDS_HLD_W_FB                             ,"Fb 0,4 bis 1250 Hz"},
	/*2406*/ {IDS_HLD_W_FC                             ,"Fc 6,3 bis 1250 Hz"},
	/*2407*/ {IDS_HLD_W_WH                             ,"Wh"},
	/*2408*/ {IDS_HLD_W_WM                             ,"Wm Gebäude"},
	/*2409*/ {IDS_HLD_W_WB                             ,"Wb Railways-Z"},
	/*2410*/ {IDS_HLD_W_WC                             ,"WC Sitzlehnen-X"},
	/*2411*/ {IDS_HLD_W_WD                             ,"Wd Horizontal-XY"},
	/*2412*/ {IDS_HLD_W_WE                             ,"wir Rotational"},
	/*2413*/ {IDS_HLD_W_WG                             ,"Wg BS 8461-Z"},
	/*2414*/ {IDS_HLD_W_WJ                             ,"Wj Kopf-X"},
	/*2415*/ {IDS_HLD_W_WK                             ,"Wk Vertikale-Z"},
	/*2416*/ {IDS_HLD_W_WF                             ,"Wf Low Freq"},
	/*2417*/ {IDS_HLD_DELAY_START                      ,"Start verzögern"},
	/*2418*/ {IDS_HLD_RUN_DUR                          ,"Führen Dauer"},
	/*2419*/ {IDS_HLD_STOR_RAW                         ,"Speichern Rohdaten"},
	/*2420*/ {IDS_HLD_STOR_PEAK                        ,"Shop Spitzendaten"},
	/*2421*/ {IDS_HLD_AUTOSTOP                         ,"Autostop"},
	/*2422*/ {IDS_HLD_OBA_TH                           ,"OBA Zeitgeschichte"},
	/*2423*/ {IDS_HLD_DB_REF                           ,"dB Reference"},
	/*2424*/ {IDS_HLD_EXP_LIMIT                        ,"Exposure Limit"},
	/*2425*/ {IDS_HLD_EXP_ACTION                       ,"Auslöse"},
	/*2426*/ {IDS_HLD_DIS_UNITS                        ,"Anzeigeeinheiten"},
	/*2427*/ {IDS_HLD_INTEGRATION                      ,"Integration"},
	/*2428*/ {IDS_HLD_K_FACTOR                         ,"K-Faktor"},
	/*2429*/ {IDS_HLD_BASE_NAME                        ,"Datendateiname"},
	/*2430*/ {IDS_HLD_SF_NAME                          ,"Festlegen Dateiname"},
	/*2431*/ {IDS_HLD_AUTO_STORE                       ,"Auto Store"},
	/*2432*/ {IDS_HLD_STORE_TIME                       ,"Öffnungszeit"},
	/*2433*/ {IDS_HLD_SINGLE                           ,"Single"},
	/*2434*/ {IDS_HLD_DOUBLE                           ,"Doppelt"},
	/*2435*/ {IDS_HLD_ACDC_OUTPUT                      ,"AC / DC-Ausgang"},
	/*2436*/ {IDS_HLD_AC_W                             ,"AC: Gewichtete"},
	/*2437*/ {IDS_HLD_AC_B                             ,"AC: Bandlimit"},
	/*2438*/ {IDS_HLD_DC_RMS                           ,"DC: RMS"},
	/*2439*/ {IDS_HLD_DC_MIN                           ,"DC: Min"},
	/*2440*/ {IDS_HLD_DC_MAX                           ,"DC: Max"},
	/*2441*/ {IDS_HLD_DC_PEAK                          ,"DC: Spitzen"},
	/*2442*/ {IDS_HLD_DC_RMS_SUM                       ,"DC: RMS Sum"},
	/*2443*/ {IDS_HLD_DC_MIN_SUM                       ,"DC: Min Sum"},
	/*2444*/ {IDS_HLD_DC_MAX_SUM                       ,"DC: Max Sum"},
	/*2445*/ {IDS_HLD_DC_PEAK_SUM                      ,"DC: Spitzen Sum"},
	/*2446*/ {IDS_HLD_RPT_HEADERS                      ,"Bericht Headers"},
	/*2447*/ {IDS_HLD_PRNT_HSTRY                       ,"Print History"},
	/*2448*/ {IDS_HLD_SENSOR_LIST                      ,"Sensorliste"},
	/*2449*/ {IDS_HLD_ACCEL_TYPE                       ,"Beschleunigungsmesser"},
	/*2450*/ {IDS_HLD_DIRECT                           ,"Direkt"},
	/*2451*/ {IDS_HLD_CHARGE                           ,"Ladung"},
	/*2452*/ {IDS_HLD_SENSORS                          ,"Sensoren"},
	/*2453*/ {IDS_HLD_SERIAL_NUM                       ,"Serial #"},
	/*2454*/ {IDS_HLD_X_SENS                           ,"x Sens."},
	/*2455*/ {IDS_HLD_Y_SENS                           ,"y Sens."},
	/*2456*/ {IDS_HLD_Z_SENS                           ,"z Sens."},
	/*2457*/ {IDS_HLD_STDATE                           ,"Anfangsdatum"},
	/*2458*/ {IDS_HLD_ENDATE                           ,"Endtermin"},
	/*2459*/ {IDS_HLD_SENSOR_NA                        ,"Fehler oder Sensor nicht unterstützt TEDS."},
	/*2460*/ {IDS_HLD_CONNECTED                        ,"Verbunden"},
	/*2461*/ {IDS_HLD_NOTCONN                          ,"Nicht verbunden"},
	/*2462*/ {IDS_HLD_ALERT                            ,"Aufmerksam"},
	/*2463*/ {IDS_HLD_CN_FAIL                          ,"Fehler beim um Netzwerk zu verbinden. Meter ist immer noch ein Access Point."},
	/*2464*/ {IDS_HLD_CN_SUCC                          ,"Meter ist jetzt mit IP verbunden"},
	/*2465*/ {IDS_HLD_CN_RESET                         ,"Zähler Rücksetzen WiFi"},
	/*2466*/ {IDS_HLD_AP_SUCC                          ,"Meter ist nun eingestellt zu einem Zugangspunkt zu sein."},
	/*2467*/ {IDS_HLD_AP_ERR                           ,"Fehler beim Setzen Access Point."},
	/*2468*/ {IDS_HLD_STATUS                           ,"Status"},
	/*2469*/ {IDS_HLD_WF_ENTNETPASS                    ,"Netzwerkkennwort eingeben"},
	/*2470*/ {IDS_HLD_WF_ADDNET                        ,"hinzufügen von Netzwerk"},
	/*2471*/ {IDS_FIRMUPG_CHOS                         ,"wählen Sie Firmware"},
	/*2472*/ {IDS_FIRMUPG_SAME                         ,"Das Messgerät wurde erfolgreich auf die gleiche Konfiguration aktualisiert."},
	/*2473*/ {IDS_FIRMUPG_SUCCESS                      ,"Erfolgreich aktualisiert das Messgerät."},
	/*2474*/ {IDS_FIRMUPG_FAIL                         ,"Das Messgerät nicht zu aktualisieren. Die Update-Datei ist möglicherweise ungültig gewesen sein oder die Verbindung kann während der Übertragung verloren gegangen sind. Stellen Sie sicher, dass Sie eine gültige Update-Datei haben und versuchen Sie es erneut."},
	/*2475*/ {IDS_HLD_FAIL                             ,"Gescheitert"},
	/*2476*/ {IDS_HLD_FINISHED                         ,"Fertig"},
	/*2477*/ {IDS_HLD_REFERENCE                        ,"Referenz"},
	/*2478*/ {IDS_HLD_SET                              ,"Set"},
	/*2479*/ {IDS_HLD_UPG_AP                           ,"Sie müssen, um des Messgeräts WiFi (Zugangspunkt) wieder anschließen. Schließen Sie dieses Fenster."},
	/*2480*/ {IDS_HLD_APOINT                           ,"Zugangspunkt"},
	/*2481*/ {IDS_HLD_AP_LOSECON                       ,"Wenn Sie fortfahren, werden Sie vorübergehend vom Messgerät getrennt werden und müssen möglicherweise mit dem Netzwerk zu verbinden."},
	/*2482*/ {IDS_HLD_CNCTING                          ,"Anschließen"},
	/*2483*/ {IDS_HLD_LOSTDLG                          ,"Es scheint die Verbindung unterbrochen wurde. Wählen Sie "Start", um an das Messgerät Liste zurückzukehren."},
	/*2484*/ {IDS_HLD_LOSTCON                          ,"Verbindung verloren"},
	/*2485*/ {IDS_HLD_MINPASS                          ,"Entweder kein Passwort oder zumindest muss ein 8-Zeichen-Passwort eingegeben werden, um Ihre WiFi-Netzwerk entsprechen."},
	/*2486*/ {IDS_HLD_MISNAME                          ,"Sie müssen einen gültigen WiFi Netzwerkname (SSID) einzugeben."},
	/*2487*/ {IDS_STOP_METER                           ,"Stoppen Sie den Meter?"},
	/*2488*/ {IDS_HLD_STOP_METER                       ,"Stoppen Sie den Meter?"},
	/*2489*/ {IDS_HLD_DO_CAL                           ,"Haben Kalibrierung"},
	/*2490*/ {IDS_HLD_QUESTION                         ,"Frage"},
	/*2491*/ {IDS_HLD_PREAMP                           ,"Vorverstärker"},
	/*2492*/ {IDS_HLD_DBPK                             ,"dB<sub>pk</sub>"},
	/*2493*/ {IDS_HLD_MIC_SAVED                        ,"Empfindlichkeitsdaten an das Messgerät geschrieben."},
};
/*****************************************************************************/
// end of module
